### ISSUE TITLE
error in make with gcc version 4.3.2

### ISSUE THREAD

**Issue by ravikasyap1717** [whoshuu/cpr#103]
Hello,
When i make with gcc-4.3.2,it gives error in auth.h file.

when i do cmake .. result is
 Checking compiler flags for C++11 support.
-- C++0x is supported.
-- Checking compiler flags for C++11 support.
-- C++0x is supported.
-- C++ Requests CMake Options
So,let me know how will i resolve this. i have i586 GNU/Linux.

Thanks

**Comment by bobjansen** [comment]
It will be hard to help you if we don't know what the error is.

**Comment by iRajul** [comment]
@ravikasyap1717 Can you post your error here? Only then we can help .

**Comment by ravikasyap1717** [comment]
Hi,
Thanks for reply.
This error has been already resolved.

Thanks
