### ISSUE TITLE
does it support vs2010?

### ISSUE THREAD

**Issue by charlessoft** [whoshuu/cpr#108]
does it support vs2010?

**Comment by snikulov** [comment]
@charlessoft I believe, yes. [CMake ](https://cmake.org/)able to generate vs2010 projects.
Just use ```cmake <path to clone> -G"Visual Studio 10 2010"```

**Comment by charlessoft** [comment]
@snikulov it doesn't support vs2010, cpr use c++11 in same codes , but vs2010 not support

**Comment by dontsovcmc** [comment]
vs2010, vs2013 doesn't support C++11  :(

**Comment by COM8** [comment]
TLDR: No
