### ISSUE TITLE
Posible to build to mobile(ios)?

### ISSUE THREAD

**Issue by BernardTolosajr** [whoshuu/cpr#113]
Hi,
Trying to build it to ios, However Im getting Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR), Do i need to build the cpr curl using architectures(i386,armv7,armv7s,arm64)?

Im Using this toolchain https://github.com/cristeab/ios-cmake

Thanks in advance!

**Comment by BernardTolosajr** [comment]
Successfully build the cpr-example into iOS
https://github.com/BernardTolosajr/cpr-example/tree/build_ios

**Comment by whoshuu** [comment]
It looks like this can be closed. Marking this for closing, if you'd like to keep this open, give me an update and I'll keep it up.

**Comment by abmantis** [comment]
Is there any official docs on this?

**Comment by ospfranco** [comment]
@BernardTolosajr can you maybe give more specific instructions on how did you get it to compile for iOS?
