### ISSUE TITLE
Memory leak in session?

### ISSUE THREAD

**Issue by lurker99** [whoshuu/cpr#118]
Valgrind seem to find a memory leak in session.cpp

Here is the diff of the fix:
diff --git a/lib/cpr/cpr/session.cpp b/lib/cpr/cpr/session.cpp
index 485be10..8467006 100755
--- a/lib/cpr/cpr/session.cpp
+++ b/lib/cpr/cpr/session.cpp
@@ -90,6 +90,7 @@ void Session::Impl::freeHolder(CurlHolder\* holder) {
 CurlHolder\* Session::Impl::newHolder() {
     CurlHolder\* holder = new CurlHolder();
     holder->handle = curl_easy_init();
-    holder->chunk = NULL;
   return holder;
  }

@@ -108,6 +109,10 @@ void Session::Impl::SetParameters(Parameters&& parameters) {
 void Session::Impl::SetHeader(const Header& header) {
     auto curl = curl_->handle;
     if (curl) {
-        if (curl_->chunk) {
-            curl_slist_free_all(curl_->chunk);
-            curl_->chunk = NULL;
-        }
       struct curl_slist\* chunk = NULL;
       for (auto item = header.cbegin(); item != header.cend(); ++item) {
           auto header_string = std::string{item->first};

**Comment by nshcat** [comment]
You should post the diff in code tags to avoid the automatic formatting.

**Comment by lurker99** [comment]
Is it better now?

`diff --git a/lib/cpr/cpr/session.cpp b/lib/cpr/cpr/session.cpp
index 485be10..8467006 100755
--- a/lib/cpr/cpr/session.cpp
+++ b/lib/cpr/cpr/session.cpp
@@ -90,6 +90,7 @@ void Session::Impl::freeHolder(CurlHolder* holder) {
 CurlHolder* Session::Impl::newHolder() {
     CurlHolder* holder = new CurlHolder();
     holder->handle = curl_easy_init();
+    holder->chunk = NULL;
     return holder;
 }

@@ -108,6 +109,10 @@ void Session::Impl::SetParameters(Parameters&& parameters) {
 void Session::Impl::SetHeader(const Header& header) {
     auto curl = curl_->handle;
     if (curl) {
+        if (curl_->chunk) {
+            curl_slist_free_all(curl_->chunk);
+            curl_->chunk = NULL;
+        }
         struct curl_slist* chunk = NULL;
         for (auto item = header.cbegin(); item != header.cend(); ++item) {
             auto header_string = std::string{item->first};`

**Comment by thedrow** [comment]
You need ``` and a line break.

**Comment by whoshuu** [comment]
Closed in #188
