### ISSUE TITLE
Feature request: Support uploading files from memory

### ISSUE THREAD

**Issue by adam-nielsen** [whoshuu/cpr#120]
I would like to request the ability to POST files where the content is already in memory.  Currently the data must be written to a file on disk before `cpr` can attach it as a file.

`curl` already supports this, by use of [`CURLFORM_BUFFER`](https://curl.haxx.se/libcurl/c/curl_formadd.html#CURLFORMBUFFER) and `CURLFORM_BUFFERPTR`.

It looks like it would be relatively straightforward to implement, by doing something like this:

1. Create a new type similar to `cpr::File` that handles in-memory data, e.g. `cpr::Buffer`
2. Modify `cpr::Part` to accept `cpr::Buffer` as a parameter, similar to how it now accepts `cpr::File`
3. Add support to `cpr::Session::Impl::SetMultipart()` to attach a buffer using `CURLFORM_BUFFERPTR`.

This would allow you to do something like:
```
std::array<uint8_t, 1234> content;
auto r = cpr::Post(cpr::Url{"http://www.httpbin.org/post"},
                   cpr::Multipart{{"key", "large value"},
                                  {"name", cpr::Buffer{"filename.txt", content, "text/plain"}}});
```
I would be willing to implement this myself except I am unsure what the best data type would be for a buffer:

* `std::string` - most raw data is not in a C++ string
* `std::vector<unsigned char>` - this is perhaps the more C++ way of doing it, but again it will probably involve copying the existing buffer into a vector which is not very efficient
* `const uint8_t *` and `int length` - compatible with pretty much every buffer type, but there is a risk the caller will free the data before `curl` has finished with it, leading to a crash
* `std::shared_ptr<uint8_t *>` - safest as data will hang around until `cpr` has finished with it, but again most existing memory buffers will be difficult to fit into a `std::shared_ptr`.

If anyone has any suggestions for the ideal data type to represent most existing in-memory buffer types and that will ensure the caller doesn't delete the buffer while `curl` is still using it, let me know.

**Comment by nshcat** [comment]
I think that `cpr::Buffer` should take an iterator range. This would allow all kinds of sequential containers (including C-style arrays) to be used. What do you think about that?

**Comment by adam-nielsen** [comment]
That's quite a good idea!  I'm not too familiar with iterator ranges but if you can create them from most standard objects without causing the data to be copied, then they are perfect!

**Comment by adam-nielsen** [comment]
I have implemented this with iterator ranges as suggested, and it works well!  It is in #129.  I will close this issue now, since any discussion can probably happen over there instead.
