### ISSUE TITLE
Memory leak in multi-threaded program

### ISSUE THREAD

**Issue by dlee-libo** [whoshuu/cpr#122]
As if the lib doesn't work well in multi-threaded program.
Take below as an example:
```cpp
for (int i = 0; i < 28; i++) {
        thread([] {
            cpr::Session s;
            s.SetUrl(cpr::Url{"http://stackoverflow.com/"});
            auto response = s.Get();
        }).detach();
  }
while (true);
```

```cpp
for (int i = 0; i < 28; i++) {
        thread([] {
            cpr::Session s;
            s.SetUrl(cpr::Url{"http://stackoverflow.com/"});
            auto response = s.Get();
        }).join();
  }
while (true);
```
On my computer, the former code consumes about 20M while the latter one consumes only about 2M.

Do I need some extra calls when use this lib in multi-threaded program?

**Comment by whoshuu** [comment]
You're running 20 _simultaneous_ network calls in the first example, and 20 _consecutive_ network calls in the second one, so the delta in memory profiles is not unexpected.

**Comment by nabijaczleweli** [comment]
Second is effectively equivalent to dropping the `std::thread` stuff altogether.

The correctest way of doing this would be storing all `std::thread`s in a container and use 2 loops, one for spawning and the second for joining.
Pseudocode (no access to a real kb, using phone, sry):
```c++
vector<thread> thrs(28);
for(auto&t:thrs)
  t=thread(YOUR LAMBDA GOES HERE);
  
MAYBE MORE CODE W/E

for(auto&t:thrs)
  t.join();
```

**Comment by dlee-libo** [comment]
Sorry for unclear description. Actually, I measured the memory still hold by the process after all requests have bee done. But it turns out the 'problem' is std::string (used in WriteFunction) not returning memory back to the OS. It seems libstdc++ just cached memory for next allocation. I use this lib writing a crawler which will be running on a RaspberryPi, so I think maybe I need write my own allocator.
