### ISSUE TITLE
Cookies cannot be traversed

### ISSUE THREAD

**Issue by eXeC64** [whoshuu/cpr#123]
Currently, to access a cookie you need to know its key. As such, you cannot iterate through all the cookies, listing them unless you know which cookies are already set.

As far as I can tell, the simplest solution is just to implement `begin()` and `end()` methods that wrap the `map_`'s `begin()` and `end()`,  and provide `using iterator = std::map<std::string, std::string>::iterator;` in the class' definition.

**Comment by COM8** [comment]
Fixed by #365.
