### ISSUE TITLE
Compile in Visual Studio

### ISSUE THREAD

**Issue by AliRezaBeitari** [whoshuu/cpr#126]
Hi!
I cannot compile it in Visual Studio. I mean, I don't know how?!
Please help.

Thanks.

**Comment by nabijaczleweli** [comment]
Use CMake

**Comment by AliRezaBeitari** [comment]
It shows a lot of errors.

**Comment by nabijaczleweli** [comment]
Post them

**Comment by AliRezaBeitari** [comment]
These are all logs:

`$ cmake ..
-- Building for: Visual Studio 14 2015
-- The C compiler identification is MSVC 19.0.23918.0
-- The CXX compiler identification is MSVC 19.0.23918.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 14.0/VC/bin/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- C++ Requests CMake Options
-- =======================================================
--   USE_SYSTEM_CURL: OFF
--   BUILD_CPR_TESTS: ON
--   INSECURE_CURL: OFF
--   GENERATE_COVERAGE: OFF
--   CPR_CURL_NOSIGNAL: OFF
--   USE_SYSTEM_GTEST: OFF
--   CMAKE_USE_OPENSSL: ON
-- =======================================================
-- Not using system Curl, using built-in curl project instead.
CMake Warning at opt/curl/CMakeLists.txt:48 (message):
  the curl cmake build system is poorly maintained.  Be aware


-- curl version=[7.50.1]
CMake Warning at opt/curl/CMakeLists.txt:218 (message):
  Found no *nroff program


-- Looking for getch in ws2_32;
-- Looking for getch in ws2_32; - found
-- Looking for getch in winmm;ws2_32
-- Looking for getch in winmm;ws2_32 - found
-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_LIBRARIES OPENSSL_INCLUDE_DIR)
-- Looking for cldap_open in wldap32;winmm;ws2_32
-- Looking for cldap_open in wldap32;winmm;ws2_32 - found
-- Looking for include file winldap.h
-- Looking for include file winldap.h - not found
-- Looking for include file winber.h
-- Looking for include file winber.h - not found
-- Looking for include file ldap_ssl.h
-- Looking for include file ldap_ssl.h - not found
-- Looking for include file ldapssl.h
-- Looking for include file ldapssl.h - not found
-- Looking for idna_to_ascii_lz in idn;wldap32;winmm;ws2_32
-- Looking for idna_to_ascii_lz in idn;wldap32;winmm;ws2_32 - not found
CMake Warning at opt/curl/CMakeLists.txt:464 (find_package):
  By not providing "FindLibSSH2.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibSSH2", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibSSH2" with any
  of the following names:

    LibSSH2Config.cmake
    libssh2-config.cmake

  Add the installation prefix of "LibSSH2" to CMAKE_PREFIX_PATH or set
  "LibSSH2_DIR" to a directory containing one of the above files.  If
  "LibSSH2" provides a separate development package or SDK, be sure it has
  been installed.


-- Performing Test USE_UNIX_SOCKETS
-- Performing Test USE_UNIX_SOCKETS - Failed
-- Looking for include file windows.h
-- Looking for include file windows.h - found
-- Looking for include files windows.h, winsock.h
-- Looking for include files windows.h, winsock.h - found
-- Looking for 3 include files windows.h, ..., ws2tcpip.h
-- Looking for 3 include files windows.h, ..., ws2tcpip.h - found
-- Looking for 4 include files windows.h, ..., winsock2.h
-- Looking for 4 include files windows.h, ..., winsock2.h - found
-- Looking for 5 include files windows.h, ..., sspi.h
-- Looking for 5 include files windows.h, ..., sspi.h - found
-- Looking for 6 include files windows.h, ..., schannel.h
-- Looking for 6 include files windows.h, ..., schannel.h - found
-- Looking for 7 include files windows.h, ..., stdio.h
-- Looking for 7 include files windows.h, ..., stdio.h - found
-- Looking for 8 include files windows.h, ..., sys/filio.h
-- Looking for 8 include files windows.h, ..., sys/filio.h - not found
-- Looking for 8 include files windows.h, ..., sys/ioctl.h
-- Looking for 8 include files windows.h, ..., sys/ioctl.h - not found
-- Looking for 8 include files windows.h, ..., sys/resource.h
-- Looking for 8 include files windows.h, ..., sys/resource.h - not found
-- Looking for 10 include files windows.h, ..., sys/uio.h
-- Looking for 10 include files windows.h, ..., sys/uio.h - not found
-- Looking for 10 include files windows.h, ..., sys/un.h
-- Looking for 10 include files windows.h, ..., sys/un.h - not found
-- Looking for 11 include files windows.h, ..., arpa/tftp.h
-- Looking for 11 include files windows.h, ..., arpa/tftp.h - not found
-- Looking for 11 include files windows.h, ..., assert.h
-- Looking for 11 include files windows.h, ..., assert.h - found
-- Looking for 12 include files windows.h, ..., crypto.h
-- Looking for 12 include files windows.h, ..., crypto.h - not found
-- Looking for 12 include files windows.h, ..., des.h
-- Looking for 12 include files windows.h, ..., des.h - not found
-- Looking for 12 include files windows.h, ..., err.h
-- Looking for 12 include files windows.h, ..., err.h - not found
-- Looking for 12 include files windows.h, ..., errno.h
-- Looking for 12 include files windows.h, ..., errno.h - found
-- Looking for 14 include files windows.h, ..., idn-free.h
-- Looking for 14 include files windows.h, ..., idn-free.h - not found
-- Looking for 14 include files windows.h, ..., ifaddrs.h
-- Looking for 14 include files windows.h, ..., ifaddrs.h - not found
-- Looking for 15 include files windows.h, ..., krb.h
-- Looking for 15 include files windows.h, ..., krb.h - not found
-- Looking for 15 include files windows.h, ..., libgen.h
-- Looking for 15 include files windows.h, ..., libgen.h - not found
-- Looking for 15 include files windows.h, ..., limits.h
-- Looking for 15 include files windows.h, ..., limits.h - found
-- Looking for 16 include files windows.h, ..., locale.h
-- Looking for 16 include files windows.h, ..., locale.h - found
-- Looking for 17 include files windows.h, ..., netinet/tcp.h
-- Looking for 17 include files windows.h, ..., netinet/tcp.h - not found
-- Looking for 17 include files windows.h, ..., pem.h
-- Looking for 17 include files windows.h, ..., pem.h - not found
-- Looking for 17 include files windows.h, ..., poll.h
-- Looking for 17 include files windows.h, ..., poll.h - not found
-- Looking for 17 include files windows.h, ..., rsa.h
-- Looking for 17 include files windows.h, ..., rsa.h - not found
-- Looking for 19 include files windows.h, ..., ssl.h
-- Looking for 19 include files windows.h, ..., ssl.h - not found
-- Looking for 19 include files windows.h, ..., stdbool.h
-- Looking for 19 include files windows.h, ..., stdbool.h - found
-- Looking for 23 include files windows.h, ..., stropts.h
-- Looking for 23 include files windows.h, ..., stropts.h - not found
-- Looking for 24 include files windows.h, ..., tld.h
-- Looking for 24 include files windows.h, ..., tld.h - not found
-- Looking for 25 include files windows.h, ..., stddef.h
-- Looking for 25 include files windows.h, ..., stddef.h - found
-- Looking for 28 include files windows.h, ..., sys/utsname.h
-- Looking for 28 include files windows.h, ..., sys/utsname.h - not found
-- Looking for 28 include files windows.h, ..., idna.h
-- Looking for 28 include files windows.h, ..., idna.h - not found
-- Check size of size_t
-- Check size of size_t - done
-- Check size of ssize_t
-- Check size of ssize_t - failed
-- Check size of long long
-- Check size of long long - done
-- Check size of long
-- Check size of long - done
-- Check size of short
-- Check size of short - done
-- Check size of int
-- Check size of int - done
-- Check size of __int64
-- Check size of __int64 - done
-- Check size of time_t
-- Check size of time_t - done
-- Looking for basename
-- Looking for basename - not found
-- Looking for strncmpi
-- Looking for strncmpi - not found
-- Looking for alarm
-- Looking for alarm - not found
-- Looking for CRYPTO_cleanup_all_ex_data
-- Looking for CRYPTO_cleanup_all_ex_data - not found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for strtoll
-- Looking for strtoll - found
-- Looking for _strtoi64
-- Looking for _strtoi64 - found
-- Looking for strerror_r
-- Looking for strerror_r - not found
-- Looking for siginterrupt
-- Looking for siginterrupt - not found
-- Looking for fork
-- Looking for fork - not found
-- Looking for freeaddrinfo
-- Looking for freeaddrinfo - found
-- Looking for freeifaddrs
-- Looking for freeifaddrs - not found
-- Looking for pipe
-- Looking for pipe - not found
-- Looking for ftruncate
-- Looking for ftruncate - not found
-- Looking for getprotobyname
-- Looking for getprotobyname - found
-- Looking for getrlimit
-- Looking for getrlimit - not found
-- Looking for idn_free
-- Looking for idn_free - not found
-- Looking for idna_strerror
-- Looking for idna_strerror - not found
-- Looking for tld_strerror
-- Looking for tld_strerror - not found
-- Looking for setlocale
-- Looking for setlocale - found
-- Looking for setrlimit
-- Looking for setrlimit - not found
-- Looking for fcntl
-- Looking for fcntl - not found
-- Looking for ioctl
-- Looking for ioctl - not found
-- Looking for setsockopt
-- Looking for setsockopt - found
-- Looking for inet_pton
-- Looking for inet_pton - not found
-- Performing Curl Test HAVE_FCNTL_O_NONBLOCK
-- Performing Curl Test HAVE_FCNTL_O_NONBLOCK - Failed
-- Performing Curl Test HAVE_IOCTLSOCKET
-- Performing Curl Test HAVE_IOCTLSOCKET - Success
-- Performing Curl Test HAVE_IOCTLSOCKET_CAMEL
-- Performing Curl Test HAVE_IOCTLSOCKET_CAMEL - Failed
-- Performing Curl Test HAVE_IOCTLSOCKET_CAMEL_FIONBIO
-- Performing Curl Test HAVE_IOCTLSOCKET_CAMEL_FIONBIO - Success
-- Performing Curl Test HAVE_IOCTLSOCKET_FIONBIO
-- Performing Curl Test HAVE_IOCTLSOCKET_FIONBIO - Success
-- Performing Curl Test HAVE_IOCTL_FIONBIO
-- Performing Curl Test HAVE_IOCTL_FIONBIO - Failed
-- Performing Curl Test HAVE_IOCTL_SIOCGIFADDR
-- Performing Curl Test HAVE_IOCTL_SIOCGIFADDR - Failed
-- Performing Curl Test HAVE_SETSOCKOPT_SO_NONBLOCK
-- Performing Curl Test HAVE_SETSOCKOPT_SO_NONBLOCK - Failed
-- Performing Curl Test HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID
-- Performing Curl Test HAVE_SOCKADDR_IN6_SIN6_SCOPE_ID - Failed
-- Performing Curl Test HAVE_SOCKLEN_T
-- Performing Curl Test HAVE_SOCKLEN_T - Success
-- Performing Curl Test HAVE_BOOL_T
-- Performing Curl Test HAVE_BOOL_T - Success
-- Performing Curl Test HAVE_FILE_OFFSET_BITS
-- Performing Curl Test HAVE_FILE_OFFSET_BITS - Failed
-- Performing Curl Test HAVE_GLIBC_STRERROR_R
-- Performing Curl Test HAVE_GLIBC_STRERROR_R - Failed
-- Performing Curl Test HAVE_POSIX_STRERROR_R
-- Performing Curl Test HAVE_POSIX_STRERROR_R - Failed
-- Check size of curl_off_t
-- Check size of curl_off_t - failed
-- Check size of socklen_t
-- Check size of socklen_t - done
-- Performing Test curl_cv_recv
-- Performing Test curl_cv_recv - Success
-- Performing Test curl_cv_func_recv_test
-- Performing Test curl_cv_func_recv_test - Success
-- Tested: int recv(int, void *, size_t, int)
-- Performing Test curl_cv_send
-- Performing Test curl_cv_send - Success
-- Performing Test curl_cv_func_send_test
-- Performing Test curl_cv_func_send_test - Success
-- Tested: int send(int, const void *, size_t, int)
-- Performing Test HAVE_MSG_NOSIGNAL
-- Performing Test HAVE_MSG_NOSIGNAL - Failed
-- Performing Test HAVE_STRUCT_TIMEVAL
-- Performing Test HAVE_STRUCT_TIMEVAL - Success
-- Performing Test HAVE_POLL_FINE
-- Performing Test HAVE_POLL_FINE - Failed
-- Check size of sig_atomic_t
-- Check size of sig_atomic_t - done
-- Performing Test HAVE_SIG_ATOMIC_T_NOT_VOLATILE
-- Performing Test HAVE_SIG_ATOMIC_T_NOT_VOLATILE - Success
-- Check size of struct sockaddr_storage
-- Check size of struct sockaddr_storage - done
CMake Error at opt/curl/tests/CMakeLists.txt:4 (add_subdirectory):
  The source directory

    C:/Users/AliReza/Desktop/cpr/opt/curl/tests/unit

  does not contain a CMakeLists.txt file.


-- Enabled features: WinSSL IPv6 SSPI SPNEGO Kerberos NTLM
-- Enabled protocols: DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS LDAP POP3 POP3S RTSP SMTP SMTPS TELNET TFTP
-- Set CURL_FOUND to TRUE.
-- Set CURL_LIBRARIES to libcurl.
-- Set CURL_INCLUDE_DIRS to C:/Users/AliReza/Desktop/cpr/opt/curl/include;C:/Users/AliReza/Desktop/cpr/build/opt/curl/include/curl.
-- Not using system gtest, using built-in googletest project instead.
-- Found PythonInterp: C:/Python27/python.exe (found version "2.7.12")
-- Looking for pthread.h
-- Looking for pthread.h - not found
-- Found Threads: TRUE
-- Set GTEST_FOUND to TRUE.
-- Set GTEST_LIBRARIES to gtest.
-- Set GTEST_MAIN_LIBRARIES to gtest_main.
-- Set GTEST_BOTH_LIBRARIES to gtest;gtest_main.
-- Set GTEST_INCLUDE_DIRS to C:/Users/AliReza/Desktop/cpr/opt/googletest/include.
-- Building mongoose project for test support.
CMake Error at opt/CMakeLists.txt:102 (add_subdirectory):
  The source directory

    C:/Users/AliReza/Desktop/cpr/opt/mongoose

  does not contain a CMakeLists.txt file.


-- Set MONGOOSE_FOUND to TRUE.
-- Set MONGOOSE_LIBRARIES to mongoose.
-- Set MONGOOSE_INCLUDE_DIRS to .
CMake Error at opt/CMakeLists.txt:112 (set_property):
  set_property could not find TARGET mongoose.  Perhaps it has not yet been
  created.


-- Using CURL_INCLUDE_DIRS: C:/Users/AliReza/Desktop/cpr/opt/curl/include;C:/Users/AliReza/Desktop/cpr/build/opt/curl/include/curl.
-- Using CURL_LIBRARIES: libcurl.
-- Configuring incomplete, errors occurred!
See also "C:/Users/AliReza/Desktop/cpr/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/AliReza/Desktop/cpr/build/CMakeFiles/CMakeError.log".
`

**Comment by bobjansen** [comment]
It seems to me you need to get the git sub modules as described in the README under Usage.

**Comment by nabijaczleweli** [comment]
`git submodule update --init --recursive`

**Comment by ethanhs** [comment]
Okay, I have done all of the needed submodule cloning etc, and I am using VS 2015, which supports almost all C++11 constructs. The build fails with the OpenSSL you are using...

The log of building is [here](https://gist.github.com/ethanhs/8f7bc84ef4e35ddccecbb5a73975413f). I ran `mkdir build && cd build` then `cmake ..` then `cmake --build .`

The cmake toolchain does not work. I will look at using the sln based route and using MSVC builds of openssl.

**Comment by ethanhs** [comment]
So I downloaded the latest curl 7.51, and it seems the cmake build is okay after commenting out one of the test directories. I'll edit this with instructions if I get things working.

**Comment by rwebber** [comment]
OK, I have built the example... and it runs in vs 2015 for me.
I now need to add cpr to an existing project in VS2015

I have completed:
1: git submodule add git@github.com:whoshuu/cpr.git
2: git submodule update --init --recursive
but I am unsure how to proceed now since this current project is not using cmake.

Help would be greatly appreciated.

**Comment by mexus** [comment]
@rwebber, the simple answer would be "cpr is shipped with a cmake configuration file", and "cmake can produce VisualStudio 'project' files". If you need a hint on how to combine two project as one in VS, please fell free to ask, but maybe you can figure out that on your own? ;) and even post a guide on "how to use CPR in VS" :))

**Comment by ethanhs** [comment]
I believe your best thing to do would be to run cmake to generate VS project files, then reference the vcproj files in Visual Studio.

**Comment by rwebber** [comment]
I am getting close (i think)
getting an error with linking "cpr\build\lib\Debug\libcurl_imp.lib"
I don't have this file. In that location there is only 'cpr.lib'

I have the cpr project included in my solution, and referenced in my project.
my '#include <cpr/cpr.h>' is fine (no longer underlined in VS)
I have linked cpr.lib

But I don't see how to link a file that isn't in the cpr/build. Its not in the functional Example project build I have either.

hint?

**Comment by mexus** [comment]
@rwebber , here's a hint: libcurl -- is an actual C "curl" library, the project requires that to run. Apparently you don't have it installed system-wide (which is a given for Windows(tm) ), so you have to build it and link to it. AFAIR the "cpr" has an option of building it as well.

The thing is, I don't have currently the VS on my PC with that OS installed, so probably someone ho HAS that stuff running could give you some straightforward advises how to make everything run smoothly.

Having said that, I did that trick something like a year ago, but I can't recall how I managed the things.. But that's definitely possible.

In the worst case scenario I'll just install the VS and tell you how to manage this issue.

**Comment by rwebber** [comment]
Looking thru the cmakecache files, I can see that the make process used curl from my anaconda python3 library.
I then found a reference to this include lib in the cpr-example, and duplicated this to my new project.
Unfortunately the libcurl_imp.lib file is not in this curl library. So it doesn't work (I don't understand why the example project works?)
Admittedly building libs and linking is the edge of my c++ understanding currently.. so this is proving to be a challenge/learning experience.
Searching, I have found reference to libcurl_imp.ib on a few sites.
this one feels like its pointing me the right direction.. yet I don't know? http://mapserver.org/installation/win32.html

If I get this working.. I am happy to write up a how to article. I will need it as much as the next newbie.

**Comment by rwebber** [comment]
I can't seem to find a solution. How to build libcurl to produce the libcurl_imp.lib ?
I will watch this project.. and hopefully comeback to it. I like the format of the api.

**Comment by mexus** [comment]
@rwebber if you could wait for a day or two, I'll get to my PC and try to build one of my cpr-using projects from scratches. With VS, I mean :)

**Comment by ethanhs** [comment]
For the record:

I found the easiest way to get this to build was to install CURL from sources via its cmake system.
This installs it somewhere like C:\Program Files (x86)\CURL\.
Add that to a CMAKE_PREFIX_PATH and then it will find the system CURL and build as usual with the cmake system. I can submit a PR with precise instructions if desired.

**Comment by rwebber** [comment]
Thanks all.. I appreciated the help.
No problem holding for a few days.
At this point, I need to uninstall/clean up and go for a clean build.
any step by steps would be hugely helpful.

**Comment by ethanhs** [comment]
Okay, I think I've figured out a couple of things:

First of all, everything builds fine using the normal procedure as long as you:
```
$ set INSECURE_CURL=ON
$ set CMAKE_USE_OPENSSL=OFF
```
You can then:
```
$ git clone https://github.com/whoshuu/cpr
$ git submodule update --init
$ mkdir build && cd build
$ cmake ..
$ cmake --build .
```

And it _should_ build fine. The first two variables are not really documented anywhere...

Anyway. If you want SSL so you can do requests over HTTPS and the like, then you need to install CURL yourself. Here are my instructions for that:

CURL by default builds 32bit, I'm still working on getting Win64 to compile as the cmake system doesn't quite work... I'll post Win64 instructions when I get it working.

If you want libssh2 support for things like SFTP and other ssh protocols:
[use these instructions to install libssh2](https://github.com/libssh2/libssh2/blob/master/docs/INSTALL_CMAKE)

```
$ git clone https://github.com/curl/curl.git
$ cd curl
$ mkdir build32 && cd build32
$ cmake ..
$ cmake --build .
```
You may want to verify that the WINSSL was used and that the HTTPS protocol is on. It will show this in the output after running `cmake ..`:
```
-- Enabled features: WinSSL IPv6 AsynchDNS Largefile SSPI SPNEGO Kerberos NTLM
-- Enabled protocols: DICT FILE FTP FTPS GOPHER HTTP HTTPS IMAP IMAPS LDAP POP3 POP3S RTSP SMTP SMTPS TELNET TFTP
```

Then you need to move to an __ADMIN__ command prompt to install curl:
```
$ cmake --build . --target install
```

So now CURL should be in C:\Program Files (x86)\CURL\

You need to add that path to an environment variable named CMAKE_PREFIX_PATH. I put this in my system environment variables so I can always use CURL.

So now for the main part: building cpr.

```
$ git clone https://github.com/whoshuu/cpr.git
$ cd cpr
$ mkdir build32 && cd build32
$ cmake .. -DUSE_SYSTEM_CURL
$ cmake --build .
```
The binaries should be useable now!

**Comment by rwebber** [comment]
Wow.. fantastic.
I will give this a try today. Glad to hear there was something outside the documentation that may have been my hangup.
I will report back once I have gone thru both methods.

**Comment by ilkeryasinaksoy** [comment]
@rwebber I found the solution. I used openssl vs 2015 dll's. (http://p-nand-q.com/programming/windows/building_openssl_with_visual_studio_2013.html). I add entry cmake-gui (OPENSSL_ROOT_DIR) and set path to "openssl-1.1.0c-64bit-release-DLL-VS2015". Then i build cpr with this settings: BUILD_CPR_TESTS , BUILD_TESTING, CMAKE_USE_LIBSSH2(unthick). And i find cpr.lib,libcurl_imp.lib and libcurl.dll in ,...cpr\build\lib\Release folder. I linked VS2015 and working fine! Sorry my very very very bad English.

**Comment by COM8** [comment]
Should be fixed. Feel free to open a new issue in case this is still a problem.
