### ISSUE TITLE
Memory leak - curl_formfree() not used after multipart POST

### ISSUE THREAD

**Issue by adam-nielsen** [whoshuu/cpr#128]
`curlform_add()` is used in `session.cpp` to build forms, however [according to the curl documentation](https://curl.haxx.se/libcurl/c/curl_formfree.html) the `formpost` variable must be passed to `curlfree()` after the form has been submitted.

cpr does not do this, so it leaks a little memory every time a multipart form is POSTed.

**Comment by dlee-libo** [comment]
I think store formpost in CurlHolder would be better.  And unique_ptr with  custom deleter is much cleaner.
[I just did it in my fork](https://github.com/dlee-libo/cpr/commit/8f3979eb53290cc85ff10d5e648e966606b1ca0e)

**Comment by adam-nielsen** [comment]
That would work too - either fix is fine with me.

**Comment by whoshuu** [comment]
Fixed in https://github.com/whoshuu/cpr/commit/075fd0dce606c584d6d5eb5581e09437c908c778.
