### ISSUE TITLE
Incorporate JSON class/parser

### ISSUE THREAD

**Issue by nholthaus** [whoshuu/cpr#135]
In #37 the idea of integrating a JSON library (such as [Niels Lohmann's library](https://github.com/nlohmann/json)) was brought up, and then decided against presumably to keep the library clean.

I have to say I respectfully disagree with that point of view. A substantial number of REST APIs use JSON, and I think it would add a lot of value to be able to generate JSON body data within the library. As an optional sub-module, I don't see why it would get in anyone's way.

I'm just a single data point, but I'm planning to tack it on in my implementation via an `operator std::string` conversion for `json` classes, and I doubt I'm the only person to mash these two libraries together.

**Comment by Dark-Passenger** [comment]
👍  but the question is is this going to mimic python requests or not. if yes an option to provide a json object as a payload should be an option.

PS: use python requests extensively for only json post and get requests.

@whoshuu thoughts ?

**Comment by whoshuu** [comment]
@nholthaus, I've thought about this more as I've used the library in my own projects. I often do use this library in conjunction with Niels' library.

With that said, I respectfully disagree with your disagreement 😏.

At the risk of sounding pedantic, I'll state my reasons as clearly as I can here, and let this ticket be the central point of discussion on this issue.

1. REST APIs are but a small subset of the total universe of HTTP interfaces one can query. All HTTP services operate in a "string" world, but not all of them care about structured data as JSON.
2. Even when APIs do care about structured data, JSON is a small subset of structured data. In addition to JSON, I've used this library to query protobuf and msgpack interfaces as well.
3. The cost per user of integrating a JSON library is exceedingly low (and getting lower). Niels' library can be dropped in as a header only library. The cost per user of integrating a JSON library is exactly identical to the benefit per user of including a JSON library in the project, discounted against the above facts that not every user will want a JSON library in the first place. You have to discount it further with the fact that not every user will want a particular JSON library, for reasons I'm in no position to impose on those users. Pricing all of these into the total benefits calculation for including a JSON library, I feel no compulsion to include a particular library, even if the cost to me, the maintainer, were negligible or non-existent.
4. The cost to include a third party library is in fact not negligible. There's the maintenance burden of keeping that library up to date across releases and branches, even if the only thing I use that library for is to do some internal stuff for me that I'm not willing to do myself.
5. But, it's not true that such a library would be implementation-world only. It would become part and parcel to the interface, and as a result, it would expose an additional maintenance burden on the project when users have issues related to that interface.

I know it sounds like that I'm pretty much convinced that not including a JSON library is the right thing to do, and you wouldn't be far off the mark if you believed that.

I'd like to think that I'm a reasonable person, and as a result, I would be open to reason. If you have objections to any of the points I made above, or have reasons for the other side that you'd like to bring up, please, I'm all ears. Being just one person, I've definitely not thought of every side of the issue, and I could be convinced that I'm wrong if the right argument is made.

**Comment by nholthaus** [comment]
I respect your opinion. The "goodness" of the integration would really only come from returning `json` objects from the queries, which means the additional library would have to be part of the interface, incurring all the maintenance downsides you mention. I also agree that a REST/JSON specialization would narrow the library scope.

That said, the specialized interface would certainly be of value for some applications, so I think I'm talking myself into forking this idea into a new library, where the integration and maintenance could be handled separately from either implementation.

**Comment by COM8** [comment]
Closing this.
Feel free to create a new issue/PR in case there is still a loot of requests for something like this.
