### ISSUE TITLE
invalid pointer traced back to a Session::Get

### ISSUE THREAD

**Issue by pellet** [whoshuu/cpr#136]
Getting an invalid pointer crash on linux but not osx.
When debugging with valgrind on OSX I get the following:

`==6791== Process terminating with default action of signal 11 (SIGSEGV)
==6791==  Access not within mapped region at address 0x70000557A43E
==6791==    at 0x100872351: _pthread_find_thread (in /usr/lib/system/libsystem_pthread.dylib)
==6791==    by 0x1008722CF: _pthread_lookup_thread (in /usr/lib/system/libsystem_pthread.dylib)
==6791==    by 0x10087361A: pthread_join (in /usr/lib/system/libsystem_pthread.dylib)
==6791==    by 0x100324C6D: Curl_thread_join (in /usr/lib/libcurl.4.dylib)
==6791==    by 0x100325F41: destroy_async_data (in /usr/lib/libcurl.4.dylib)
==6791==    by 0x1003260E0: Curl_resolver_is_resolved (in /usr/lib/libcurl.4.dylib)
==6791==    by 0x100316986: multi_runsingle (in /usr/lib/libcurl.4.dylib)
==6791==    by 0x1003166E1: curl_multi_perform (in /usr/lib/libcurl.4.dylib)
==6791==    by 0x10030FB13: curl_easy_perform (in /usr/lib/libcurl.4.dylib)
==6791==    by 0x1000CB84C: cpr::Session::Impl::makeRequest(void*) (session.cpp:356)
==6791==    by 0x1000CC29B: cpr::Session::Impl::Get() (in ./cpp_core_test_main)
==6791==    by 0x1000CD1E6: cpr::Session::Get() (in ./cpp_core_test_main)
`

I am calling multiple get requests and it crashes around the third request, so this could have something to do with it.

**Comment by nabijaczleweli** [comment]
MCVE?

**Comment by pellet** [comment]
The problem could actually be more to do more with the libcurl version which was packaged with coreos and how it handles multiple threads hitting it.  I've experimented with different versions of libcurl and had different results, I'm currently not getting a crash whilst running against libcurl4-openssl-dev amd64 7.50.1-1

**Comment by pellet** [comment]
i'll close this for now because it was hard to trace down an exact way to replicate it, if someone could point me to any documentation on which curl versions/features aren't supported it would be helpful.
