### ISSUE TITLE
Missing SSL certificate option(s) for https request.

### ISSUE THREAD

**Issue by WolverinDEV** [whoshuu/cpr#137]
Hello,
i need some options for using ssl certificates for an HTTPS request

**Comment by sago007** [comment]
I think I need this too.
I keep getting:
```
SSL certificate problem: unable to get local issuer certificate
```
I can turn it off in test but that are not acceptable in a production environment.
I know I have the certificates in "/etc/ssl/certs/" but nothing I can do to use them.

**Comment by COM8** [comment]
Should be fixed. Feel free to open a new issue in case this is still a problem.
