### ISSUE TITLE
How to set SOCKS5 proxy?

### ISSUE THREAD

**Issue by shiyanhui** [whoshuu/cpr#138]
Hi,

I can't figure out how to set socks5 proxy. I replaced `http` with `socks5`, but it didn't work. I also viewed the document and `test/proxy_test.cpp` but without result. Could you give some advise? Thanks.

**Comment by dlee-libo** [comment]
It seems won't work. Checkout session.cpp, you will find out that it uses protocol of your URL to decide proxy policy. So if your URL is 'http://xxxx' then it will try to use proxy like {'http', 'something'}

**Comment by shiyanhui** [comment]
I fixed it with Surge. Thanks anyway :)

**Comment by NekoDragonica** [comment]
In case someone need similar answer, add "socks5://" before a proxy address like {"http", "socks5://127.0.0.1:9999" }
