### ISSUE TITLE
text files are modified if downloading via range requests

### ISSUE THREAD

**Issue by pellet** [whoshuu/cpr#140]
line 379 of session.cpp has:
```c++
    response_string = cpr::util::parseResponse(response_string);
```
the method's definition:
```c++
std::string parseResponse(const std::string& response) {
    if (!response.empty()) {
        if (response.back() == '\n') {
            return response.substr(0, response.length() - 1);
        }
    }

    return response;
}
```
It strips newlines at the end of a response, this caused a carriage return to be stripped from a text file downloaded in sections.
I commented this line out and now the downloaded file matches the source file.
I'm not sure why this is done? Could i be causing more harm than good?

**Comment by nabijaczleweli** [comment]
Ooooo, this is naaaaaaaaaaasty

**Comment by whoshuu** [comment]
Interesting find. Looks like it was added in this commit: https://github.com/whoshuu/cpr/commit/8e3a78f8dc51206214b4a996043e133be99bcb04. The only test that fails if I comment out the pruning is `BasicTests.ResourceNotFoundTest`, which is trivially fixable by changing the expected response text to include the newline.

**Comment by whoshuu** [comment]
Feel free to throw in a pull request to address this issue. You can in fact just get rid of the parsing entirely I think, since `parseResponse` does only that newline pruning.
