### ISSUE TITLE
Memory leak in session - header parsing

### ISSUE THREAD

**Issue by thejinx0r** [whoshuu/cpr#144]
Hi,

There's a potential memory leak in session.cpp when parsing headers:
Here's a patch, but I don't think this is the best way to do it.

```
74d73
< #ifdef INSECURE_CURL
77c76
< #endif

---
>
115c114,115
<         struct curl_slist* chunk = NULL;

---
>         struct curl_slist* chunk = NULL, *temp = NULL;
>
116a117
>             temp = NULL;
123c124,130
<             chunk = curl_slist_append(chunk, header_string.data());

---
>
>             temp = curl_slist_append(chunk, header_string.data());
>             while(temp == NULL){
>                 temp = curl_slist_append(chunk, header_string.data());
>             }
>             chunk = temp;
>
```

For more information, see:
https://github.com/collectd/collectd/pull/1639 and https://github.com/collectd/collectd/pull/1671

Essentially
curl_slist_append() overwrote previous pointer which would leak if
any curl_slist_append() failed since it returns NULL in case of errors.

**Comment by thejinx0r** [comment]
Could be related to #118, but someone needs to edit the formating in #118.

**Comment by erengy** [comment]
Do we need `curl_->chunk`, `chunk` and `temp` for this? Assuming that the `while` loop is necessary and `curl_->chunk` is initialized to `NULL`, I feel like this should be enough:

```cpp
struct curl_slist* chunk = NULL;
while (chunk == NULL) {
    chunk = curl_slist_append(curl_->chunk, header_string.data());
}
curl_->chunk = chunk;
```

Speaking of which, calling `curl_easy_setopt` once after the `for` loop should be enough too; no need to call it for each chunk.

If it's any help, looks like `curl_slist_append` returns `NULL` only if it [can't](https://github.com/curl/curl/blob/9297ca49f5f3caca938a679b9c1feeb719e61ddb/lib/slist.c#L95) `strdup` the data or [can't](https://github.com/curl/curl/blob/9297ca49f5f3caca938a679b9c1feeb719e61ddb/lib/slist.c#L68) `malloc` the new item.

**Comment by thejinx0r** [comment]
I'm not sure if the loop is necessary, but I tought that would be the most straightforward thing to do without throwing an exception.
