### ISSUE TITLE
Build fails on Windows with gcc 7

### ISSUE THREAD

**Issue by Sodivad** [whoshuu/cpr#145]
The error occurs for all the ...Async Methods (GetAsync, PostAsync, PutAsync, HeadAsync, ...)
`/cpr/cpr.h:4:0,
                 from \cpr\test\error_tests.cpp:6:
/cpr/include/cpr/api.h: In function 'cpr::AsyncResponse cpr::GetAsync(Ts ...)':
cpr/include/cpr/api.h:46:32: error: return type 'using AsyncResponse = class std::future<cpr::Response> {aka class std::future<cpr::Response>}' is incomplete
 AsyncResponse GetAsync(Ts... ts) {`

**Comment by nshcat** [comment]
Considering that GCC 7 is a preview release, this most likely is a bug in the compiler and not in CPR. You could try to boil it down to a minimal reproducible example and file the bug with the GCC people.

**Comment by Sodivad** [comment]
Actually it seems to be an issue with MinGW as the build completes when I use a MinGW with posix threading model. But fails if the threading model is win32. It seems that <future> is unimplemented without poxis threading.
http://stackoverflow.com/questions/10209871/c11-stdasync-doesnt-work-in-mingw
