### ISSUE TITLE
Is this library production ready?

### ISSUE THREAD

**Issue by himanshub16** [whoshuu/cpr#146]
I would like to know that can I completely rely on this library for my project. My project needs simple HTTP requests and need to work on all three major OSes. 
Even if it works for just HTTP, it would suffice. I don't need HTTPS.
Also, I would like to know that I should use the master branch or one from the releases. However, the releases seem very old.

**Comment by thedrow** [comment]
I agree that a new release should be made. This project looks interesting enough that I might provide Python bindings as an alternative to PyCurl but it has to be more stable before I do so.
Maybe you should call for more maintainers?

**Comment by himanshub16** [comment]
I would advice not to take Python into consideration. Python already has request module. The time and resources you have should be directed towards making C++ platform better, and ruling out the missing features of the ecosystem. Better do one thing and do it best. 
Instead of Python bindings, it would be great if we could figure out more projects/libraries which ease out network programming on C++. Or something like, which brings the cool features of Python to C++, the same way cpr did for HTTP requests.

But as of now, I would like to know whether it is production ready?

**Comment by nabijaczleweli** [comment]
It is, use `master`.

Also, why wouldn't HTTPS work?

**Comment by himanshub16** [comment]
HTTPS would definitely work. I don't need it for now.

It would be great to have some instructions on how to use and integrate with any project.

**Comment by nabijaczleweli** [comment]
What do you mean by "some instructions on how to use & integrate"? It has a `CMakeLists.txt`, just use CMake.

**Comment by himanshub16** [comment]
Got it. Thanks. :smiley:

**Comment by himanshub16** [comment]
Ok. CMake is fine. But, I want to integrate with Qt which uses qmake. 
I don't have much idea on how to use it.

**Comment by nabijaczleweli** [comment]
You've entered "Figure it out for yourself" lang
