### ISSUE TITLE
build fail on windows 10 with QT5.7 MingW

### ISSUE THREAD

**Issue by shanecode** [whoshuu/cpr#150]
OS: windows 10 x64
QT 5.7 
MINGW 530_32
get error:

\cpr\opt\googletest\include\gtest\internal\gtest-port.h:1787: error: 'AutoHandle' does not name a type
   AutoHandle thread_;
   ^

**Comment by kracejic** [comment]
Just in case you find this issue, easiest think to do is to disable building of tests:

    cmake -DBUILD_CPR_TESTS=OFF ..
