### ISSUE TITLE
bug when parse cookie

### ISSUE THREAD

**Issue by dlee-libo** [whoshuu/cpr#159]
The lib doesn't parse cookie correctly when the server set cookie to an empty value.
example:
Set-Cookie: name=;
Then we will get a cookie whoes name is '0' and value is 'name'

**Comment by mexus** [comment]
Could you please provide a patch to fix that problem?
It seems like the maintainer of this repo is out for some time..

**Comment by COM8** [comment]
It looks like this has been fixed some time in the past.
