### ISSUE TITLE
Build fails on Arch Linux

### ISSUE THREAD

**Issue by noh4hss** [whoshuu/cpr#177]
Fails during linking:
```
[ 31%] Linking CXX executable ../bin/alternating_tests
/usr/bin/ld: CMakeFiles/alternating_tests.dir/server.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
/usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line
```
Fixed it by adding pthread to target_link_libraries in test/CMakeLists.txt but of course it's not very portable.

**Comment by whoshuu** [comment]
Is there a CMake-land test for Arch Linux or more specifically for this link requirement?

**Comment by noh4hss** [comment]
The build fail only occurs when building using system gtest.
I can't test on another Linux distro but this issue probably applies to Linux not just Arch.
On linux you have to link to pthread or add "-pthread" flag.

I added a pull request that fixes it while not breaking buiild process on other platforms.
You can also probably fix it by checking if compiler has "-pthread" flag and then adding it.
