### ISSUE TITLE
Usage on windows

### ISSUE THREAD

**Issue by Loreleix64** [whoshuu/cpr#179]
Is there any easy way to use this on Windows? I can't figure out how, especially since I can't get make to run on mingw.

**Comment by whoshuu** [comment]
You should give `CMake` a try on Windows. It can be used to [generate Visual Studio project files](http://stackoverflow.com/a/9259836/2297365). I'm not an expert myself on that process but I know it's possible.

**Comment by Loreleix64** [comment]
Compiling with Visual Studio gives me an error about the VS runtime DLLs missing when run, even after those DLLs are installed, and Visual Studio being set to statically link instead of look for the DLLs.

**Comment by Loreleix64** [comment]
Also, when setting CMake to create a CodeBlocks project file and then compiling from there, I get a bunch of undefined references to curl.

**Comment by Pwera** [comment]
Build curl in insecure mode, then in Your final app link to curl lib.

**Comment by Loreleix64** [comment]
Nevermind, I managed to get make to work, the command was mingw32-make and not just make.
