### ISSUE TITLE
Add CA path to VerifySSL

### ISSUE THREAD

**Issue by apollo13** [whoshuu/cpr#189]
it would be nice if the user could add a custom CA path to VerifySSL which then gets set with https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html -- this is useful if the system CA is bogus or one is using self-signed certs at some point.

If that is okay I'll prep a PR adding that.

**Comment by apollo13** [comment]
@whoshuu Do you have any thoughts on the linked fix? Is it good, does it require something else?

**Comment by whoshuu** [comment]
Hey @apollo13! I think it's a good idea to add an option to specify a custom ca info path, but I'd much rather it be it's own object altogether. This is how most libraries handle this (and this is how curl does it too, the options are separate), and it would be most consistent with how cpr does things already.

**Comment by codergs** [comment]
This is a great PR, would love to see this go through on the CPR master.

**Comment by jungletek** [comment]
This patch works nicely, thank you so much!

**Comment by COM8** [comment]
Is there still a PR open for this?
Or can this issue be closed.
