### ISSUE TITLE
Compile fails on Linux (G++)

### ISSUE THREAD

**Issue by ghost** [whoshuu/cpr#201]
When I try to compile I get this weird error:

> [~/Dev]$ g++ test.cpp -I cpr/include                                                
/tmp/ccufpOuC.o: In function `cpr::Response cpr::Get<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cpr::Authentication>(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&, cpr::Authentication&&)':
test.cpp:(.text._ZN3cpr3GetIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14AuthenticationEEEENS_8ResponseEDpOT_[_ZN3cpr3GetIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14AuthenticationEEEENS_8ResponseEDpOT_]+0x1d): undefined reference to `cpr::Session::Session()'
test.cpp:(.text._ZN3cpr3GetIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14AuthenticationEEEENS_8ResponseEDpOT_[_ZN3cpr3GetIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14AuthenticationEEEENS_8ResponseEDpOT_]+0x60): undefined reference to `cpr::Session::Get()'
test.cpp:(.text._ZN3cpr3GetIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14AuthenticationEEEENS_8ResponseEDpOT_[_ZN3cpr3GetIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14AuthenticationEEEENS_8ResponseEDpOT_]+0x6d): undefined reference to `cpr::Session::~Session()'
test.cpp:(.text._ZN3cpr3GetIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14AuthenticationEEEENS_8ResponseEDpOT_[_ZN3cpr3GetIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_14AuthenticationEEEENS_8ResponseEDpOT_]+0x7e): undefined reference to `cpr::Session::~Session()'
/tmp/ccufpOuC.o: In function `void cpr::priv::set_option<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >(cpr::Session&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&&)':
test.cpp:(.text._ZN3cpr4priv10set_optionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRNS_7SessionEOT_[_ZN3cpr4priv10set_optionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRNS_7SessionEOT_]+0x2a): undefined reference to `cpr::Session::SetOption(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
/tmp/ccufpOuC.o: In function `void cpr::priv::set_option<cpr::Authentication>(cpr::Session&, cpr::Authentication&&)':
test.cpp:(.text._ZN3cpr4priv10set_optionINS_14AuthenticationEEEvRNS_7SessionEOT_[_ZN3cpr4priv10set_optionINS_14AuthenticationEEEvRNS_7SessionEOT_]+0x2a): undefined reference to `cpr::Session::SetOption(cpr::Authentication const&)'
collect2: Fehler: ld gab 1 als Ende-Status zurück

Sourcecode:
`#include <iostream>
#include <curl/curl.h>
#include <cpr/cpr.h>

using namespace std;

int main(){
	auto r = cpr::Get(cpr::Url{"http://www.httpbin.org/basic-auth/user/pass"},
        cpr::Authentication{"user", "pass"});
	cout << r.text << endl;
	return 0;
}	`

Fails with every example I tried to compile.

**Comment by dlee-libo** [comment]
Hey man, you need to link with the lib. g++ -L cpr/lib -l cpr
