### ISSUE TITLE
cpr::Post http method is GET

### ISSUE THREAD

**Issue by Jenuce** [whoshuu/cpr#203]
there is my example:
cpr::Post(cpr::Url{url});
I had captured the http package,  I fond the http method is GET.

error in the code (session.cpp)
Response Session::Impl::Post() {
    auto curl = curl_->handle;
    if (curl) {
        curl_easy_setopt(curl, CURLOPT_HTTPGET, 0L);   ////////////should CURLOPT_HTTPPOST
        curl_easy_setopt(curl, CURLOPT_NOBODY, 0L);
    }

    return makeRequest(curl);
}

**Comment by yoni386** [comment]
Hello,

is there solution? Can you please share example how to post? cpr::Post do Get

**Comment by armata** [comment]
Same issue here.
