### ISSUE TITLE
Port to Beast?

### ISSUE THREAD

**Issue by vinniefalco** [whoshuu/cpr#205]
Any chance we could get the wonderful interface of this library ported to use Beast?

Repository:
https://github.com/vinniefalco/Beast/

Docs:
http://vinniefalco.github.io/beast/index.html

**Comment by Ninja-007** [comment]
I checked beast library. It is interesting for me. But I am not your intended user(I need for mobile app.). It will be great if someone can integrate beast and this library. May be this project is in dormant state, no replies on issues and no new commit. :(

**Comment by vinniefalco** [comment]
Beast is usable on mobile devices, or am I misunderstanding?

**Comment by Ninja-007** [comment]
sorry for misunderstading. I saw your presentation from cppcon. You said that your library is for another library developers, not for app developers. So it is not for me.
Another thing which I do not like about beast is usage of boost headers other than async. Library with only standalone asio is my first choice.

**Comment by vinniefalco** [comment]
Why are you afraid of Boost?

**Comment by Ninja-007** [comment]
Too many dependencies and no official port.

**Comment by vinniefalco** [comment]
There's no official port of Boost to your mobile platform?

**Comment by Ninja-007** [comment]
yes

**Comment by nshcat** [comment]
Why would it be ported to beast? It's a very thin C++ wrapper around Curl. I think porting it would be pretty out of the scope of this project. Why not just make a new library for that, using the same style of API design?

**Comment by Ninja-007** [comment]
By any chance, beast will come without boost and only with standalone asio?

**Comment by vinniefalco** [comment]
No.

**Comment by Ninja-007** [comment]
Thanks

**Comment by COM8** [comment]
No. Sorry there is currently no plan for this.
