### ISSUE TITLE
Use Cpr in a Qt Project (MinGW)

### ISSUE THREAD

**Issue by AliRezaBeitari** [whoshuu/cpr#206]
How to import and use Cpr library in a Qt project?! (Compiler: MinGW)

**Comment by arcan1s** [comment]
am sorry, but why? Qt provides own QtNetwork module, which is integrated into Qt framework (signals and slots, data representation classes and so on), which is not hard to use.

But nevertheless there are no issues to use it in qt project, but it might require some class conversions.
