### ISSUE TITLE
Body does not support cpr::File

### ISSUE THREAD

**Issue by ilkeraksoy** [whoshuu/cpr#212]
cpr::Body{cpr::File{"json.txt"}} -> i am getting error for this. please fix this. Sorry my very bad English.

**Comment by whoshuu** [comment]
You need to wrap a `cpr::File` inside of a `cpr::Multipart` in your POSTs. See the test here: https://github.com/whoshuu/cpr/blob/3b768350ce30635df131e488faeec17430ebe5dc/test/post_tests.cpp#L138.
