### ISSUE TITLE
USE_SYSTEM_CURL compile and probability 

### ISSUE THREAD

**Issue by yoni386** [whoshuu/cpr#214]
Hello,

How to use  curl  -> USE_SYSTEM_CURL: OFF
I would it to be static, probable as much is possible. Even if the OS has libcurl.

How to fix it?

-- Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the system variable OPENSSL_ROOT_DIR (missing:  OPENSSL_INCLUDE_DIR)

**Comment by whoshuu** [comment]
CPR doesn't have an embedded TLS library, so if you want to use the embedded curl, you either have to turn off TLS (`CMAKE_USE_OPENSSL`), or you build and provide your own OpenSSL (or TLS library) using `OPENSSL_ROOT_DIR` and `OPENSSL_INCLUDE_DIR`.

To specify `USE_SYSTEM_CURL: OFF`, do this with CMake:

```
cmake -DUSE_SYSTEM_CURL=OFF ..
```

and check the output from  the command to verify that system curl isn't being used.

Also make sure that you pull in all of the optional submodules with `git submodule update --init --recursive`.
