### ISSUE TITLE
CURLOPT_VERBOSE environment variable doesn't appear to have any effect

### ISSUE THREAD

**Issue by TheAssassin** [whoshuu/cpr#236]
I'm trying to resolve a nasty bug in one of my applications which uses both CPR and, in some legacy C code, CURL directly.

So, as usual, I've set `CURLOPT_VERBOSE=1` in my environment, ran my application and expected to see some verbose logging output. However, I could see those only for the requests made with CURL, not for the ones made with CPR.

Is there anything that might prevent CPR's requests from showing up in the log? I am in the progress of replacing the legacy code with CPR (it'd be a _lot_ shorter and way more elegant that way), but I really need `CURLOPT_VERBOSE` to work as intended.

Any input is highly appreciated.

Maybe we could add some verbosity feature to CPR (like calling `cpr::setVerbose(true)`) which controls this behavior globally and/or session wide (for normal requests, a global switch would suffice in my opinion), and implement it like it was done here https://github.com/whoshuu/cpr/commit/d837d87f90221758cb1419ef8ee335af6b32d342#diff-7807c1d828315695457566273ce727aeR284.

**Comment by dontsovcmc** [comment]
For loggin you should also call:
```
            curl_easy_setopt(curl_, CURLOPT_VERBOSE, 1L);     //you added
            curl_easy_setopt(curl_, CURLOPT_DEBUGFUNCTION, trace_function);
            curl_easy_setopt(curl_, CURLOPT_DEBUGDATA, &log_cfg);
```

trace_function example:
```
struct log_config {  //this structure will be in trace_function argument 'userp'
    std::string *out;
    std::mutex  *out_mutex;
} log_cfg;

static int trace_function(CURL *handle, curl_infotype type,
                          char *data, size_t size,
                          void *userp)
{
    struct log_config *config = (struct log_config *)userp;

    Lock_guard lock(*config->out_mutex);
    std::string *out = config->out;
    (void)handle; /* prevent compiler warning */
    if (!out) return 0;

    switch (type) {
        case CURLINFO_TEXT:
            fprintf(stderr, "== Info: %s", data);
        default: /* in case a new one is introduced to shock us */
            return 0;

        case CURLINFO_HEADER_OUT:
            *out += "=> CURL:Send header";
            break;
        case CURLINFO_DATA_OUT:
            *out += "=> CURL:Send data";
            break;
        case CURLINFO_SSL_DATA_OUT:
            *out += "=> CURL:Send SSL data";
            break;
        case CURLINFO_HEADER_IN:
            *out += "<= CURL:Recv header";
            break;
        case CURLINFO_DATA_IN:
            *out += "<= CURL:Recv data";
            break;
        case CURLINFO_SSL_DATA_IN:
            *out += "<= CURL:Recv SSL data";
            break;
    }
    *out += " (" + std::to_string(size) + " bytes)\n";
    std::string t(data, size);
    *out += t;
    return 0;
}

```

**Comment by xloem** [comment]
Note that in 2018 41f3f76f9c0b475b5956c09c2213c9478e588949 added cpr::Verbose which does the same thing as CURLOPT_VERBOSE .  Is that sufficient?
