### ISSUE TITLE
how to get response headers for string?

### ISSUE THREAD

**Issue by smarttang** [whoshuu/cpr#240]
RT;
I want get response headers information,but i don't know how to get it.
in my work,I want to get:
The complete message of the request
Returns the body's full message。。。。

**Comment by t0trader** [comment]
@smarttang 

`	fstream fLog("log.txt",ios::out);
	stringstream stext;
	for (auto it=r.header.begin(); it!=r.header.end(); it++) {

		stext << it->first << ":" << it->second <<endl;
	}

	fLog<<stext.str()<<endl;`

**Comment by t0trader** [comment]
@smarttang 
`
	fstream fLog("log.txt",ios::out);
	stringstream stext;
	for (auto it=r.header.begin(); it!=r.header.end(); it++) {

		stext << it->first << ":" << it->second <<endl;
	}

	fLog<<stext.str()<<endl;
`

**Comment by t0trader** [comment]
@smarttang 
```
	fstream fLog("log.txt",ios::out);
	stringstream stext;
	for (auto it=r.header.begin(); it!=r.header.end(); it++) {

		stext << it->first << ":" << it->second <<endl;
	}

	fLog<<stext.str()<<endl;
```

**Comment by smarttang** [comment]
@t0trader  thx...i try to print~haha~
