### ISSUE TITLE
No symbols are exported when building a DLL

### ISSUE THREAD

**Issue by r-darwish** [whoshuu/cpr#242]
I'm trying to pack CPR for [Conan](https://www.conan.io/), which means that I check that the library works also in Visual Studio as a static library and a shared library. When compiling a shared library it seems that the exported DLL has no symbols (see the attached image). I searched the code and could not find either `__declspec(dllexport)` not a `.def` files, as specified [here](https://msdn.microsoft.com/en-us/library/z4zxe9k8.aspx).

You can see [this example ](https://github.com/facebook/zstd/blob/bd88f633acda0de4f9eaef6b0914c3b569a34724/lib/zstd.h#L29-L32) for creating a DLL compatible header file.

![image](https://user-images.githubusercontent.com/1383193/33703272-1f3a8964-db30-11e7-8c4c-1ce41c506405.png)

**Comment by COM8** [comment]
Should be fixed. Feel free to open a new issue in case this is still a problem.
