### ISSUE TITLE
Conan package

### ISSUE THREAD

**Issue by ZaMaZaN4iK** [whoshuu/cpr#244]
Hello,
Do you know about [Conan](https://github.com/conan-io/conan)?
[Conan](http://docs.conan.io/en/latest/) is modern dependency manager for C++. And will be great if your library will be available via package manager for other developers.

[Here](https://github.com/bincrafters/conan-templates) you can find example, how you can create package for the library. 

If you have any questions, just ask :-)

**Comment by p-groarke** [comment]
+1

**Comment by dlazarus** [comment]
+1

**Comment by ForgottenUmbrella** [comment]
Someone's already made a [recipe](https://bintray.com/degoodmanwilson/opensource/cpr%3ADEGoodmanWilson)

**Comment by deblauwetom** [comment]
You can use this one I made: https://bintray.com/metalmajor/metalmajor/cpr%3Ametalmajor

**Comment by ZaMaZaN4iK** [comment]
Any update on the issue? Can you move your package to bincrafters?

**Comment by deblauwetom** [comment]
I don't have time or knowledge to do that. I already struggled a great deal to get where it is now, so I consider my packages more of a starting point for real conan-people to fix it.

**Comment by jgsogo** [comment]
Hi! I'm not sure if you are aware of the new service Conan has developed to create and curate recipes for 3rd party libraries. It is called `conan-center-index` (general availability soon) and it provides an easy way for the community to contribute with recipes and improve them. Under the hood, it runs more than a hundred jobs with different compilers, options and versions to generate quite a wide bunch of binaries, that can be consumed afterward by the Conan client.

With this service, a simple command like: `conan install cpr/1.3.0@` would be enough to install and consume this library.

Here you can find the PR if you want to follow the progress in this recipe: https://github.com/conan-io/conan-center-index/pull/450

**Comment by gocarlos** [comment]
Issue can be closed: https://conan.io/center/cpr/1.3.0/?user=_&channel=_

**Comment by jgsogo** [comment]
GitHub doesn't render properly the links ending with `_`, here it is the proper one: https://conan.io/center/cpr/1.3.0
