### ISSUE TITLE
SSL certificate problem: unable to get local issuer certificate

### ISSUE THREAD

**Issue by sujiths93** [whoshuu/cpr#246]
I am trying to access bit-coin data through GDAX and I get the above error when sending a HTTPS request, I am a beginner in network programming, not sure what to do.

**Comment by paulohefagundes** [comment]
try passing `cpr::VerfifySsl(false)`

**Comment by leecbaker** [comment]
Disabling SSL verification sounds like a security issue. Is there another way to fix this issue?

**Comment by interfector18** [comment]
Yes, look https://github.com/whoshuu/cpr/issues/261#issuecomment-377064004

**Comment by NoneTirex** [comment]
You need to install `libcurl4-openssl-dev` and then clean and rebuild project. This solution works for me.

**Comment by vladipus** [comment]
For me the problem was solved with multiple steps.
I had to set bothe client cert/key and the downloaded cacert.pem (`https://curl.haxx.se/ca/cacert.pem`).
    cpr::SslOptions sslOpts = cpr::Ssl(cpr::ssl::CertFile{"client.cer"},
                                       cpr::ssl::KeyFile{"client.key"},
                                       cpr::ssl::CaInfo{"cacert.pem"})

The key/cer files were actually created by the build scripts themselves in the bin directory.
