### ISSUE TITLE
Static Build: SegFault on run

### ISSUE THREAD

**Issue by ibroheem** [whoshuu/cpr#252]
I linked with the following flags:
` -lcpr -lcurl -lz  -lssl1 -lcrypto1 -ldl -pthread`

 on running I encountered Segmentation fault even with no cpr codes (i.e nothing to link).
This happens in both Debug and Relese Build

**Comment by COM8** [comment]
Is this still the case?
Are you running it on ARM?

**Comment by ibroheem** [comment]
No, it's no longer the case. At least on v1.5.0.
Thanks
