### ISSUE TITLE
https web pages cannot be retreived in the vcpkg x64 build

### ISSUE THREAD

**Issue by VioletGiraffe** [whoshuu/cpr#254]
I'm using the x64 build of CPR from vcpkg. The example from the README does not work, nor any other https requests I tried. `r.status_code` is zero. http links work fine.

Any pointers? I'm hoping it's a known issue and a solution already exists.

**Comment by COM8** [comment]
No, there is no know issue about this.
I'd say this is caused by an outdated version of `CPR` provided by `vcpkg`.

Feel free to reopen, in case this problem still exists.
