### ISSUE TITLE
No such file cpr.h

### ISSUE THREAD

**Issue by privateOmega** [whoshuu/cpr#258]
@whoshuu Yours seems to be the most simplest and straighforward library to implement API call from c++.

But I am stuck with the initial setup.
After completing steps to build CPR.
`mkdir build
cd build
cmake ..
cmake --build .`

Yet, on compiling the file ` g++ rest-client.cpp 
rest-client.cpp:1:21: fatal error: cpr/cpr.h: No such file or directory
compilation terminated.
`
I've also tried compiling with -std=c++11. 

Haven't had luck solving it. Also how do you compile a program? Are there any extra linking parameters??

**Comment by timofeyuk** [comment]
Hi @privateOmega,

You might want to install (copy) the include files and lib file to /usr/local/include/ and /usr/local/lib respectively - assuming you're on linux.  

GCC will not search for headers outside default include paths.

I'd also suggest using CMake just to make builds easier and put all compiler/linker flags in one place.
