### ISSUE TITLE
MSVC solution

### ISSUE THREAD

**Issue by Cylix** [whoshuu/cpr#259]
Hi,

We are currently working on a C++ library, [iota.lib.cpp](https://github.com/thibault-martinez/iota.lib.cpp) using your great library (thanks for the good work!) as a dependency.

One of our goals is to make the library very accessible to help the development of IOTA crypto-currency related projects based on C++ such that the IOTA ecosystem keeps growing up.

To do so, we also support windows environment and try to make it accessible for windows users that are not used to CMake buildchain. So we were looking into adding a MSVC solution to the repository as I already did for another of my libraries ([cpp_redis](https://github.com/cylix/cpp_redis)) or other big projects do ([google test](https://github.com/thibault-martinez/iota.lib.cpp)).

Unfortunately, MSVC solution configuration is pretty limited (definitely not as convenient as CMake) and we can't achieve that without our dependencies providing their own MSVC solution (then we can link your solution with ours).

Therefore, I have the following questions:
* Do you plan adding an MSVC solution in the future?
* If not, would you consider merging a PR adding such support? I would be able to do it, however, I can't guarantee I can maintain the solution file, so I could understand you would not be interested considering the additional maintenance cost.

Best

**Comment by Cylix** [comment]
Note to myself: this is related to https://github.com/thibault-martinez/iota.lib.cpp/issues/213

**Comment by iPherian** [comment]
I don't think the original maintainer is around, but you could:

- fork this repo
- add a git pre-commit hook to generate .sln, and stage it.
- If someone changes cmakelists.txt, any changes will also be reflected in the .sln and committed

Not sure about all the details.

_**Caveat:**_
afaik, the resulting .sln will require users to have cmake installed. However they don't need to know cmake syntax.

**Comment by Cylix** [comment]
Thanks for the suggestion @iPherian.
I'm not a big fan of maintaining a fork as a dependency rather than the original dependency itself, but I guess a merge regularly should have the same effect as changing the sub module refs.
Will definitely look into it :)

**Comment by COM8** [comment]
CMake is able to generate a .sln project for you run Cmake with `"Visual Studio 16 2019"` as it's generator. Does this solve your problem?

**Comment by COM8** [comment]
Feel free to reopen, in case this problem still exists.
