### ISSUE TITLE
MSVC support

### ISSUE THREAD

**Issue by whoshuu** [whoshuu/cpr#26]

**Comment by smiley** [comment]
What version are you targeting? It's nearly-flawless (save for some warnings on CRT functions) on MSVC14.

**Comment by nshcat** [comment]
Same here, works fine with the current version of MSVC. Only thing that has to be done is to disable deprecation warnings using  __/sdl-__ compiler switch.

**Comment by smiley** [comment]
The tests, however, aren't compiling due to a problem with `Response` objects and `std::tuple` in use in `std::bind`. (See #38)

**Comment by whoshuu** [comment]
Hey @smiley, thanks for the information you posted about the builds. I'm going to go ahead and write out separate issues for each error and link them here. Once we get those sorted out, this can get closed.

@nshcat, that's awesome that you got it to work on the latest MSVC! Have you actually linked it to an executable and made requests using it? The library building is different from the library working, just want to know how far you were able to take things.

**Comment by smiley** [comment]
Whoops, looks like my commit message in 1a04ac7 triggered a future close on this issue, once my PR (#38) is accepted. Any way to turn that off on your end?

**Comment by whoshuu** [comment]
@smiley, no worries, I'll fix it up before merging it in.

**Comment by whoshuu** [comment]
#40 and #41 are all sorted out so this is good to go.
