### ISSUE TITLE
Debugging feature

### ISSUE THREAD

**Issue by Criscal** [whoshuu/cpr#260]
Hi,

would it be possible to add debugging output to cpr? For example Session could have a SetOption(Debugging&...) option, which would implicitly set CURLOPT_VERBOSE and CURLOPT_STDERR on the curl handler. At the moment I wouldn't know how to log these and I don't want to get wireshark out for getting flooded in data.

Thanks!

**Comment by COM8** [comment]
You can pass the `Verbose` option when creating a request to enable `CURLOPT_VERBOSE`.

**Comment by sierret** [comment]
Could you give a short example on how to perform?

Session.setOption doesn't seem to work.
