### ISSUE TITLE
ERROR IN CALLING MICROSOFT VISION API

### ISSUE THREAD

**Issue by abhisaini** [whoshuu/cpr#261]
Hii ,
I want to call Microsoft Vision API from c++ and for that i run the following code

```
#include <iostream>

#include <cpr/cpr.h>
#include <json.hpp>


int main(int argc, char** argv) {
    auto response = cpr::Post(cpr::Url{"https://westcentralus.api.cognitive.microsoft.com/vision/v1.0/analyze"},
    		cpr::Body{{"url","https://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Broadway_and_Times_Square_by_night.jpg/450px-Broadway_and_Times_Square_by_night.jpg"}},
            cpr::Header{{"Ocp-Apim-Subscription-Key", "15302439fd7c432b8249b3e54231d67d"}}
    );
    std :: cout << response.status_code ;
    auto json = nlohmann::json::parse(response.text);
    std::cout << json.dump(4) << std::endl;
}
```

The make was successful but when I tried to run the executable I got following error
```
terminate called after throwing an instance of 'std::length_error'
  what():  basic_string::_M_create
Aborted (core dumped)

```
PS : the documentation for Microsoft Vision API can be found [here](https://docs.microsoft.com/en-in/azure/cognitive-services/computer-vision/quickstarts/python)
So , tell me if I am doing some mistake

**Comment by WesThorburn** [comment]
This library currently doesn't work with HTTPS requests. They will always return a response.status_code 0 and an empty string.

Your request's response text is coming back as an empty string, it's passing it to nlohmann::json::parse() which doesn't verify that the length of its string parameter is greater than 1. Trying to access an non-existent position in the string causes the program to crash.

**Comment by Liastre** [comment]
Hey, https is working with OpenSSL included to Curl

**Comment by iPherian** [comment]
I'd like to confirm that cpr works just fine with https if libcurl underneath works with it.

@abhisaini please tell us what `response.error.message` is.

Just a shot in the dark, but my problem getting https on windows was the lack of a peer certificates file. Try downloading `https://curl.haxx.se/ca/cacert.pem` into `C:\etc\ssl\cert.pem` and cleanly rebuilding.  (make sure you change the filename to `cert.pem`)

This assumes you're building with `-DCMAKE_USE_OPENSSL=ON`

**Comment by ZaMaZaN4iK** [comment]
Is theere any option to provide certificate bundle to the curl, which is used under the hood? I cannot understand, how to make https requests, if curl is compiled without bundled certificates.

**Comment by COM8** [comment]
`CPR` work quite fine for https requests if you build with `openSSL` enabled.
The only problem currently is the lag of `cacert` discovery.
Curl searches for the `cacert` in predefined locations, which can be altered by the `CURLOPT_CAINFO` option.
I don't think there is an option to change this in `CPR` right now.

I'm currently working on proper https support, based on all those PRs.

**Some useful links:**
* https://curl.haxx.se/libcurl/c/CURLOPT_CAINFO.html
* https://curl.haxx.se/docs/sslcerts.html
* https://curl.haxx.se/docs/caextract.html

**Comment by COM8** [comment]
#276 fixed this.
