### ISSUE TITLE
Hi! i am new to C++,just want to know does cpr support twitter web api call?

### ISSUE THREAD

**Issue by caoisgod** [whoshuu/cpr#262]

**Comment by Liastre** [comment]
Hey, of course It supports any kind of http/https requests including REST based as Twitter one, cheer

**Comment by part1zano** [comment]
Doesn't have a separate twitter API or something, though. You just make HTTP(S) requests, that's it.

**Comment by whoshuu** [comment]
To echo what's been said here, the Twitter API is based on plain HTTP and HTTPS. For more information, visit their developer portal: https://developer.twitter.com/en/docs.html.
