### ISSUE TITLE
How to  skip the verification of the server's certificate

### ISSUE THREAD

**Issue by gmatesunny** [whoshuu/cpr#264]
How I could disable the certificate verification which is equivalent to -k option of curl cmd line. I wanted a REST client which does not perform server certificate verification.

```
int main(int argc, char** argv) {
    const string data = "This is the POST body";

    VerifySsl disable_verify = VerifySsl(false);
    auto response = cpr::Get(
        cpr::Url{"https://localhost:4433/"}
        );
    cout << response.text << endl;
}


```
Basically I wanted to set curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L); 
I tried this, it compiles but still does server certificate verification I think. Someone please help.

**Comment by gmatesunny** [comment]
Is it even possible to set that option in cpr?

**Comment by whoshuu** [comment]
@gmatesunny, yes there are two ways to accomplish what you want:

1. Using it directly in an API call:

```c++
auto response = cpr::Get(cpr::Url{"https://localhost:4433/"}, cpr::VerifySsl{false});
```

2. Embedding the option in a longer-lived `Session`:

```c++
cpr::Session session;
session.SetUrl(cpr::Url{"https://localhost:4433/"});
session.SetVerifySsl(cpr::VerifySsl{false});
auto response = session.Get();
```

The only difference is that the former will not persist the option to future API calls, whereas the latter will continue to skip SSL verification for any calls made using the `session` object.
