### ISSUE TITLE
CodeBlocks compile time error in api.h line no 39

### ISSUE THREAD

**Issue by susonwaiba** [whoshuu/cpr#268]
Error says:
undefined reference to cpr::Session::Session()
undefined reference to cpr::Session::Get()
and so on.. seems like session got problem ??

#include < iostream>
#include <cpr/cpr.h>

int main(int argc, char** argv) {
    auto r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"});
    std::cout << r.text;
    return 0;
}

I have copypast include/cpr to MinGW/include/cpr
And I have download curl-7.59.0.tar.gz and copypast curl-7.59.0\include\curl to MinGW/include/curl

Can someone solve this thing.?

**Comment by susonwaiba** [comment]
@iPherian i am using windows so, compile doesn't work. so, I added include/cpr folder directly to MinGW/include/cpr compiler include folder. Doing samething to Json lib is working. I am new to cpp. Is it wrong way to do it.?

**Comment by iPherian** [comment]
@susonwaiba 

> I am new to cpp

If you're new to c++, there's a lot of information. But I'll try to get you started.

> Is it wrong way to do it.?

It's fine. Some libraries require additional steps.

> Doing samething to Json lib is working.

Assuming you're referring to the excellent [nlohmann/json](https://github.com/nlohmann/json) library, yes, it merely requires the include files, as you have done.

--------------

You'll need to compile cpr. It will work on windows.

- Right click on code blocks project -> add files recursively -> select <repo_root>/cpr
- this is the folder which contains 'session.cpp' as well as others
- now it should compile but will complain of `undefined reference to curl_easy_setopt` and similar.
- this means you will need to link to libcurl
- you'll have to find libcurl for gcc 5.1 compiler (aka mingw) which I think codeblocks comes with. Instructions for adding libraries to a code blocks project can be found on google.

Sorry this isn't complete.

**Comment by smailzhu** [comment]
Thanks for @iPherian reply
> You'll need to compile cpr. It will work on windows.
> 
>     * Right click on code blocks project -> add files recursively -> select <repo_root>/cpr
> 
>     * this is the folder which contains 'session.cpp' as well as others
> 
>     * now it should compile but will complain of `undefined reference to curl_easy_setopt` and similar.

* download curl from [website](https://curl.haxx.se/download.html) ([Windows](https://curl.haxx.se/windows/))

* Right click on code blocks project -> Build options.. -> Search directories tab -> Add -> Select <curl_root>/include -> OK

* System error dialog said "libcurl.dll" missing. I copy from <curl_root>/bin/libcrul.dll to where the compiled exe file locates dir

It's work for me on Win7(x86)

If you cannot find code blocks project, you can find it on view -> Manager

**Comment by goncaloperes** [comment]
If you are using a development environment, for example Dev-C++, don't forget to access Compiler Options>Directories>C++Includes and add the directory path of the "include" folder.
