### ISSUE TITLE
I don't understand why I can't use it

### ISSUE THREAD

**Issue by wl496928838** [whoshuu/cpr#269]
错误	1	error C2610: “cpr::Body::Body(cpr::Body &&)”: 不是可默认为的特殊成员函数
错误	2	error C2610: “cpr::Body &cpr::Body::operator =(cpr::Body &&)”: 不是可默认为的特殊成员函数

vs2013 

```
#include <cpr/cpr.h>
int main(int argc, char** argv) {
	auto r = cpr::Get(cpr::Url{ "https://api.github.com/repos/whoshuu/cpr/contributors" },
		cpr::Authentication{ "user", "pass" },
		cpr::Parameters{ { "anon", "true" }, { "key", "value" } });
	r.status_code;                  // 200
	r.header["content-type"];       // application/json; charset=utf-8
	r.text;                         // JSON text string
}
```

**Comment by wl496928838** [comment]
vs2017

cpr-example

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "public: __thiscall cpr::Session::~Session(void)" (??1Session@cpr@@QAE@XZ)，该符号在函数 "class cpr::Response __cdecl cpr::Get<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&)" (??$Get@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@cpr@@YA?AVResponse@0@$$QAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用	example	G:\c\cpr-example\build\example.obj	1	

严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "public: void __thiscall cpr::Session::SetOption(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SetOption@Session@cpr@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)，该符号在函数 "void __cdecl cpr::priv::set_option<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(class cpr::Session &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&)" (??$set_option@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@priv@cpr@@YAXAAVSession@1@$$QAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用	example	G:\c\cpr-example\build\example.obj	1	
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK2019	无法解析的外部符号 "public: class cpr::Response __thiscall cpr::Session::Get(void)" (?Get@Session@cpr@@QAE?AVResponse@2@XZ)，该符号在函数 "class cpr::Response __cdecl cpr::Get<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&)" (??$Get@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@cpr@@YA?AVResponse@0@$$QAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) 中被引用	example	G:\c\cpr-example\build\example.obj	1	


My level is low.

Many times have failed to succeed.

Hope to help me

**Comment by iPherian** [comment]
It looks like missing symbol errors. Assuming you're not using cmake, try adding the *.cpp files to your vs project.

**Comment by TravisB91** [comment]
I'm new to the whole cmake use on this. I'm trying to figure out how to use it in VS2015 for a project I'm trying to do for work on this. Anyone able to point me into a good direction on what exactly I need to do to get this up and running? I'm normally used to just linking the dlls and the include paths through VS project properties so the rest of this is a bit over my head.

**Comment by COM8** [comment]
Feel free to reopen, in case this problem still exists.
