### ISSUE TITLE
CMake on macOS with GCC

### ISSUE THREAD

**Issue by mhfrantz** [whoshuu/cpr#272]
I'm having trouble building with CMake on macOS and GCC 7. (I believe this would happen with any version of GCC on macOS.)
```
mkdir build
cd build
cmake -DCMAKE_C_COMPILER=gcc-7 -DCMAKE_CXX_COMPILER=g++-7
make
```
What eventually happens are errors like this:
```
g++-7: error: unrecognized command line option '-stdlib=libc++'
```
I believe the problematic CMake configuration is this (around line 19 of `CMakeLists.txt`):
```
    if(COMPILER_SUPPORTS_CXX11)
        message(STATUS "C++11 is supported.")
        if(${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 -stdlib=libc++")
        else()
            set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
        endif()
```
Using `CMAKE_SYSTEM_NAME` this way assumes that a `Darwin` system will support the `-stdlib` option, but that is a Clang option and is not recognized by GCC.

It turns out there is a second bug in how the CMake version is being checked. Here is that code: 
```
if(NOT ${CMAKE_VERSION} LESS 3.2)
    set(CMAKE_CXX_STANDARD 11)
    set(CMAKE_CXX_STANDARD_REQUIRED ON)
```
Since I have 3.11.0, at first I thought that I should take that branch. However, the `LESS` operator is not doing a semantic version comparison, so since `3.11.0` is lexicographically less than `3.2`, I end up skipping that section and drop into the problematic section above.

If you use `VERSION_LESS` instead of `LESS`, this should have the correct behavior. I can put up a PR for that change, though I am unsure how to tackle the other issue.

**Comment by iPherian** [comment]
I have the problem related to `LESS` vs `VERSION_LESS` as well.
