### ISSUE TITLE
Adding and linking missing files

### ISSUE THREAD

**Issue by qasimraheem** [whoshuu/cpr#274]
**i like this cpr library, but i got some issues:**
i clone this **cpr** repo, when i compile there were some other files were **missing** (**_CURL, googletest and mongoose_**), i also clone  them and paste them in **cpr/opt**. then i compile with **Clang cmake** there were some errors :
- CMake Error at test/CMakeLists.txt:24 (add_custom_command): Error evaluating generator expression:
    $<TARGET_FILE_DIR:libcurl>
    No target "libcurl" Call Stack (most recent call first): test/CMakeLists.txt:42 (add_cpr_test)

- CMake Error at test/CMakeLists.txt:24 (add_custom_command): Error evaluating generator expression:
    $<TARGET_FILE_DIR:libcurl>
    No target "libcurl" Call Stack (most recent call first): test/CMakeLists.txt:41 (add_cpr_test)

**can you check it here -> https://github.com/qasimraheem/CPR_Cpp **

i also try it in Cmake but there were also some files were missing,
![screenshot_2](https://user-images.githubusercontent.com/35058402/41115741-d6899ff0-6aa1-11e8-90f6-a5acd698771c.png)

**Comment by wuno** [comment]
I had this same issue and this fixed it, 

`git submodule update --init --recursive`

**Comment by whoshuu** [comment]
@qasimraheem did @wuno's suggestion fix your issue?
