### ISSUE TITLE
Can we use it on windows system ?

### ISSUE THREAD

**Issue by saurabhjangir** [whoshuu/cpr#275]

**Comment by sum01** [comment]
I see no reason why it wouldn't work on Windows, you just need libcurl. If you don't have it then it [will build from the submodule.](https://github.com/whoshuu/cpr/blob/3d14e61ed247a90a07db26fb107beb3086a035d6/opt/CMakeLists.txt#L41-L61)

[Here](https://curl.haxx.se/download.html) you can seen there's libcurl versions for basically every OS, including Windows.

**Comment by whoshuu** [comment]
I think this question is effectively answered by @sum01. Ultimately it comes down to running CMake on Windows to produce Visual Studio Solution artifacts, and then relying on Windows tools to do the building from there.
