### ISSUE TITLE
Is it possible to request Unix Socket with cpr ?

### ISSUE THREAD

**Issue by edmBernard** [whoshuu/cpr#279]
I wonder if we can request unix socket with cpr library ?
Thanks

**Comment by edmBernard** [comment]
I add unix socket parameters in cpr https://github.com/whoshuu/cpr/pull/282

**Comment by COM8** [comment]
Nice. Thanks for your help!

**Comment by COM8** [comment]
Related issue:
https://github.com/whoshuu/cpr/issues/344
