### ISSUE TITLE
`install` target when built without `curl` or tests

### ISSUE THREAD

**Issue by part1zano** [whoshuu/cpr#280]
Long story short, I'm creating a FreeBSD port for `cpr`. It doesn't want to install without defining an install target in the `Makefile`. Please add one.

Thank you very much in advance.

**Comment by part1zano** [comment]
Gotta provide the patch and maybe file a pull request for it.

**Comment by whoshuu** [comment]
There's a bunch of PR's that do this right now, most recently this one: https://github.com/whoshuu/cpr/pull/277

I haven't had time to review and test them. Since demand for this seems pretty high I'll see if I can find the time to do that within the week.

**Comment by part1zano** [comment]
This resolves the issue, thank you @whoshuu
