### ISSUE TITLE
cmake config

### ISSUE THREAD

**Issue by part1zano** [whoshuu/cpr#281]
I'm still creating a FreeBSD port, and it would be great to have a cmake config for cpr in order to do stuff like `find_package(cpr)`.

Thank you very much in advance.

**Comment by edmBernard** [comment]
I don't know if it's what you want ?
I found these 2 : 
https://github.com/whoshuu/cpr/blob/master/cpr-config.cmake
https://github.com/Microsoft/vcpkg/pull/3185/files#diff-c3504c47965a68cfb1adf265ce8babfe

**Comment by part1zano** [comment]
Yup, looks like what I want.

**Comment by part1zano** [comment]
Doesn't seem to build with that config. Am I missing something? This is what cmake says:
```% cmake ..
-- The C compiler identification is Clang 6.0.0
-- The CXX compiler identification is Clang 6.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Could NOT find CPR (missing: CPR_INCLUDE_DIR) 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/che/git/qfr/api/build
```

**Comment by part1zano** [comment]
Ok, I modified the cmake config a bit according to the patch you provided, still no luck yet. Now it requires `curl` to be a dependency (what, though valid), and when found, gives 405 on a `POST` request.

**Comment by part1zano** [comment]
The exact same program, however, compiles and runs flawlessly when I'm using the provided receipt (the one in `README.md`)

**Comment by edmBernard** [comment]
Are you sure `cpr-config.cmake` found `cpr.h` https://github.com/whoshuu/cpr/blob/master/cpr-config.cmake#L13
It seem you need to add cpr include in your path.
For the second config file, you're right it was design to work with vcpkg and use external curl instead of the submodule.
At this time, I use these two methods to include CPR in a project:
- add CPR as submodule and add these lines in your CMakeLists: 
  - `add_subdirectory("third-party/cpr")`
  - `target_link_libraries(main ${CPR_LIBRARIES})`
  - `include_directories(${CPR_INCLUDE_DIRS})`
- use vcpkg to install cpr and add these lines in your CMakeLists
  - `find_path(CPR_INCLUDE_DIR cpr.h)`
  - `find_library(CPR_LIBRARY cpr)`
  - `target_link_libraries(main ${CPR_LIBRARIES})`
  - `include_directories(${CPR_INCLUDE_DIRS})`

It seem there is an issue with cpr installation see [arthur-tacca's comment](https://github.com/Microsoft/vcpkg/issues/3875#issuecomment-404893404)

**Comment by part1zano** [comment]
Thank you very much for your kind comments. The point is, when I add cpr as a submodule and use `add_subdirectory`, everything works flawlessly, but as soon as I try using the "system-wide" installation I made, it only makes a `GET` request properly. I also use system `curl` in both cases.

**Comment by part1zano** [comment]
Moreover, the one I built manually (`lib/libcpr.a`) has a different checksum from the one installed system-wide (`/usr/local/lib/libcpr.a`):
```
[15:09:15] 0 [che@xeon ~/git/cpr/build]% sha256 lib/libcpr.a
SHA256 (lib/libcpr.a) = 88682e890a56e071c6aa2b45009f6cbd1f2d6c37704e60c5792783baae470deb
[15:09:19] 0 [che@xeon ~/git/cpr/build]% sha256 /usr/local/lib/libcpr.a
SHA256 (/usr/local/lib/libcpr.a) = 68d86a88b7781e98e1739a36b2a0590405d78ab672f9c56004674eeb33aa591a
[15:09:22] 0 [che@xeon ~/git/cpr/build]% file lib/libcpr.a
lib/libcpr.a: current ar archive
[15:09:32] 0 [che@xeon ~/git/cpr/build]% file /usr/local/lib/libcpr.a
/usr/local/lib/libcpr.a: current ar archive
[15:09:42] 0 [che@xeon ~/git/cpr/build]% ls -l /usr/local/lib/libcpr.a
-rw-r--r--  1 root  wheel  195442 17 июля  04:04 /usr/local/lib/libcpr.a
[15:10:03] 0 [che@xeon ~/git/cpr/build]% ls -l lib/libcpr.a
-rw-r--r--  1 che  che  416560 17 июля  15:09 lib/libcpr.a```

**Comment by edmBernard** [comment]
I don't think checksum will mean usefull information. If there is a small difference (version, options, etc ...) it will mismatch.
what is your error when you try `POST` request ?

**Comment by part1zano** [comment]
Ah, I see what my problem with checksum may be! I'm using a tag in the port while using the latest `master` commit in the manual build. So the checksum may differ.

My error is 405.

**Comment by part1zano** [comment]
It is. Again: when I compile using cpr as a submodule, the exact same request goes flawlessly fine.

**Comment by part1zano** [comment]
I mean, does `http://httpbin.org/post` accept `POST`? Does it? It does, doesn't it?

**Comment by part1zano** [comment]
This program:
```
#include <cpr/cpr.h>
#include <iostream>

using std::cout;
using std::endl;

int main(int argc, char** argv) {
        // auto r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"},
        //                   cpr::Authentication{"part1zano", "Aighath7"},
        //                   cpr::Parameters{{"anon", "true"}, {"key", "value"}});
        auto r = cpr::Post(cpr::Url("http://httpbin.org/post"), cpr::Parameters{{"you", "suck"}, {"fuck", "you"}});
        cout << r.status_code << endl;                  // 200
        cout << r.header["content-type"] << endl;       // application/json; charset=utf-8
        cout << r.text << endl;                         // JSON text string
}```

returns this:
```% ./cpr-test
405
text/html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>405 Method Not Allowed</title>
<h1>Method Not Allowed</h1>
<p>The method is not allowed for the requested URL.</p>```

**Comment by edmBernard** [comment]
if you post the request with curl command line ? 
`curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://httpbin.org/post` 
does it works ?

**Comment by part1zano** [comment]
It does:
```
% curl -d '{"key1":"value1", "key2":"value2"}' -H "Content-Type: application/json" -X POST http://httpbi
n.org/post
{"args":{},"data":"{\"key1\":\"value1\", \"key2\":\"value2\"}","files":{},"form":{},"headers":{"Accept":"*/*","Connection":"close","Content-Length":"34","Content-Type":"application/json","Host":"httpbin.org","User-Agent":"curl/7.60.0"},"json":{"key1":"value1","key2":"value2"},"origin":"37.252.124.82","url":"http://httpbin.org/post"}
```

**Comment by edmBernard** [comment]
As I think it's more an issue with curl than cpr can you try with libcurl directly. 
Here a example to post request with libcurl: https://curl.haxx.se/libcurl/c/post-callback.html
you can copy/past this example and change url.

**Comment by part1zano** [comment]
It's more of an issue with the cmake config. Again: I use system curl in both cases. In one case, everything works while in the remaining one I get a 405.

**Comment by part1zano** [comment]
I took the example you mentioned, and here's what it returned:
```
% ./libcurl-post
*   Trying 52.22.127.224...
* TCP_NODELAY set
* Connected to httpbin.org (52.22.127.224) port 80 (#0)
> POST /post HTTP/1.1
Host: httpbin.org
Accept: */*
Content-Length: 424
Content-Type: application/x-www-form-urlencoded

* We are completely uploaded and fine
< HTTP/1.1 200 OK
< Connection: keep-alive
< Server: gunicorn/19.8.1
< Date: Wed, 18 Jul 2018 11:47:05 GMT
< Content-Type: application/json
< Content-Length: 684
< Access-Control-Allow-Origin: *
< Access-Control-Allow-Credentials: true
< Via: 1.1 vegur
<
{"args":{},"data":"","files":{},"form":{"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed vel urna neque. Ut quis leo metus. Quisque eleifend, ex at laoreet rhoncus, odio ipsum semper metus, at tempus ante urna in mauris. Suspendisse ornare tempor venenatis. Ut dui neque, pellentesque a varius eget, mattis vitae ligula. Fusce ut pharetra est. Ut ullamcorper mi ac sollicitudin semper. Praesent sit amet tellus varius, posuere nulla non, rhoncus ipsum.":""},"headers":{"Accept":"*/*","Connection":"close","Content-Length":"424","Content-Type":"application/x-www-form-urlencoded","Host":"httpbin.org"},"json":null,"origin":"37.252.124.82","url":"http://httpbin.org/post"}
* Connection #0 to host httpbin.org left intact
```
As you can observe, this is NOT a problem with curl.

**Comment by edmBernard** [comment]
it's strange because cpr is a really thin layer on top of libcurl. If it work with libcurl it has to work with cpr.

**Comment by part1zano** [comment]
Sorry, are you even listening? What I'm talking about is a problem with cmake configs. How on earth can it be a problem with cpr itself?

**Comment by iPherian** [comment]
@part1zano Are you sure both the working and non-working examples are loading the same curl dll? Try using [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to check.

**Comment by iPherian** [comment]
Are you sure both the working and non working examples are using the same curl .so? Try running them under ltrace (or possible strace) to see.

**Comment by edmBernard** [comment]
you can also use `ldd` to check which *.so is used by your executable

**Comment by part1zano** [comment]
And as far as FreeBSD's package manager says, it's been installed by the `curl` package:
```% pkg which /usr/local/lib/libcurl.so.4.5.0
/usr/local/lib/libcurl.so.4.5.0 was installed by package curl-7.60.0
```

**Comment by part1zano** [comment]
Just in case someone notices it's `.4` and not `.4.5.0`:
```
% ls -l /usr/local/lib/libcurl.so.4
lrwxr-xr-x  1 root  wheel  16 26 июня  04:13 /usr/local/lib/libcurl.so.4 -> libcurl.so.4.5.0
```

**Comment by part1zano** [comment]
It was actually a problem with cpr. See, in `Session::Post` they somehow used `CURLOPT_HTTPGET` instead of `CURLOPT_HTTPPOST`, so it was `GET` instead of `POST` with applicable consequences. Made a patch in the port itself, gotta prepare a proper cmake config and submit!

**Comment by part1zano** [comment]
In case anyone wonders, here's my patch to the config for cmake:
```
--- cpr-config.cmake.orig       2018-07-18 20:06:59 UTC
+++ cpr-config.cmake
@@ -11,11 +11,15 @@
 #                     file that uses this interface
 
 find_path(CPR_INCLUDE_DIR
-          NAMES cpr.h)
+          NAMES cpr/cpr.h
+                 PATHS
+                 /usr/local/include)
 
 find_library(CPR_LIBRARY
-             NAMES cpr
-             HINTS ${CPR_LIBRARY_ROOT})
+                        NAMES cpr
+                        PATHS
+                        /usr/local/lib
+                        )
 
 include(FindPackageHandleStandardArgs)
 find_package_handle_standard_args(CPR REQUIRED_VARS CPR_LIBRARY CPR_INCLUDE_DIR)
```
Please note: you might want to add your own paths to includes and libs (like `/usr/lib` or `/usr/include`). I'm not interested in that, sorry not sorry.
