### ISSUE TITLE
Multiple headers with same name

### ISSUE THREAD

**Issue by 01e9** [whoshuu/cpr#288]
I was about to use this library but I see it doesn't support multiple headers with same name

https://github.com/whoshuu/cpr/blob/3d14e61ed247a90a07db26fb107beb3086a035d6/include/cpr/cprtypes.h#L13

I had a similar issue with another http client https://github.com/jgaa/restc-cpp/issues/37

https://stackoverflow.com/q/3241326/8766845

**Comment by COM8** [comment]
Hmmm...
I don't think this is a too important use case.
Would you like to create a PR for this?

**Comment by 01e9** [comment]
Nope, I don't need it anymore (two jobs changed since then)

**Comment by COM8** [comment]
Ok. Closing it then.
