### ISSUE TITLE
problem with Digest Authentication

### ISSUE THREAD

**Issue by InvisibleLeVen** [whoshuu/cpr#291]
![image](https://user-images.githubusercontent.com/24772156/45474563-ace77100-b76c-11e8-9f0e-8b69f8c7e440.png)
This is the requested code. However, in the request received by the server, there is no authorization field in the headers.

**Comment by InvisibleLeVen** [comment]
![image](https://user-images.githubusercontent.com/24772156/45474746-23846e80-b76d-11e8-96a7-4937079e4bb2.png)

**Comment by COM8** [comment]
Is this still an issue?
