### ISSUE TITLE
How to build .sln for VS 2017? CMake gives errors.

### ISSUE THREAD

**Issue by KardoseR** [whoshuu/cpr#294]
Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.17134.
The CXX compiler identification is MSVC 19.13.26131.1
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x86/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x86/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Checking compiler flags for C++11 support.
C++11 is supported.
C++ Requests CMake Options
=======================================================
  USE_SYSTEM_CURL: OFF
  BUILD_CPR_TESTS: ON
  GENERATE_COVERAGE: OFF
  CPR_CURL_NOSIGNAL: OFF
  USE_SYSTEM_GTEST: OFF
  CMAKE_USE_OPENSSL: ON
=======================================================
Not using system Curl, using built-in curl project instead.
CMake Error at opt/CMakeLists.txt:48 (add_subdirectory):
  The source directory

    C:/Users/kardo/Desktop/cpr/opt/curl

  does not contain a CMakeLists.txt file.

CMake Error at opt/CMakeLists.txt:57 (set_property):
  set_property could not find TARGET curl.  Perhaps it has not yet been
  created.

CMake Error at opt/CMakeLists.txt:60 (set_property):
  set_property could not find TARGET libcurl.  Perhaps it has not yet been
  created.

Set CURL_FOUND to TRUE.
Set CURL_LIBRARIES to libcurl.
Set CURL_INCLUDE_DIRS to /include;/include/curl.
Not using system gtest, using built-in googletest project instead.
CMake Error at opt/CMakeLists.txt:82 (add_subdirectory):
  The source directory

    C:/Users/kardo/Desktop/cpr/opt/googletest

  does not contain a CMakeLists.txt file.

CMake Error at opt/CMakeLists.txt:90 (set_property):
  set_property could not find TARGET gtest.  Perhaps it has not yet been
  created.

CMake Error at opt/CMakeLists.txt:91 (set_property):
  set_property could not find TARGET gtest_main.  Perhaps it has not yet been
  created.

Set GTEST_FOUND to TRUE.
Set GTEST_LIBRARIES to gtest.
Set GTEST_MAIN_LIBRARIES to gtest_main.
Set GTEST_BOTH_LIBRARIES to gtest;gtest_main.
Set GTEST_INCLUDE_DIRS to /include.
Building mongoose project for test support.
CMake Error at opt/CMakeLists.txt:106 (add_subdirectory):
  The source directory

    C:/Users/kardo/Desktop/cpr/opt/mongoose

  does not contain a CMakeLists.txt file.

Set MONGOOSE_FOUND to TRUE.
Set MONGOOSE_LIBRARIES to mongoose.
Set MONGOOSE_INCLUDE_DIRS to .
CMake Error at opt/CMakeLists.txt:116 (set_property):
  set_property could not find TARGET mongoose.  Perhaps it has not yet been
  created.

Using CURL_INCLUDE_DIRS: /include;/include/curl.
Using CURL_LIBRARIES: libcurl.
Configuring incomplete, errors occurred!
See also "C:/Users/kardo/Desktop/cpr/BUILD_/CMakeFiles/CMakeOutput.log".

**Comment by KardoseR** [comment]
Ok so that was solved by git clone curl, mongoose and that other package

but visual studio build fails when building the ALL_BUILD project.

**Comment by KardoseR** [comment]
Couple 1104 LNK errors.

**Comment by COM8** [comment]
Were you able to solve this issue?
If yes, please tell us here, since there is no official MSVC support.
