### ISSUE TITLE
How do you install?

### ISSUE THREAD

**Issue by muffinrecon** [whoshuu/cpr#295]
I don't have git and I don't use cmake for my project. How do I move get cpr into usr/includes folder?

I tried building the sample project. it only managed to install curl libraries, but when I went to make install, it said there was no command.

**Comment by chuxi** [comment]
also have the same problem.

**Comment by CODER591** [comment]
> Now I use it in ExternalPorject_Add and use copy instead of INSTALL_COMMAND

How you use this? I mean where should I input the INSTALL_COMMAND ?
Can You provide a tutorial how to build it:
For example:as usual console application?

**Comment by muffinrecon** [comment]
I went ahead and used libcurl instead. The documentation is easy to understand compared to other libraries.
