### ISSUE TITLE
Issue with release 1.3.0 POST request method not set

### ISSUE THREAD

**Issue by kwach** [whoshuu/cpr#304]
I found an error in `Response Session::Impl::Post() `
It causes the request to be send with method of the last used request. If it was PUT, then your POST will be PUT rather than what you'd think so.

Latest release 1.3.0 has:
```
Response Session::Impl::Post() {
    auto curl = curl_->handle;
    if (curl) {
        curl_easy_setopt(curl, CURLOPT_HTTPGET, 0L);
        curl_easy_setopt(curl, CURLOPT_NOBODY, 0L);
    }

    return makeRequest(curl);
}```

while on master it's fixed with the following

```

Response Session::Impl::Post() {
    auto curl = curl_->handle;
    if (curl) {
        curl_easy_setopt(curl, CURLOPT_NOBODY, 0L);
        curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "POST");
    }

    return makeRequest(curl);
}
```

Proposed fix: create a new official realease.

**Comment by leomachado73** [comment]
Same problem here.

I managed to fix the problem by adding this:

curl_easy_setopt(curl, CURLOPT_CUSTOMREQUEST, "POST");

and removing this:
curl_easy_setopt(curl, CURLOPT_HTTPGET, 0L);

on **Response Session::Impl::Post()**

Until now everything is working fine.

**Comment by COM8** [comment]
A new release will be created by the end of next week.
https://github.com/whoshuu/cpr/issues/362#issuecomment-614168836
