### ISSUE TITLE
General Questions

### ISSUE THREAD

**Issue by kennykaiyinyu** [whoshuu/cpr#305]
Hi
I'm interested in using this library for it's elegant and stylish implementation. But there are two aspects that I want to ask: (1) is this project still live? :) seeing it's not been updating for some months. Also  (2) does it currently support SSL? I read it's yet to support Open SSL. Does it mean it doesn't support SSL in general yet?

Thanks!

**Comment by yasser-sobhy** [comment]
@whoshuu if possible, please add maintainers to help merge pull requests or add new features. I will be to support.

**Comment by kennykaiyinyu** [comment]
I actually switch back to libcurl... I see it’s actually not working as expected if the paraneter combination is a bit complicated (you can’t do the authentication the way you want)

The library looks fancy at first, but behind the interface it imposes too much restrictions...

**Comment by pengweichu** [comment]
> @whoshuu if possible, please add maintainers to help merge pull requests or add new features. I will be to support.

Totally agree.

**Comment by COM8** [comment]
Related to: #362
