### ISSUE TITLE
bugs when post with form-data

### ISSUE THREAD

**Issue by ouhaiyun0** [whoshuu/cpr#306]
hi, I got some issues when use Multipart to post data.

When a field in the Multipart is too long, it will cause the content to be messy.

Just like my test code:

```c++
#include <cpr/cpr.h>
#include <string>
#include <sstream>
#include <iostream>
#include <fstream>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <algorithm>

using namespace cpr;
using namespace std;

int main()
{
    string sLongData;
    for (int i = 0; i < 1024; i++)
    {
        stringstream ss;
        ss << "start" << "\n";
        ss << "add_seq-" << i << ";" << "\n";
        ss << "end" << "\n";
        sLongData.append(ss.str());
    }
    auto multipart = cpr::Multipart{{"1", "field1"},
                                    {"2", "field2"},
                                    {"LongData", sLongData},
                                    {"3", "field3"},
                                    {"4", "field4"},
                                    {"5", "field5"},
                                    {"6", "field6"}};

    string sUrl = "http://127.0.0.1/echo/callback";

    cpr::Response cprrsp;
    cprrsp = cpr::Post(Url{sUrl}, multipart, Timeout{6000});
    cout << "\n" <<sLongData << endl;

    return 0;
}
```

I use tcpdump to capture the actual content sent by the program and get the data that does not meet expectations.

![_15517875587249](https://user-images.githubusercontent.com/3839874/53804300-20cb3f00-3f82-11e9-99f5-c46417009011.png)

![_1551787629564](https://user-images.githubusercontent.com/3839874/53804346-435d5800-3f82-11e9-93b1-8d42ecbb323e.png)

Please Check, thanks.

**Comment by ouhaiyun0** [comment]
Hello, I have fixed this issue by update libcurl to version 7.64.0

But unfortunately there is some conflict between new version libcurl and cpr, because in curl.h

#define CURLE_SSL_CACERT CURLE_PEER_FAILED_VERIFICATION

and in cpr:

swtich case contained both CURLE_SSL_CACERT and CURLE_PEER_FAILED_VERIFICATION.

It may be need to do a little change

**Comment by whoshuu** [comment]
@ouhaiyun0 I believe this is fixed in the latest version of cpr with the merging of #296

**Comment by COM8** [comment]
Feel free to reopen this issue, if the answer from @whoshuu did not resolve your problem.
