### ISSUE TITLE
Part::datalen type, conversion warnings and validation.

### ISSUE THREAD

**Issue by qis** [whoshuu/cpr#307]
For someone not familiar with curl APIs, these warnings look quite scary.

```
session.cpp(189): warning C4312: 'reinterpret_cast': conversion from 'unsigned long' to 'const char *' of greater size
session.cpp(221): warning C4312: 'reinterpret_cast': conversion from 'const unsigned long' to 'const char *' of greater size
```

From what I could gather, this is benign and intentional. Is this assumption correct?

Given the special case in the documentation, can `datalen` be `0` and the `data` be `nullptr`?

<https://curl.haxx.se/libcurl/c/curl_formadd.html#CURLFORMCONTENTLEN>

**Comment by COM8** [comment]
Yes, this can be problematic and `curl_formadd` is also deprecated (see [here](https://curl.haxx.se/libcurl/c/curl_formadd.html) for reference).

https://github.com/whoshuu/cpr/blob/8bf5ac64140df19d907144e12c96e02f68d1a56a/cpr/session.cpp#L211-L242

**Comment by COM8** [comment]
This one has been fixed. I do not know when, but it does not occur any more.
Closing it for now.
Feel free to reopen in case this is still a problem.
