### ISSUE TITLE
Needs update to support curl 7.64.1

### ISSUE THREAD

**Issue by wangli28** [whoshuu/cpr#311]
When curl update to version 7.64.1, curl modified **CURLE_SSL_CACERT** in **curl.h**: L623
 `#define CURLE_SSL_CACERT CURLE_PEER_FAILED_VERIFICATION`
 caused a build error in _cpr/error.cpp_: 
```
ErrorCode Error::getErrorCodeForCurlError(std::int32_t curl_code) {
...
        case CURLE_SSL_CACERT: //60
            return ErrorCode::SSL_CACERT_ERROR

        case CURLE_PEER_FAILED_VERIFICATION: //60
            return ErrorCode::SSL_REMOTE_CERTIFICATE_ERROR;
...
```
See more information: 
[install-x86-windows-dbg-out.log](https://github.com/whoshuu/cpr/files/3124662/install-x86-windows-dbg-out.log)

Thanks.

**Comment by llchan** [comment]
I believe this is resolved by #296 which has already been merged, are you on master?
