### ISSUE TITLE
Prebuilt libcurl libraries v7.64.1 for windows openssl is not working

### ISSUE THREAD

**Issue by tomay3000** [whoshuu/cpr#312]
I have downloaded the prebuilt libcurl libraries v7.64.1 for windows from [here](https://curl.haxx.se/windows/)

The static build of cpr-example went smoothly, except I found that the OpenSSL built against libcurl is not working until I use this option: `cpr::VerifySsl{false}`.

**Comment by 161134050** [comment]
Yeah I had the same issue.. This lib is called CPR because you will need CPR after trying to build on windows

**Comment by COM8** [comment]
Ping @kingkili.

**Comment by KingKili** [comment]
Can you please provide an build log, or an minimal example.

**Comment by COM8** [comment]
Closing this since there has not been a response for a month now.
