### ISSUE TITLE
unsafe for multiple threads to call cpr::Get?

### ISSUE THREAD

**Issue by LumaGhost** [whoshuu/cpr#313]
If I am understanding correctly: `cpr::Get` ultimately calls `curl_easy_init`. Based on [the curl documentation](https://curl.haxx.se/libcurl/c/curl_easy_init.html)

"If you did not already call curl_global_init, curl_easy_init does it automatically. This may be lethal in multi-threaded cases, since curl_global_init is not thread-safe, and it may result in resource problems because there is no corresponding cleanup."

I searched this repo for `curl_global_init` but did not find anything. does the user have to call `curl_global_init` on their own in order to be thread safe? does your library handle the global init in any way? I do not have any experience with curl so I may be missing something. 

I did notice https://github.com/whoshuu/cpr/issues/101 but I think similar errors are still possible. Since `Post` can still end up calling `curl_global_init` from more than one thread?

I am trying to understand the behavior better. any help is appreciated (:

**Comment by NightNightNight** [comment]
so, how to use cpr in multiple threads? any question?

**Comment by brownfeng** [comment]
> so, how to use cpr in multiple threads? any question?

我们这边直接在全局启动时候.手动初始化了curl_global_init.

**Comment by ITotalJustice** [comment]
I noticed that the library doesn't call `curl_gloab_init` and instead lets `curl_easy_init` call it instead (hence the need for mutex locks). I think a better solution would be to just require the user to call `curl_global_init` at least once, or make a wrapper for the function (better) because otherwise `curl_easy_init` is thread safe. However I understand that by forcing an init, it takes away some of the simplicity of the library, but then again, I find it very common in most libs to require at least one init before use.

**Comment by COM8** [comment]
The problem with the user calling `curl_global_init` would be, we would have to provide a wrapper call to prevent them having to link against libcurl.
Also, like you mentioned this removes a bit of simplicity and convenience for users.
So I'd suggest we are keeping this mutex here.

**Comment by ITotalJustice** [comment]
> 
> 
> The problem with the user calling `curl_global_init` would be, we would have to provide a wrapper call to prevent them having to link against libcurl.
> Also, like you mentioned this removes a bit of simplicity and convenience for users.
> So I'd suggest we are keeping this mutex here.

Yeah after looking at the [source](https://github.com/curl/curl/blob/3186f5005497df68ef0735b2e23b8a5c9d76d8b9/lib/easy.c#L286) for `curl_easy_init`, i agree with you that keeping the mutex is the best option. I was under the impression that if curl easy did globally init curl for us, then it would call `curl_global_cleanup` when calling easy cleanup. Very happy that's not the case :)

**Comment by crazydef** [comment]
If you are not going to wrap `curl_global_init`, then we still need to call it ourselves (and link against libcurl) to override Curl's memory management functions.

**Comment by COM8** [comment]
> If you are not going to wrap `curl_global_init`, then we still need to call it ourselves (and link against libcurl) to override Curl's memory management functions.

You are right here.

But if there is need for it, please create a issue for it, so we provide proper wrappers for the curl memory management where we then can integrate cpr into it (pmr and std custom allocators?).
