### ISSUE TITLE
I get a bunch of errors when running this library

### ISSUE THREAD

**Issue by ghost** [whoshuu/cpr#314]
So here is what I get whenever I try to compile

1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: bool __thiscall cpr::CaseInsensitiveCompare::operator()(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)const " (??RCaseInsensitiveCompare@cpr@@QBE_NABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@0@Z) referenced in function "bool __cdecl std::_Debug_lt_pred<struct cpr::CaseInsensitiveCompare &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &>(struct cpr::CaseInsensitiveCompare &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (??$_Debug_lt_pred@AAUCaseInsensitiveCompare@cpr@@AAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@ABV34@@std@@YA_NAAUCaseInsensitiveCompare@cpr@@AAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@0@ABV30@@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: __thiscall cpr::Parameters::Parameters(class std::initializer_list<struct cpr::Parameter> const &)" (??0Parameters@cpr@@QAE@ABV?$initializer_list@UParameter@cpr@@@std@@@Z) referenced in function _main
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: __thiscall cpr::Session::Session(void)" (??0Session@cpr@@QAE@XZ) referenced in function "class cpr::Response __cdecl cpr::Get<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,int,class cpr::Parameters>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&,int &&,class cpr::Parameters &&)" (??$Get@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HVParameters@cpr@@@cpr@@YA?AVResponse@0@$$QAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$$QAH$$QAVParameters@0@@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: __thiscall cpr::Session::~Session(void)" (??1Session@cpr@@QAE@XZ) referenced in function "class cpr::Response __cdecl cpr::Get<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,int,class cpr::Parameters>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&,int &&,class cpr::Parameters &&)" (??$Get@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HVParameters@cpr@@@cpr@@YA?AVResponse@0@$$QAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$$QAH$$QAVParameters@0@@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: void __thiscall cpr::Session::SetOption(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?SetOption@Session@cpr@@QAEXABV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z) referenced in function "void __cdecl cpr::priv::set_option<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >(class cpr::Session &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&)" (??$set_option@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@priv@cpr@@YAXAAVSession@1@$$QAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: void __thiscall cpr::Session::SetOption(class cpr::Parameters &&)" (?SetOption@Session@cpr@@QAEX$$QAVParameters@2@@Z) referenced in function "void __cdecl cpr::priv::set_option<class cpr::Parameters>(class cpr::Session &,class cpr::Parameters &&)" (??$set_option@VParameters@cpr@@@priv@cpr@@YAXAAVSession@1@$$QAVParameters@1@@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: void __thiscall cpr::Session::SetOption(bool const &)" (?SetOption@Session@cpr@@QAEXAB_N@Z) referenced in function "void __cdecl cpr::priv::set_option<int>(class cpr::Session &,int &&)" (??$set_option@H@priv@cpr@@YAXAAVSession@1@$$QAH@Z)
1>ConsoleApplication1.obj : error LNK2019: unresolved external symbol "public: class cpr::Response __thiscall cpr::Session::Get(void)" (?Get@Session@cpr@@QAE?AVResponse@2@XZ) referenced in function "class cpr::Response __cdecl cpr::Get<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,int,class cpr::Parameters>(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > &&,int &&,class cpr::Parameters &&)" (??$Get@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@HVParameters@cpr@@@cpr@@YA?AVResponse@0@$$QAV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@$$QAH$$QAVParameters@0@@Z)

What to do

**Comment by Danc2050** [comment]
I hear you... I tried to install it manually and followed [this guy's code](https://github.com/whoshuu/cpr/issues/161) almost exactly, try to run the `README` code and still get "reference" issues. Glad to know I am not the only one experiencing issues.

**Comment by helloitsm3** [comment]
Did any of you manage to fix this issue? I'm having it right now and I'm unsure how to fix this linker problem

**Comment by Danc2050** [comment]
@helloitsm3 I gave up on it and just used python's request library.

**Comment by helloitsm3** [comment]
> @helloitsm3 I gave up on it and just used python's request library.

I manage to get it working

**Comment by jungletek** [comment]
Those are linker errors, it's probable your compiler can't find the compiled library to link to your app.

After a bit of headache and adding some patches for CMake and MinGW stuff, I managed to get it to build and link.

Part of being a C++ dev is unfortunately dealing with library and dependency hell. Package managers help with this, FWIW.

**Comment by helloitsm3** [comment]
> Those are linker errors, it's probable your compiler can't find the compiled library to link to your app.
> 
> 
> 
> After a bit of headache and adding some patches for CMake and MinGW stuff, I managed to get it to build and link.
> 
> 
> 
> Part of being a C++ dev is unfortunately dealing with library and dependency hell. Package managers help with this, FWIW.

You're right. I manage to fix my errors using vspkg, however, not all libraries are listed there so that's the downside of using vspkg.

**Comment by amrosado** [comment]
I had this issue as well when trying to use cpr after intalling with vcpkg.  One thing that helps is switching vcpkg to install x64 packages instead of x86.  You can do this with the following environment variable:

`VCPKG_DEFAULT_TRIPLET=x64-windows`

You should then make sure that your visual studio includes and library directories for vcpkg installed packages are setup correctly.

**Comment by helloitsm3** [comment]
> 
> 
> I had this issue as well when trying to use cpr after installing with vcpkg. Specifically, I'm trying to compile a x64 program with cpr. One thing that helps is switching vcpkg to install x64 packages instead of x86. You can do this with the following environment variable:
> 
> `VCPKG_DEFAULT_TRIPLET=x64-windows`
> 
> You should then make sure that your visual studio includes and library directories for vcpkg installed packages are setup correctly.

You can also install both versions which was what I did.

32-bit version
`vcpkg install cpr`

64-bit version
`vcpkg install cpr:x64-windows`

**Comment by HerrDrFink** [comment]
**Try this**

.\vcpkg integrate install
--> Applied user-wide integration for this vcpkg root.

**Result**

All MSBuild C++ projects can now #include any installed libraries.
Linking will be handled automatically.
Installing new libraries will make them instantly available.

[Source](https://vcpkg.readthedocs.io/en/latest/examples/installing-and-using-packages/)

**Comment by hostinfodev** [comment]
> > I had this issue as well when trying to use cpr after installing with vcpkg. Specifically, I'm trying to compile a x64 program with cpr. One thing that helps is switching vcpkg to install x64 packages instead of x86. You can do this with the following environment variable:
> > `VCPKG_DEFAULT_TRIPLET=x64-windows`
> > You should then make sure that your visual studio includes and library directories for vcpkg installed packages are setup correctly.
> 
> You can also install both versions which was what I did.
> 
> 32-bit version
> `vcpkg install cpr`
> 
> 64-bit version
> `vcpkg install cpr:x64-windows`

This was the solution for me after installing `cpr` via `vcpkg` and running into the same error. The error noted invalid architecture was being used, which brought me here. :) In my case, I was using `x86` version of `cpr` when I should've been using `x64`. Cheers!
