### ISSUE TITLE
Fatal error: cpr/cpr.h: No such file or directory

### ISSUE THREAD

**Issue by cabatchi** [whoshuu/cpr#316]
So I'm trying to get this to run

```
using namespace std;

#include <iostream>
#include <cpr> 

int main(int argc, char** argv) {
    auto r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"},
                      cpr::Authentication{"user", "pass"},
                      cpr::Parameters{{"anon", "true"}, {"key", "value"}});
    r.status_code;                  // 200
    r.header["content-type"];       // application/json; charset=utf-8
    r.text;                         // JSON text string
}
```

But when I try to run it in VSCode 2019, I get "fatal error: cpr/cpr.h: No such file or directory."

I've added ${workspaceFolder}/cpr/include to my includePath but no die.

**Comment by Dankkkk** [comment]
Use common sense, replace 'cpr/cpr.h' with your includes working directory.

**Comment by goncaloperes** [comment]
Copy [this include folder](https://github.com/whoshuu/cpr/tree/master/include/cpr) to the include path directory of your development environment (or the one you predefined). Then add the following to your script `#include <cpr/cpr.h>`

**Comment by COM8** [comment]
Feel free to reopen this issue, if the answer from @kdeng00 did not resolve your problem.

**Comment by Mr-Kips** [comment]
Sir, I am also facing this problem , in my case for each #include my VS code can't search for header file in the working dir of main program (main.cpp) . means when I include header file as **#include "cpr/cpr.h"** its done just here but when in the cpr.h internal def of #include "api.h" executes then compiler search for **api.h**  file in 'cpr/cpr/api.h' becaouse of now the **api.h** have that 'cpr/' dir relative to main.cpp.
then it shows error : 
**cpr/cpr.h:4:10: fatal error: cpr/api.h: No such file or directory
    4 | #include "cpr/api.h"**
    
    how can I solve this issue

**Comment by COM8** [comment]
@Mr-Kips Could you please provide an example project for me to reproduce this behavior?
