### ISSUE TITLE
Support for bearer token authentication

### ISSUE THREAD

**Issue by palucki** [whoshuu/cpr#318]
Nowadays more and more REST APIs are using bearer token authentication.
Maintainers of cURL introduced it some time ago. Please see:
[CURLOPT_HTTPAUTH](https://curl.haxx.se/libcurl/c/CURLOPT_HTTPAUTH.html)
[CURLOPT_XOAUTH2_BEARER](https://curl.haxx.se/libcurl/c/CURLOPT_XOAUTH2_BEARER.html)

It would be great if your lib supports it as well.

**Comment by souaremsaidou** [comment]
Maybe this is what you are looking for

```
    auto r = cpr::Post(cpr::Url{"http://lifecycle-hom/service/authentication-server/login"},
                       cpr::Header{{"Authorization", "Bearer Hulk"}},
                       cpr::Body{"username=Bruce&password=Banner"});
```

BR
Saidou

**Comment by COM8** [comment]
We should add support for this.
Does not look overly complicated to implement.
Anybody here wants to work on a PR for this?
