### ISSUE TITLE
misleading name cpr::Header lead to silently overwriting headers

### ISSUE THREAD

**Issue by saucecode** [whoshuu/cpr#319]
`cpr::Header` is a misleading name. The correct name should be `cpr::Headers`.

By using the name `cpr::Header`, it implies that the following code is correct. But alas, the following code is not correct.
```
cpr::Response response = cpr::Post(cpr::Url{"https://httpbin.org/post"},
   cpr::Header{{"Authorization", myAuthorization}},
   cpr::Header{{"Content-Length", "0"}}
);
```

The above code snippet will not send the `Authorization` header, because it is overwritten by the `Content-Length` header on the next line.

Here's the correct code, which behaves as expected under the current version.

```
cpr::Response response = cpr::Post(cpr::Url{"https://httpbin.org/post"},
   cpr::Header
   {
        {"Authorization", myAuthorization},
        {"Content-Length", "0"}
   }
);
```

This confusion could've been prevented by either:

 - Pluralization `cpr::Header -> cpr::Headers`
 - *Any* example code showing a use case where two or more custom headers are used, such as that pictured above.

It took too long to figure out that this was why our requests were failing. Hopefully others do not suffer the same fate.

**Comment by jungletek** [comment]
Read the documentation, it's actually quite good.

If you had, you might have seen where they specify that `Header` and other classes are "Map-like" in how they handle key-pairs, etc., as well as seen an actual implementation of how to use them.

The set of double-braces should be a clue, they're braces within braces, implying a container of containers.
