### ISSUE TITLE
Upload file 

### ISSUE THREAD

**Issue by ArjunNarayan2066** [whoshuu/cpr#320]
Is there support to upload a file using this library? Im wondering if there is a method to give a filepath & it will automatically upload the file via POST request (assuming required auth info is given)? 
Im looking to upload a file but without needing to touch the filesystem myself

**Comment by kdeng00** [comment]
```C++
auto url = "https://uritouploadfile.com/upload/file"; 

// Path of the file you want to upload
const std::string filePath("/tmp/file/path.ext");

// Where you implement your or retrieve your auth info
const std::string auth("");

auto r = cpr::Post(cpr::Url{url}, cpr::Multipart{{"key", "small value"},
    {"file", cpr::File{filePath}}}, cpr::Header{{"authorization", authInfo}}
);

bool uploaded = (r.status_code == 200) ? true : false;
```

**Comment by COM8** [comment]
Feel free to reopen this issue, if the answer from @kdeng00 did not resolve your problem.
