### ISSUE TITLE
Using custom characters in GET request parameters

### ISSUE THREAD

**Issue by uched41** [whoshuu/cpr#324]
Currently, the library encodes all special characters except a select few. 
I encountered a situation where I need to add commans ',' to one of my GET request parameters. I made a quick fix by adding editing the urlencode function in utils.cpp. 
I could make a pull request and implement a more robust function to enable users to pass a list of special characters to ignore.
Is this feature needed?

```
cpr::Parameters{
	{"datatype", "eph,pos,aux"}
}
```

this is encoded as:
```
datatype=eph%2Cpos%2Caux
```

**Comment by COM8** [comment]
Sounds like a nice features.
Something like: Encode stuff `true` or `false` would be great, with the default being `true`.

**Comment by rlagur9286** [comment]
I also need this function now, is it being provided?

**Comment by COM8** [comment]
I added this feature.
Here you can find two examples:
https://github.com/whoshuu/cpr/blob/04f06b837e16b286d9693a62471ddd46cb54c93f/test/structures_tests.cpp#L19-L29

https://github.com/whoshuu/cpr/blob/04f06b837e16b286d9693a62471ddd46cb54c93f/test/structures_tests.cpp#L40-L50
