### ISSUE TITLE
compile fail on windows using cpr library

### ISSUE THREAD

**Issue by Rahul123456789mondal** [whoshuu/cpr#328]
||=== Build: Debug in api_connect (compiler: GNU GCC Compiler) ===|
obj\Debug\main.o||In function `ZN3cpr4PostIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_4BodyESt3mapIS6_S6_NS_22CaseInsensitiveCompareESaISt4pairIKS6_S6_EEEEEENS_8ResponseEDpOT_':|
D:\api_connect\cpr\api.h|62|undefined reference to `cpr::Session::Session()'|
D:\api_connect\cpr\api.h|64|undefined reference to `cpr::Session::Post()'|
D:\api_connect\cpr\api.h|62|undefined reference to `cpr::Session::~Session()'|
D:\api_connect\cpr\api.h|62|undefined reference to `cpr::Session::~Session()'|
obj\Debug\main.o||In function `ZN3cpr3GetIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_8ResponseEDpOT_':|
D:\api_connect\cpr\api.h|39|undefined reference to `cpr::Session::Session()'|
D:\api_connect\cpr\api.h|41|undefined reference to `cpr::Session::Get()'|
D:\api_connect\cpr\api.h|39|undefined reference to `cpr::Session::~Session()'|
D:\api_connect\cpr\api.h|39|undefined reference to `cpr::Session::~Session()'|
obj\Debug\main.o||In function `ZN3cpr6DeleteIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_8ResponseEDpOT_':|
D:\api_connect\cpr\api.h|131|undefined reference to `cpr::Session::Session()'|
D:\api_connect\cpr\api.h|133|undefined reference to `cpr::Session::Delete()'|
D:\api_connect\cpr\api.h|131|undefined reference to `cpr::Session::~Session()'|
D:\api_connect\cpr\api.h|131|undefined reference to `cpr::Session::~Session()'|
obj\Debug\main.o||In function `ZN3cpr4priv10set_optionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRNS_7SessionEOT_':|
D:\api_connect\cpr\api.h|25|undefined reference to `cpr::Session::SetOption(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'|
obj\Debug\main.o||In function `ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_S5_ESt10_Select1stIS8_EN3cpr22CaseInsensitiveCompareESaIS8_EE29_M_get_insert_hint_unique_posESt23_Rb_tree_const_iteratorIS8_ERS7_':|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1923|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1928|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1934|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1944|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1950|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
obj\Debug\main.o:C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1516|more undefined references to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' follow|
obj\Debug\main.o||In function `ZN3cpr4priv10set_optionINS_4BodyEEEvRNS_7SessionEOT_':|
D:\api_connect\cpr\api.h|25|undefined reference to `cpr::Session::SetOption(cpr::Body&&)'|
obj\Debug\main.o||In function `ZN3cpr4priv10set_optionISt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_NS_22CaseInsensitiveCompareESaISt4pairIKS8_S8_EEEEEvRNS_7SessionEOT_':|
D:\api_connect\cpr\api.h|25|undefined reference to `cpr::Session::SetOption(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cpr::CaseInsensitiveCompare, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'|
obj\Debug\main.o||In function `ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_S5_ESt10_Select1stIS8_EN3cpr22CaseInsensitiveCompareESaIS8_EE24_M_get_insert_unique_posERS7_':|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1820|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1831|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
||error: ld returned 1 exit status|
||=== Build failed: 24 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|
||=== Build: Debug in api_connect (compiler: GNU GCC Compiler) ===|
obj\Debug\main.o||In function `ZN3cpr4PostIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEENS_4BodyESt3mapIS6_S6_NS_22CaseInsensitiveCompareESaISt4pairIKS6_S6_EEEEEENS_8ResponseEDpOT_':|
D:\api_connect\cpr\api.h|62|undefined reference to `cpr::Session::Session()'|
D:\api_connect\cpr\api.h|64|undefined reference to `cpr::Session::Post()'|
D:\api_connect\cpr\api.h|62|undefined reference to `cpr::Session::~Session()'|
D:\api_connect\cpr\api.h|62|undefined reference to `cpr::Session::~Session()'|
obj\Debug\main.o||In function `ZN3cpr3GetIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_8ResponseEDpOT_':|
D:\api_connect\cpr\api.h|39|undefined reference to `cpr::Session::Session()'|
D:\api_connect\cpr\api.h|41|undefined reference to `cpr::Session::Get()'|
D:\api_connect\cpr\api.h|39|undefined reference to `cpr::Session::~Session()'|
D:\api_connect\cpr\api.h|39|undefined reference to `cpr::Session::~Session()'|
obj\Debug\main.o||In function `ZN3cpr6DeleteIJNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEENS_8ResponseEDpOT_':|
D:\api_connect\cpr\api.h|131|undefined reference to `cpr::Session::Session()'|
D:\api_connect\cpr\api.h|133|undefined reference to `cpr::Session::Delete()'|
D:\api_connect\cpr\api.h|131|undefined reference to `cpr::Session::~Session()'|
D:\api_connect\cpr\api.h|131|undefined reference to `cpr::Session::~Session()'|
obj\Debug\main.o||In function `ZN3cpr4priv10set_optionINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEEEEvRNS_7SessionEOT_':|
D:\api_connect\cpr\api.h|25|undefined reference to `cpr::Session::SetOption(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'|
obj\Debug\main.o||In function `ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_S5_ESt10_Select1stIS8_EN3cpr22CaseInsensitiveCompareESaIS8_EE29_M_get_insert_hint_unique_posESt23_Rb_tree_const_iteratorIS8_ERS7_':|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1923|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1928|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1934|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1944|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1950|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
obj\Debug\main.o:C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1516|more undefined references to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const' follow|
obj\Debug\main.o||In function `ZN3cpr4priv10set_optionINS_4BodyEEEvRNS_7SessionEOT_':|
D:\api_connect\cpr\api.h|25|undefined reference to `cpr::Session::SetOption(cpr::Body&&)'|
obj\Debug\main.o||In function `ZN3cpr4priv10set_optionISt3mapINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES8_NS_22CaseInsensitiveCompareESaISt4pairIKS8_S8_EEEEEvRNS_7SessionEOT_':|
D:\api_connect\cpr\api.h|25|undefined reference to `cpr::Session::SetOption(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, cpr::CaseInsensitiveCompare, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > > > const&)'|
obj\Debug\main.o||In function `ZNSt8_Rb_treeINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEESt4pairIKS5_S5_ESt10_Select1stIS8_EN3cpr22CaseInsensitiveCompareESaIS8_EE24_M_get_insert_unique_posERS7_':|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1820|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
C:\Program Files (x86)\CodeBlocks\MinGW\lib\gcc\mingw32\5.1.0\include\c++\bits\stl_tree.h|1831|undefined reference to `cpr::CaseInsensitiveCompare::operator()(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) const'|
||error: ld returned 1 exit status|
||=== Build failed: 24 error(s), 0 warning(s) (0 minute(s), 0 second(s)) ===|

**Comment by biom3tric** [comment]
Build it using MinGW or Clang (LLVM), CPR does not support MSVC compiler.
Also, check you well followed instructions here https://github.com/whoshuu/cpr#usage

**Comment by daimiaopeng** [comment]
me too

**Comment by jungletek** [comment]
> Build it using MinGW or Clang (LLVM), CPR does not support MSVC compiler.
> Also, check you well followed instructions here https://github.com/whoshuu/cpr#usage

They're using GCC (MinGW), duh.

@Rahul123456789mondal 
Undefined Reference == Linker Error.

Learn to setup your IDE for external libs.
