### ISSUE TITLE
How to run this in Makefile project

### ISSUE THREAD

**Issue by RazdolbayOne** [whoshuu/cpr#332]
Hi,I have Linux Makefile project how to use this wrapper lib in my project? What "keys" i must add to Makefile rules e.t.c  in cURL is  **-lcurl** but what about wrappers "keys"?
BTW is any Install guides how to install this wrapper on Linux/VSCode do not using CMake?

**Comment by COM8** [comment]
You could use [`vcpkg`](https://github.com/CloudPolis/webdav-client-cpp) and then just link against CPR.

Might be related to:
https://github.com/whoshuu/cpr/issues/352#issuecomment-614537289

**Comment by COM8** [comment]
Closing this since there has not been a response for a month now.
