### ISSUE TITLE
Compile error fix incorrect identification const char mimetypd

### ISSUE THREAD

**Issue by timeisflowing** [whoshuu/cpr#335]
‘mimetype’ undeclared (first use in this function); did you mean ‘mimetypd’?
opt/curl/lib/mime.c:1320

renamed CURLcode curl_mime_type(curl_mimepart *part, const char *mimetyped) to 
CURLcode curl_mime_type(curl_mimepart *part, const char *mimetype) and build no problem.

Respects!

**Comment by COM8** [comment]
Would you like to create a PR for this?

**Comment by COM8** [comment]
Is this still a problem?

**Comment by timeisflowing** [comment]
It was not compiled because of a misspelled variant, compiled after correcting it no problem :)
