### ISSUE TITLE
Webdav support

### ISSUE THREAD

**Issue by jothepro** [whoshuu/cpr#336]
I want to make WebDav-requests with libcurl.

Is it in the scope of cpr to also support the webdav-verbs COPY, LOCK, MKCOL, MOVE, PROPFIND, PROPPATCH, UNLOCK somewhere in the future?

I'd prefer to contribute to this project to match my needs instead of writing another bad libcurl-wrapper just for my use-case. But I'd like to make sure that a PR with these changes would have a chance to make it into master.

**Comment by COM8** [comment]
I don't think `webdav` support is something this lib should focus on.
If it's easy enough to implement I would say, sure go for it, but there exist other libraries like https://github.com/CloudPolis/webdav-client-cpp that already provide this functionality.

**Comment by jothepro** [comment]
The library you linked is a good example for why I think cpr would benefit from opening up for other http-verbs than the frequently used ones. It is basically a custom curl wrapper with a tiny bit of xml parsing involved, which would render it somehow obsolete if cpr would allow the use of webdav http-verbs (Parsing the webdav-xml is pretty straight forward).
As for my usecase using a library like this did not quite match my requirements, so I was forced to [write my own](https://gitlab.com/jothepro/libcloudsync/-/tree/master/src/request/curl) (poorly implemented, as promised :stuck_out_tongue:) curl wrapper that matched my needs. It's interface differs from cpr in the fact that you can basically pass any http-verb you like as a string & the wrapper tries to figure out what the correct behaviour for the verb should be. _(Don't look at the Oauth2 part, I'm not even sure if it works :see_no_evil:)_

With the knowledge gained from implementing my own wrapper I'd like to ask a different question now:
I see how additionally supporting webdav verbs in cpr would kind of make the project loose it's focus. Plain curl offers this pretty powerful interface that basically allows you to pass any verb you like. **May it be in the scope of cpr to also open up to ANY http verb, not restricting users to just the most frequently used ones?** This would allow my project to build on a far more stable and capable base than it currently does.

**Comment by COM8** [comment]
@jothepro, Yes this would definitely be possible to create an extension for CPR which supports user defined http verbs.
You are more than welcome to create a PR, adding this feature.

**Comment by jothepro** [comment]
Should I rename this Issue ("supporting user defined verbs") to track progress on the feature or open a new issue?

**Comment by COM8** [comment]
I would suggest creating a new issue for that.
Thanks!
