### ISSUE TITLE
How can I compile the project under centos7?

### ISSUE THREAD

**Issue by mslovy** [whoshuu/cpr#337]
I want to compile the project under centos7, but when running cmake, got the error below:

CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

anyone can help? 

the project is compiled successfully under ubuntu 16.04 following the logs in travis-ci

**Comment by jothepro** [comment]
It seems like you have not set up your build-system properly. 
[Stackoverflow says you need to install a compiler like gcc/g++](https://stackoverflow.com/questions/48160125/cmake-was-unable-to-find-a-build-program-corresponding-to-unix-makefiles)

**Comment by jothepro** [comment]
Oh and readling the error message tells you that you also need to install `make` or another build tool.

**Comment by mslovy** [comment]
Thanks, I solved problem by installing make.
