### ISSUE TITLE
Support for CURLOPT_UNIX_SOCKET_PATH

### ISSUE THREAD

**Issue by leeyiw** [whoshuu/cpr#344]
Hello, I want to use CPR with my existing project, but it looks like CPR doesn't support connect to UNIX socket HTTP server for now. I used to made it work by using `curl_easy_setopt` with  `CURLOPT_UNIX_SOCKET_PATH` option.

Is it possible to add this feature to CPR? If it is, I'm happy to contribute a PR for it.

@tstack @whoshuu

**Comment by COM8** [comment]
Looks like a nice to have feature.
If you need it in time, it might be the best if you create a PR for it ;).
Else we are currently starting to work on the backlog of feature requests.

**Comment by COM8** [comment]
There already exists a PR for this:
https://github.com/whoshuu/cpr/pull/282

Related issue:
https://github.com/whoshuu/cpr/issues/279
