### ISSUE TITLE
How can I build this library using toolchain for arm?

### ISSUE THREAD

**Issue by RobsonRojas** [whoshuu/cpr#346]

**Comment by NightNightNight** [comment]
![image](https://user-images.githubusercontent.com/16199542/77038066-c61a4f00-69ed-11ea-9e28-51afb12c5db9.png)
![image](https://user-images.githubusercontent.com/16199542/77038117-e5b17780-69ed-11ea-91b1-89042dc701ff.png)

**Comment by COM8** [comment]
If the answer from @NightNightNight did not solve your problem, feel free to reopen this issue again.
