### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by SJS830** [whoshuu/cpr#347]
I tried to compile this with mingw32-make, but I get the following errors:

undefined reference to `GetTickCount64'

undefined reference to `InitializeCriticalSectionEx'

recipe for target 'lib/libcurl.dll' failed

recipe for target 'cpr/opt/curl/lib/CMakeFiles/libcurl.dir/all' failed

**Comment by jungletek** [comment]
Did you configure it beforehand somehow with CMake or it's GUI?

Undefined reference is a linker error, the linker can't find a matching function that your code specifies.

It's not a bug, it's user error on your part.
