### ISSUE TITLE
Name followed by '::' must be a class or namespace name.

### ISSUE THREAD

**Issue by Enebz** [whoshuu/cpr#351]
I am doing this:
```cpp
#include "cpr/include/cpr/cpr.h"

int main()
{
    auto r = **cpr**::Get(**cpr**::Url{ "https://api.github.com/repos/whoshuu/cpr/contributors" });
}
```
On the cpr:: it gives me "Name followed by '::' must be a class or namespace name."

![image](https://user-images.githubusercontent.com/46542339/75077761-f6142680-5503-11ea-824d-902a624ee00b.png)

**Comment by jungletek** [comment]
Your IDE can't find your CPR include directory, you need to do more than just add an `#include`.

Look up what the process is for whatever IDE you use to properly set include and lib paths for external libraries you want to use.

**Comment by COM8** [comment]
How did you install `CPR`?

**Comment by COM8** [comment]
Closing this since no response for one month.
