### ISSUE TITLE
modern CMake support

### ISSUE THREAD

**Issue by Xeverous** [whoshuu/cpr#353]
Hello, I'm interested in using the library however I want to have 2 things: modern C++ and modern CMake. The first one is rather trivial to find info about but the second is (still) rather hard to encounter.

So what I mean by modern CMake is:

- Any project that needs library `foobar` should be enough to just write `target_link_libraries(project_name PRIVATE foobar)`. If there are any compiler/linker flags missing that's the library's fault.
- `foobar` should never touch any global CMake variables  (`CMAKE_*`) as changing any can corrupt the build of the whole dependency tree. It should instead declare everything through `target_*` CMake functions as either `PUBLIC` or `PRIVATE` requirement.

This repository contains rather old CMake recipe, so I'm asking whether you are interested in any PRs. The would bump the minimum required CMake version significantly. I can not safely use it in it's current form in my projects because it resets some global CMake variables and uses a keyword-less `target_link_libraries` call which corrupts any descendant targets which then can not use modern version of the function.

**Comment by tolstenko** [comment]
Did you try the hunterized version? https://hunter.readthedocs.io/en/latest/packages/pkg/cpr.html https://github.com/cpp-pm/hunter

**Comment by Xeverous** [comment]
No, I have no experience with Hunter but I see that https://github.com/hunter-packages/cpr/blob/hunter/CMakeLists.txt apart from hunter-related changes, has the same problems like modifying global flags or keyword-less linking which corrupts any descendant project.

**Comment by COM8** [comment]
Ping @kingkili.

**Comment by KingKili** [comment]
I think this is valid, and plan to rewrite the CMake scripts for cpr.
