### ISSUE TITLE
no route to host

### ISSUE THREAD

**Issue by NightNightNight** [whoshuu/cpr#355]
When i use cpr post form data, occasionally, no route to host appears, then connect timeout. Check the network normal.

![image2020-2-13 13_51_9](https://user-images.githubusercontent.com/16199542/75764376-be657400-5d78-11ea-8500-f56f533cef3a.png)

**Comment by COM8** [comment]
Could you provide a minimal project for reproduction of this error.
Does it only happen if you try to connect to `192.168.127.200:8080`?

**Comment by COM8** [comment]
Closing this since there has not been a response for a month now.
