### ISSUE TITLE
New release for an updated conan pakage

### ISSUE THREAD

**Issue by COM8** [whoshuu/cpr#360]
Would it be possible to create a new release tag (e.g. `1.4` or `1.3.1`) so conan has access to all the latest fixes, especially to those bugs introduced by `curl` (e.g. #343 and #296).
Conan is still on the `cpr/1.3.0` release.

**Comment by COM8** [comment]
Like mentioned over here:
https://github.com/whoshuu/cpr/issues/362#issuecomment-614168836

There will be a new release, by the end of next week.

**Comment by tstack** [comment]
@COM8 Are there any other changes that you think should be in this release?  It might be nice to get #364 in, have you made any progress on that?

**Comment by COM8** [comment]
@tstack I think this is the only PR/issue that should be included in the next release.
I was having problems installing VS2015 this is what kept me back since the download is so large and it was not running that well, the last couple of days.

I'm trying to reproduce it but on my end everything compiles like a charm.
Would it be possible for you to push back the release until Tuesday so I'm able to say with 100% certainty, this is not an issue?

If not, you can create the release/tag and then perhaps just create a quick new tag, by the end of next week when issues occurred.

**Comment by tstack** [comment]
I'm in no rush, Tuesday is fine.

**Comment by KingKili** [comment]
Conan should get releases with https://github.com/conan-io/conan-center-index/pull/1496
