### ISSUE TITLE
How can I use cpr as a static linked library on Windows?

### ISSUE THREAD

**Issue by shavitush** [whoshuu/cpr#361]
Hiya. I got cpr and libcurl from vcpkg

```
./vcpkg install libcurl:x86-windows-static
./vcpkg install cpr:x86-windows-static
```

Due to vcpkg having a static package for cpr, I just assume that it exists and works.

Now.. it works. However, requires `libcurl.dll` and `zlib1.dll` in the app's directory.
When I try to build with the runtime library as `Multi-threaded (/MT)`, I get a bunch of errors from cpr

```
1>cpr.lib(session.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in CMainWindow.obj
1>cpr.lib(auth.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in CMainWindow.obj
1>cpr.lib(cookies.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in CMainWindow.obj
1>cpr.lib(digest.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in CMainWindow.obj
1>cpr.lib(proxies.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in CMainWindow.obj
1>cpr.lib(error.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in CMainWindow.obj
1>cpr.lib(timeout.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in CMainWindow.obj
1>cpr.lib(util.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in CMainWindow.obj
1>cpr.lib(cprtypes.cpp.obj) : error LNK2038: mismatch detected for 'RuntimeLibrary': value 'MD_DynamicRelease' doesn't match value 'MT_StaticRelease' in CMainWindow.obj
```

Am I doing something wrong?

**Comment by dylanmit** [comment]
Facing the same issue, building in vs2019 requires zlib1 and libcurl.dll be in the same folder as the exe that was compiled :\

**Comment by COM8** [comment]
Ping @KingKili .

**Comment by KingKili** [comment]
I don't know how vcpk works, but if you add cpr with 'fetch_content' as recommend this should be no problem.
I think it is best if you create an issue at vcpkg.

**Comment by sofneo** [comment]
Bump

**Comment by MFMokbel** [comment]
Vcpkg is the way to go. It is working for me on VS2017. Do the following:

1. ./vcpkg install cpr
2. ./vcpkg install cpr:x86-windows-static
3. ./vcpkg install libcurl
4. ./vcpkg install libcurl:x86-windows-static (this is if you're not interested in SSL/TLS, otherwise you have to install OpenSSL too)

Open VS Project Propertie:
-> Vcpkg -> and set **Use static libraries** to **Yes**.
-> C/C++ -> Code Generation -> set **Runtime Library** to **Multi-threaded (/MT)**

**Comment by shavitush** [comment]
@MFMokbel 
>  -> Vcpkg -> and set Use static libraries to Yes.

Where do you see this part?

**Comment by MFMokbel** [comment]
@shavitush 

![image](https://user-images.githubusercontent.com/4950707/91894307-7e1d7a80-ec63-11ea-96fd-1c52b37643ab.png)

**Comment by COM8** [comment]
Closing this one in favor of #361

**Comment by bl-ue** [comment]
> Closing this one in favor of #361

@COM8, this _is_ #361.  Did you mean #520?

**Comment by COM8** [comment]
> > Closing this one in favor of #361
> 
> @COM8, this _is_ #361. Did you mean #520?

Right, thanks!

**Comment by 0x0ff537** [comment]
I have successfully compile a static binary with Visual Studio 2019. Apart from using vcpkg to install the static libraries and setting the proper values as mentioned by MFMokbel I also needed to add these:
`#pragma comment (lib, "cpr.lib")
#pragma comment (lib, "libcurl.lib")
#pragma comment(lib,"Ws2_32.lib")
#pragma comment(lib,"Wldap32.lib")
#pragma comment(lib,"Crypt32.lib")
`
I'm not using SSL/TLS but in nay case the last 3 libraries are needed by libcurl.lib.

Hope it helps someone.

**Comment by hamzaahmedzia1** [comment]
I can confirm the fix from @0x0ff537  works for Visual Studio 2022 using vcpkg and x86 static linking.

**Comment by gelatyna** [comment]
HI, i've done everything as you all said, but i still have an error:  

LINK : fatal error LNK1104: cannot open file 'libcurl.lib'

I would be happy if someone could help me :)

**Comment by MFMokbel** [comment]
@gelatyna,

Check if the curl library is installed.

**Comment by CypherpunkSamurai** [comment]
How can i static link in Mingw64? I'm using msys2

**Comment by BaiFeng666** [comment]
严重性	代码	说明	项目	文件	行	禁止显示状态
错误	LNK1181	无法打开输入文件“libssl.lib”	BFMenuV2	D:\Github\BFMenuV2\BFMenuV2\LINK	1

**Comment by nmbf02** [comment]
How did you to download that library, i've not fount: 
libcurl.lib
