### ISSUE TITLE
How to use it in Visual Studio2019?

### ISSUE THREAD

**Issue by wcmiracle** [whoshuu/cpr#367]
1.git clone https://github.com/whoshuu/cpr.git
2.  cd cpr
3.  mkdir build && cd build
4.  cmake ..

and now my error message is:

-- Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.18363.
-- C++ Requests CMake Options
-- =======================================================
--   USE_SYSTEM_CURL: OFF
--   BUILD_CPR_TESTS: ON
--   GENERATE_COVERAGE: OFF
--   CPR_CURL_NOSIGNAL: OFF
--   USE_SYSTEM_GTEST: OFF
--   CMAKE_USE_OPENSSL: ON
-- =======================================================
-- Not using system Curl, using built-in curl project instead.
CMake Error at opt/CMakeLists.txt:48 (add_subdirectory):
  The source directory

    C:/Users/xxx/Desktop/project/pytest1/cpr/cpr/opt/curl

  does not contain a CMakeLists.txt file.

CMake Error at opt/CMakeLists.txt:60 (set_property):
  set_property could not find TARGET libcurl.  Perhaps it has not yet been
  created.

-- Set CURL_FOUND to TRUE.
-- Set CURL_LIBRARIES to libcurl.
-- Set CURL_INCLUDE_DIRS to /include;/include/curl.
-- Not using system gtest, using built-in googletest project instead.
CMake Error at opt/CMakeLists.txt:82 (add_subdirectory):
  The source directory

    C:/Users/xxx/Desktop/project/pytest1/cpr/cpr/opt/googletest

  does not contain a CMakeLists.txt file.

CMake Error at opt/CMakeLists.txt:90 (set_property):
  set_property could not find TARGET gtest.  Perhaps it has not yet been
  created.

CMake Error at opt/CMakeLists.txt:91 (set_property):
  set_property could not find TARGET gtest_main.  Perhaps it has not yet been
  created.

-- Set GTEST_FOUND to TRUE.
-- Set GTEST_LIBRARIES to gtest.
-- Set GTEST_MAIN_LIBRARIES to gtest_main.
-- Set GTEST_BOTH_LIBRARIES to gtest;gtest_main.
-- Set GTEST_INCLUDE_DIRS to /include.
-- Building mongoose project for test support.
CMake Error at opt/CMakeLists.txt:106 (add_subdirectory):
  The source directory

    C:/Users/xxx/Desktop/project/pytest1/cpr/cpr/opt/mongoose

  does not contain a CMakeLists.txt file.

-- Set MONGOOSE_FOUND to TRUE.
-- Set MONGOOSE_LIBRARIES to mongoose.
-- Set MONGOOSE_INCLUDE_DIRS to .
CMake Error at opt/CMakeLists.txt:116 (set_property):
  set_property could not find TARGET mongoose.  Perhaps it has not yet been
  created.

-- Using CURL_INCLUDE_DIRS: /include;/include/curl.
-- Using CURL_LIBRARIES: libcurl.
-- Configuring incomplete, errors occurred!
See also "C:/Users/xxx/Desktop/project/pytest1/cpr/cpr/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/xxx/Desktop/project/pytest1/cpr/cpr/build/CMakeFiles/CMakeError.log".

**Comment by COM8** [comment]
I need more context.
Could you provide information how you installed CPR, which OS (looks like VS on W10) and an example code that produces this error.

**Comment by wcmiracle** [comment]
vs2019
Win10 1909
cpr1.3.0

**Comment by wcmiracle** [comment]
CmakeError.log

Determining if the include file pthread.h exists failed with the following output:
Change Dir: C:/Users/40819/Desktop/project/pytest1/cpr/cpr/build/CMakeFiles/CMakeTmp

Run Build Command(s):C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/MSBuild/Current/Bin/MSBuild.exe cmTC_7e4fc.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=16.0 /v:m && 用于 .NET Framework 的 Microsoft (R) 生成引擎版本 16.5.0+d4cbfca49

版权所有(C) Microsoft Corporation。保留所有权利。



  用于 x64 的 Microsoft (R) C/C++ 优化编译器 19.25.28614 版

  CheckIncludeFile.cxx

  版权所有(C) Microsoft Corporation。保留所有权利。

  cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Qspectre /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_7e4fc.dir\Debug\\" /Fd"cmTC_7e4fc.dir\Debug\vc142.pdb" /Gd /TP /errorReport:queue C:\Users\40819\Desktop\project\pytest1\cpr\cpr\build\CMakeFiles\CMakeTmp\CheckIncludeFile.cxx

C:\Users\40819\Desktop\project\pytest1\cpr\cpr\build\CMakeFiles\CMakeTmp\CheckIncludeFile.cxx(1,10): fatal error C1083: 无法打开包括文件: “pthread.h”: No such file or directory [C:\Users\40819\Desktop\project\pytest1\cpr\cpr\build\CMakeFiles\CMakeTmp\cmTC_7e4fc.vcxproj]

**Comment by COM8** [comment]
You are not recursively cloning the repo. So curl is missing.
**Try:**
```Bash
$ cd cpr
$ git submodule update --init --recursive
```
**Reference:**
https://github.com/whoshuu/cpr#usage

**Comment by wcmiracle** [comment]
My problem is solved, thank you very much

**Comment by COM8** [comment]
You are welcome.
