### ISSUE TITLE
when making cookie, don't url encode

### ISSUE THREAD

**Issue by penguin2233** [whoshuu/cpr#369]
hi, I've noticed when making cookies the library will url encode (as stated in the documentation) but for my application I need to have the cookie value not url encoded. Is there anyway to send the cookie without url encoding?

**Comment by COM8** [comment]
I will have a look at this later today.

**Comment by COM8** [comment]
OK. I had a look at [RFC6265](https://www.ietf.org/rfc/rfc6265.txt) and found the following:
```
[...]
To maximize compatibility with user agents, servers that wish to
store arbitrary data in a cookie-value SHOULD encode that data, for
example, using Base64 [RFC4648].
[...]
```

So it is **recommended** but not mandatory to encode cookies.
I will add an option to disable cookie encoding.
