### ISSUE TITLE
POST Requests with raw post data

### ISSUE THREAD

**Issue by niklas88** [whoshuu/cpr#37]
Maybe I'm missing something but I couldn't find a way to do a post request with a custom content-type and raw body which is needed for many REST APIs that expect e.g. JSON in a POST body.

**Comment by whoshuu** [comment]
You're actually right, there's no way to upload raw data with POST/PUT/PATCH. This is an oversight, I'll have to get this down in 1.2, but it'll be pretty high priority. In the meantime, there is a way to set the content-type, but it requires you to go through the header. You have to add a `Header{{"content-type"}, {"application/json"}}` to your request call.

While we're on the subject, what are your thoughts on providing a json library (I'm thinking Niels Lohmann's [library](https://github.com/nlohmann/json))? This would let me do things like accept a `Json` object and set the header automatically.

**Comment by whoshuu** [comment]
For now, I'm going to limit the scope of this to just providing an API for setting a raw data type for a request.

**Comment by niklas88** [comment]
I personally think that adding json is out of the scope of a HTTP library. Honestly I'm a big fan of the HTTP package of Go https://golang.org/pkg/net/http/ and that's also pretty clear on staying in the HTTP realm.

Also when cpr supports raw bodys either with it's own Body type or directly as string (this should probably be kept in sync with response.text / response.body) using json with it is absolutely trivial so the gain in my opinion isn't too big.
