### ISSUE TITLE
multi perform

### ISSUE THREAD

**Issue by SZNero** [whoshuu/cpr#371]
is there a imp for multi perform? so that i can receive data async?

**Comment by COM8** [comment]
I don't know exactly what you mean with "multi perform", but it is possible to request data asynchronously.
You can find some example here:
* https://github.com/whoshuu/cpr/blob/master/test/async_tests.cpp
* https://whoshuu.github.io/cpr/advanced-usage.html#asynchronous-requests

**Comment by SZNero** [comment]
> I don't know exactly what you mean with "multi perform", but it is possible to request data asynchronously.
> You can find some example here:
> 
> * https://github.com/whoshuu/cpr/blob/master/test/async_tests.cpp
> * https://whoshuu.github.io/cpr/advanced-usage.html#asynchronous-requests

sorry for the bad description of my issue. my question is that if i POST a request and the remote server will send some big data for me. so it will separate to small parts and send to me.In this situation what can i do to receive every single data ?
