### ISSUE TITLE
OpenSSL linker error while compiling in Arch Linux

### ISSUE THREAD

**Issue by neel** [whoshuu/cpr#373]
I am using system `curl`.

```
SET(USE_SYSTEM_CURL ON CACHE INTERNAL "")
SET(BUILD_CPR_TESTS OFF CACHE INTERNAL "")
SET(CMAKE_USE_OPENSSL OFF CACHE INTERNAL "")
add_subdirectory(cpr)
```

And getting linker issues on arch linuc. The openssl package is installed. Reinstalled multiple times. The issue persists.

> /usr/bin/ld: /usr/bin/libcurl.a(openssl.c.o): undefined reference to symbol 'SSL_write@@OPENSSL_1_1_0'
> /usr/bin/ld: /usr/lib/libssl.so.1.1: error adding symbols: DSO missing from command line
> collect2: error: ld returned 1 exit status

**Comment by COM8** [comment]
Ping @kingkili

**Comment by KingKili** [comment]
I think the variables are not changed because there is no force keyword.
Can you please try:
```
SET(USE_SYSTEM_CURL ON CACHE INTERNAL "" FORCE)
SET(BUILD_CPR_TESTS OFF CACHE INTERNAL "" FORCE)
SET(CMAKE_USE_OPENSSL OFF CACHE INTERNAL "" FORCE)
add_subdirectory(cpr)
```

**Comment by neel** [comment]
The issue is resolved without using `FORCE`. I needed to link with `OpenSSL`.
