### ISSUE TITLE
Adding cpr to makefile

### ISSUE THREAD

**Issue by Francisobiagwu** [whoshuu/cpr#376]
I have program and I created a class that will utilize the cpr library. On top of the class, I included <cpr/cpr.h> . I have equally followed the instruction outlined in the readme of this github. I was able to cmake, make and carry out sudo make install commands. Please, how can I add this library to my makefile?

#include <cpr/cpr.h>

std::string const url = "http://192.168.0.1/virb";
std::string query = "command: status";

std::cout<<"about to get a response"<<std::endl;
auto response = cpr::Post(cpr::Url{url},
                                                cpr::Body{query},
                                                cpr::Header{{"Content-Type", "text/plain"}});

std::cout<<response.text<<std::endl;

**Comment by COM8** [comment]
Ping @kingkili.

**Comment by KingKili** [comment]
The compile command should be something like this `g++ file.cpp -lcpr -lcurl`
If it does not work you probably have to tweak the command with the include command (-I)
and the link include directory (-L).

(Don't forget to include iostream, and put your code in a function 😜)

**Comment by COM8** [comment]
Closing this, since one month of inactivity.
Feel free to reopen in case this is still a problem.
