### ISSUE TITLE
Drop support for ancient CMake version

### ISSUE THREAD

**Issue by KingKili** [whoshuu/cpr#378]
I want to start a discussion to switch to a more recent CMake version.
Currently, cpr requires 2.8 which is 7 years old, and is  even removed from the docs.
Also switching to a more recent version would allow us to replace git submodules with
[fetch-content](https://cmake.org/cmake/help/v3.15/module/FetchContent.html).
If there is an interest, I am willing to redo the CMake scripts.

**Comment by COM8** [comment]
Sounds like a really good idea.
Are you willing to create a PR for this?

This is related to #353 .

**Comment by KingKili** [comment]
Yes I can do it
