### ISSUE TITLE
An assertion occurred when execute urlencode method to encode Chinese characters(the char number is negative)

### ISSUE THREAD

**Issue by Doeca** [whoshuu/cpr#379]
Expression: c>=-1 && c<=255
![image](https://user-images.githubusercontent.com/20863202/82124991-77164d80-97d5-11ea-821e-d8e2b2803edc.png)

**Comment by COM8** [comment]
Which character/string would you like to encode?
Could you please provide a minimal example?

**Comment by Doeca** [comment]
> Which character/string would you like to encode?
> Could you please provide a minimal example?

Like "一二三"

**Comment by Doeca** [comment]
> Which character/string would you like to encode?
> Could you please provide a minimal example?

By the way, there is another messagebox
![image](https://user-images.githubusercontent.com/20863202/82125167-c3ae5880-97d6-11ea-8cf8-f5c2afde4d0b.png)

**Comment by COM8** [comment]
Could it be, that there is something wrong with your encoding?
When I run the following example, I do not get any errors.
```C++
#include <stdio.h>
#include <string>
#include <ctype.h>

int main()
{
    std::string value = "一二三";
        for (auto i = value.cbegin(), n = value.cend(); i != n; ++i) {
        std::string::value_type c = (*i);
        // Keep alphanumeric and other accepted characters intact
        if (std::isalnum(c) || c == '-' || c == '_' || c == '.' || c == '~') {
            continue;
        }
    }
    return 0;
}
```

Could you please provide a minimal project?

**Comment by Doeca** [comment]
> Could it be, that there is something wrong with your encoding?
> When I run the following example, I do not get any errors.
> 
> ```c++
> #include <stdio.h>
> #include <string>
> #include <ctype.h>
> #include <iostream>
> 
> int main()
> {
>     std::string value = "一二三";
>         for (auto i = value.cbegin(), n = value.cend(); i != n; ++i) {
>         std::string::value_type c = (*i);
>         // Keep alphanumeric and other accepted characters intact
>         if (std::isalnum(c) || c == '-' || c == '_' || c == '.' || c == '~') {
>             std::cout << c;
>         }
>         std::cout << c;
>     }
>     return 0;
> }
> ```
> 
> Could you please provide a minimal project?

When I run your code
![image](https://user-images.githubusercontent.com/20863202/82125475-bbefb380-97d8-11ea-9413-0a0eabbafb16.png)

I guess it is because visual c++ , its ctype.h:
![image](https://user-images.githubusercontent.com/20863202/82125508-f6595080-97d8-11ea-874c-f0343a35bed3.png)

**Comment by COM8** [comment]
Yes, this could be the problem.
I was using [onlineGDB](https://www.onlinegdb.com/) for testing.
I will have a look at it, what I can do.

**Comment by COM8** [comment]
https://onlinegdb.com/H11R0cTqI

**Comment by Doeca** [comment]
Maybe the parameter of function 'isalnum' should be converted to unsigned char ,but as I use cpr by vcpkg so I can't modify the files directly which means I can't give you a test result.

**Comment by Doeca** [comment]
![image](https://user-images.githubusercontent.com/20863202/82128104-02e6a480-97eb-11ea-9720-b91c8a3000fa.png)
I created another function which is safe to use.
Additionally, without the type convertion it can not run correctly.
I guess it's the problem.

**Comment by COM8** [comment]
I found an even better solution:
```C++
static CURL* curl = curl_easy_init();
assert(curl);
char* output = curl_easy_escape(curl, "data to convert", 15);
assert(output);

std::string result = output;
curl_free(output);
return result;
```
Still missing a bit of cleanup code but I think we should switch to this.
