### ISSUE TITLE
Cannot generate lib\Debug\cpr.lib file - Windows builds broken

### ISSUE THREAD

**Issue by leolong1983** [whoshuu/cpr#391]
Hi, I'm new to CMake and also cpr. It took quite some time for me to figure out how to compile my project along with cpr subdirectory
Now I managed to eliminate compile error to only 1:
 LINK1104  Unable to open file "lib\Debug\cpr.lib"

Here's how I built this project:
1) Wrote my VS C++ project with CMake to "Configure" and "Generate", made sure it work with hello world printed on screen.
2) At root repo level of my c++ project, ran below command and it finished properly
  git submodule add git@github.com:whoshuu/cpr.git
3) I CANNOT get below command work because desperate network connectivity -- Always time out even if I used global VPN.
  git submodule update --init --recursive
4) Trying to make things work, I downloaded branches curl @ b81e0b0 / googletest @ 703bd9c / mongoose @ 359060a directly from git, unzip and placed them to my local project in below di`
   [My_Proj_DIR]/cpr/opt/curl
   [My_Proj_DIR]/cpr/opt/googletest
   [My_Proj_DIR]/cpr/opt/mongoose/mongoose
5) CMake Configure, un-ticked BUILD_CPR_TESTS (it led to 35 other LINK errors if ticked), generate
6) Re-built solution
7) The last 1 error came out. I've checked the located -- no cpr.lib existed at all.
LINK1104  Unable to open file "lib\Debug\cpr.lib"

PS: I noticed other lib files can be generated, like mongoose.lib & mongoose.dll.  But not cpr.lib

Any kind hint will be appreciated

**Comment by COM8** [comment]
Windows builds are currently broken in `master`.
This will hopefully be fixed with #383 .

Please try the latest release:
```
git checkout 1.4.0
```

**Comment by leolong1983** [comment]
> Windows builds are currently broken in `master`.
> This will hopefully be fixed with #383 .
> 
> Please try the latest release:
> 
> ```
> git checkout 1.4.0
> ```

Thanks a lot for your prompt reply!
I'm trying 1.4.0 now and will revisit here some time later

**Comment by leolong1983** [comment]
I used 1.4.0 and got the same lnk1104 error for "lib\Debug\cpr.lib"

Here's what I've done:
1. move [My_Proj_DIR]/cpr out of repo
2. unzip cpr-1.4.0.zip, name it to "cpr" and as a sub-directory of [My_Proj_DIR]
3. As 1.4.0 doesn't contain actual files within /cpr/opt, so I copied previously downloaded sub-projects to
  [My_Proj_DIR]/cpr/opt/curl
  [My_Proj_DIR]/cpr/opt/googletest
  [My_Proj_DIR]/cpr/opt/mongoose/mongoose
4. CMake "configure" and "generate"
5. In VS C++, click reload-all in prompt-up window. 
6. Re-built solution
7. Same LNK error

I'm using VS 2019 which is of C++15 compiler. 
anything I missed?

**Comment by COM8** [comment]
Arg...
Looks fine to me.
Could you please try it again with:
```
git checkout 1.3.0
```

**Comment by KingKili** [comment]
No you are not missing anything Windows requires boilerplate for dlls which cpr does not provide in the moment. It will be is already fixed with #383.
