### ISSUE TITLE
curl_easy_escape produces lower-cased encoded characters

### ISSUE THREAD

**Issue by bit-mask** [whoshuu/cpr#394]
For example, a colon `:` seems to be converted to `%3a` instead of `%3A`. While it may be technically correct, the latter form is much more commonly used.

Some weird web API may even implicitly require the latter form. As a hacky workaround, I have to string-replace Parameters' content.

It'd be ideal to add an option somewhere for this, or just use the upper case form by default.

**Comment by COM8** [comment]
On `master` this has been fixed by: 7e4a803fff0787b8a961527016f1060373a7ce64
