### ISSUE TITLE
Build broke in aa6132 when using system CURL

### ISSUE THREAD

**Issue by audaki** [whoshuu/cpr#395]
Heya cpr maintainers,

our build broke in commit https://github.com/whoshuu/cpr/commit/aa6132278e623739d3c0520564edfc77b35e7bbd

Since that commit CMake is trying to use CURL::libcurl but without doing a FindCURL beforehand. Our build broke in openSUSE Tumbleweed and Leap. It should be fixable by using https://cmake.org/cmake/help/latest/module/FindCURL.html beforehand.

kind regards, Kira

**Comment by COM8** [comment]
Ping @kingkili.

**Comment by KingKili** [comment]
You are right, but I think it would be smarter to just do the dependency logic in the root `CMakeLists.txt`. But I will prepare a quick fix.
