### ISSUE TITLE
libcpr.a is no longer installed in master

### ISSUE THREAD

**Issue by audaki** [whoshuu/cpr#398]
Heya cpr maintainers yet again,

I found another issue:

![image](https://user-images.githubusercontent.com/1321285/84161459-9704fe00-aa6f-11ea-8b1c-cabc1b2d8b29.png)

libcpr.a is built but no longer installed. Is this intentional, do I need a CMake flag or is this a bug? :-)

PS: Thanks for the fast issue handling and great library!

kind regards, Kira

**Comment by KingKili** [comment]
You are right that is not intended, I will have a look into it
