### ISSUE TITLE
Access violation when reading at position 0x01610000

### ISSUE THREAD

**Issue by DeerMaximum** [whoshuu/cpr#400]
Hey, I get an access violation on a simple Post request. Do you know how I can fix this error?

My Code: 
```c++
#include <cpr/cpr.h>
cpr::Payload load = cpr::Payload{ {"email",""} ,{"password",""} ,{"devicetoken",""} };
cpr::Response r = cpr::Post(cpr::Url{ "http://localhost:3000/account/login" }, cpr::Timeout{ 10000 }, load);
cout << r.text << endl;
cout << r.status_code << endl; 
```
CMakeLists.txt:
```
cmake_minimum_required (VERSION 3.8)

project ("CMakeProject1")
set(BUILD_CPR_TESTS OFF)

set (CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
set (CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})

add_subdirectory(cpr)

add_executable (CMakeProject1 "CMakeProject1.cpp" "CMakeProject1.h")

target_include_directories(CMakeProject1 PRIVATE ${CPR_INCLUDE_DIRS})
target_link_libraries(CMakeProject1 PRIVATE ${CPR_LIBRARIES})
```
Error message:
```
Ausnahme ausgelöst bei 0x7B6A369E (vcruntime140d.dll) in CMakeProject1.exe: 0xC0000005: Zugriffsverletzung beim Lesen an Position 0x01540000.
```

**Comment by COM8** [comment]
What version of CPR are you using (1.4 or master or ...)?

It looks to me as you are using an older version since you are still using:

target_include_directories(CMakeProject1 PRIVATE ${CPR_INCLUDE_DIRS})
target_link_libraries(CMakeProject1 PRIVATE ${CPR_LIBRARIES})
‘‘‘

Instead of the new fetch_content approach.

**Comment by DeerMaximum** [comment]
I used the master version. 
I tried the fetch_content approach and the error still exists.

**Comment by DeerMaximum** [comment]
I tried a little bit around and found out that the error only occurs when I use the payload in the request. Is there a workaround for this.

**Comment by COM8** [comment]
Running the following unit test on Linux works.
![image](https://user-images.githubusercontent.com/11741404/85233748-0f24d980-b409-11ea-944b-30f11cd040da.png)
I will have a look how the situation is on Windows.

**Comment by COM8** [comment]
It's running like a charm on Windows.
https://github.com/whoshuu/cpr/runs/795737211

I'm unable to reproduce this error.
Could you please provide a minimal project?

**Comment by DeerMaximum** [comment]
With CPR 1.5.0 the error no longer occurs.

**Comment by COM8** [comment]
Glad to hear :+1: .
