### ISSUE TITLE
CMAKE stucked here.

### ISSUE THREAD

**Issue by SollyTaylor** [whoshuu/cpr#406]
![image](https://user-images.githubusercontent.com/11702186/85723453-d85f0400-b725-11ea-85cf-561a84621b54.png)

Windows 10 system, default CMAKE procedure using default settings.

**Comment by dilshodm** [comment]
Most likely it's downloading libcurl and gtest. After a while it has to continue

**Comment by COM8** [comment]
I agree @dilshodm.
Nevertheless I think we should add a line of CMake output to inform users, it's downloading `CURL`, `gtest` or `mongose`.
Ping @KingKili.

**Comment by KingKili** [comment]
We may also use the [git_progress](https://cmake.org/cmake/help/latest/module/ExternalProject.html?highlight=git_progress) option for that.
