### ISSUE TITLE
compile error in openssl

### ISSUE THREAD

**Issue by wuzhidefeng** [whoshuu/cpr#417]
when I build my project,it remind:
![image](https://user-images.githubusercontent.com/39819358/86730023-abcdb500-c060-11ea-8d24-0327143134dc.png)

how can i resole it.

**Comment by COM8** [comment]
Looks to me like OpenSSL is not installed correctly.

But for further help I need the following information:
* Which OS are you using (looks to me like UNIX based?)
* Which version of CPR are you using
* How did you use CPR (fetch content/git submodule/vcpkg/...)
* Please provide a minimal example so I can reproduce this behaviour

**Comment by wuzhidefeng** [comment]
> Looks to me like OpenSSL is not installed correctly.
> 
> But for further help I need the following information:
> 
> * Which OS are you using (looks to me like UNIX based?)
> * Which version of CPR are you using
> * How did you use CPR (fetch content/git submodule/vcpkg/...)
> * Please provide a minimal example so I can reproduce this behaviour


>*my env:ubuntu16
>*CPR version:cpr-1.5.0
>*use:becaues my cmake version is lower than 3.14,so I use the vcpkg to build cpr like :
![image](https://user-images.githubusercontent.com/39819358/86742895-0966ff00-c06b-11ea-911c-a72e59a76921.png)


>*my openssl version:OpenSSL 1.0.2g
![image](https://user-images.githubusercontent.com/39819358/86742693-e1779b80-c06a-11ea-9b73-3595c35ead30.png)

>*my code:
![image](https://user-images.githubusercontent.com/39819358/86742603-d290e900-c06a-11ea-9b51-2cc73e802fd4.png)

>*my cmakelist:(build a so for other moudle)
![image](https://user-images.githubusercontent.com/39819358/86743195-4af7aa00-c06b-11ea-9e7e-3e2649ca8199.png)

**Comment by COM8** [comment]
Could you please package your small example project and upload it here on GitHub for me to be able to play around with it.

**Comment by wuzhidefeng** [comment]
> Could you please package your small example project and upload it here on GitHub for me to be able to play around with it.

Here is the project.But maybe you cannot reproduce this error in your environment.
[cpr-test.zip](https://github.com/whoshuu/cpr/files/4896701/cpr-test.zip)

**Comment by KingKili** [comment]
I think this problem is related to vcpkg, can please create an issue there.

**Comment by COM8** [comment]
Closing it for now.
Feel free to reopen in case this issue still persists.

**Comment by innerNULL** [comment]
> I think this problem is related to vcpkg, can please create an issue there.

so did you finally solved this problem?
