### ISSUE TITLE
Use develop/master branching model

### ISSUE THREAD

**Issue by whoshuu** [whoshuu/cpr#42]
Currently master is a snapshot of the most recent official release, and `release/x.x` branches are where the most recent development work happens. This isn't ideal because the release branch should be feature stable as bugs are ironed out, and development shouldn't be halted just because a release is taking time to complete.

**Comment by smiley** [comment]
I think flipping the two is ideal: `master` should be a workable, worked-on branch, while `stable` should point to the latest stable release, or point in time if that's doable. (Between releases)

**Comment by whoshuu** [comment]
Just looked through how python requests does it, they just use a master branch for the development branch and tags for all of the releases. That's probably the easiest thing to do, so I'll just go with that.
