### ISSUE TITLE
How can i use cpr in my pro without lots of test example?

### ISSUE THREAD

**Issue by wuzhidefeng** [whoshuu/cpr#422]
I want to use cpr in my project,I add the following code in my cmakelist:
![image](https://user-images.githubusercontent.com/39819358/87537220-de188b80-c6cc-11ea-96ae-f64a93b9b38b.png)
when I build my project,I just want to build my own project,but lots of example of cpr will be compiled.How can I avoid this?
![image](https://user-images.githubusercontent.com/39819358/87537480-423b4f80-c6cd-11ea-9d3b-c015c835c31f.png)

**Comment by COM8** [comment]
You can disable building tests by setting `BUILD_CPR_TESTS` to `OFF`.
For reference:
https://github.com/whoshuu/cpr/blob/5e87cb5f45ac99858f0286dc1c35a6cd27c3bcb9/CMakeLists.txt#L30-L41
