### ISSUE TITLE
Why the use of const rvalues?

### ISSUE THREAD

**Issue by mikedld** [whoshuu/cpr#424]
Looking at the code, there's a number of places where `const T&&` parameters are being used. This strikes me as odd (why would you want an rvalue to be const if you want to move it? either pass `const T&` or `T&&` or `T` or any combination of those), and also leads to compilation failures in an [I would assume] ordinary code such as e.g.

```cpp
void C::f(const std::string& authUsername, const std::string& authPassword) {
    cpr::Get(cpr::Url{"..."}, cpr::Authentication{authUsername, authPassword});
}
```

forcing one to make [odd] changes to their code to accomodate the library, which shouldn't be necessary.

See also: https://codesynthesis.com/~boris/blog/2012/07/24/const-rvalue-references/

**Comment by COM8** [comment]
Thanks for reporting. Those were some old artefacts.

**Comment by mikedld** [comment]
@COM8, sorry but this isn't fixed in full. I'm still unable to use the API the way described above. Getting the following error with GCC 10.1 (although I'm storing values as `const` class members, not passing them as `const&` method arguments, but the issue is still the same --- one cannot pass `const` value as a `&&` parameter):
```
.../MyClient.cpp: In member function 'virtual std::string MyClient::MyRequest(const string&, const string&) const':
.../MyClient.cpp:85:33: error: cannot bind rvalue reference of type 'std::string&&' {aka 'std::__cxx11::basic_string<char>&&'} to lvalue of type 'const string' {aka 'const std::__cxx11::basic_string<char>'}
   85 |             cpr::Authentication(m_basicAuthUsername, m_basicAuthPassword),
      |                                 ^~~~~~~~~~~~~~~~~~~
In file included from /usr/local/include/cpr/api.h:10,
                 from /usr/local/include/cpr/cpr.h:4,
                 from .../MyClient.cpp:7:
/usr/local/include/cpr/auth.h:12:34: note:   initializing argument 1 of 'cpr::Authentication::Authentication(std::string&&, std::string&&)'
   12 |     Authentication(std::string&& username, std::string&& password)
      |                    ~~~~~~~~~~~~~~^~~~~~~~
```

Not saying that the issue is with `cpr::Authentication` only, I guess other places need fixing as well to support both move and non-move cases.

**Comment by COM8** [comment]
Which version of `CPR`are you using?
With #425 a couple of changes to `cpr::Authentication` were introduced.

**Comment by mikedld** [comment]
I've applied changes from 9a4e94d6cb4ce769f4c3e1e8ede4c4edbe3806ea to 1.5.1, didn't try current master yet.

**Comment by mikedld** [comment]
I see that #425 indeed fixes at least `cpr::Authentication`. Sorry for the noise ;)

**Comment by COM8** [comment]
Glad to hear :D
