### ISSUE TITLE
Multiple thread HTTP POST

### ISSUE THREAD

**Issue by antibioticTR** [whoshuu/cpr#430]
Hello, When I tried to HTTP POST with multiple threads after a time program crashes, how can I handle this problem?

**Comment by COM8** [comment]
Thanks for reporting this crash.
Could you please provide a bit more context?
* Which version CPR are you using?
* Does it always happen in a deterministic manner?
* Please provide a small sample project or [unit test](https://github.com/whoshuu/cpr/blob/master/test/post_tests.cpp), so we can reproduce and fix the issue.

**Comment by COM8** [comment]
Closing it for now.
Feel free to reopen in case this issue still persists.
