### ISSUE TITLE
Latest version of cpr on Vcpkg

### ISSUE THREAD

**Issue by MFMokbel** [whoshuu/cpr#442]
Could you please push latest version of **cpr** to Vcpkg. Only version 1.3 is currently supported by Vcpkg.

**Comment by COM8** [comment]
> The cpr port in vcpkg is kept up to date by Microsoft team members and community contributors.
Source: https://github.com/whoshuu/cpr#building-cpr---using-vcpkg

We are not maintaining the `vcpkg` build of cpr.
Please create a PR here: https://github.com/Microsoft/vcpkg

**Comment by MFMokbel** [comment]
Thank you, will do that!
