### ISSUE TITLE
cpr::Post wrong content length

### ISSUE THREAD

**Issue by COM8** [whoshuu/cpr#450]
I have a similar question. Here's the code I wrote. Run it, I found some problems by Wireshark. `Content-Length` is 240518168632, and `Expect` is 100-continue. Please help me, thanks.

```c++
std::string body = "{\"RegisterObject\": {\"DeviceID\": \"65010000005030000001\"}}";
auto response    = cpr::Post(cpr::Url{"http://10.10.10.235:14000/VIID/System/Register"},
                               cpr::Header{{"Content-Type", "application/json"}}, cpr::Body{body},
                               cpr::ConnectTimeout{3000}, cpr::Timeout{3000});
```
![cpr](https://user-images.githubusercontent.com/16732948/93995045-191cf680-fdc3-11ea-8e53-936cfe244b3e.png)

_Originally posted by @bayec in https://github.com/whoshuu/cpr/issues/449#issuecomment-697256619_

**Comment by COM8** [comment]
@bayec, which version of `cpr` are you using?
I remember I have fixed this one early in the development cycle of v1.5.0.
I Also created a quick unit test and to me it looks like its working with the current master build.
```c++
TEST(UrlEncodedPostTests, TimeoutPostTest) {
    Url url{server->GetBaseUrl() + "/json_post.html"};
    std::string body{"{\"RegisterObject\": {\"DeviceID\": \"65010000005030000001\"}}"};
    cpr::Response response =
            cpr::Post(url, cpr::Header{{"Content-Type", "application/json"}}, cpr::Body{body},
                      cpr::ConnectTimeout{3000}, cpr::Timeout{3000});
    std::string expected_text{"{\"RegisterObject\": {\"DeviceID\": \"65010000005030000001\"}}"};
    EXPECT_EQ(expected_text, response.text);
    EXPECT_EQ(url, response.url);
    EXPECT_EQ(std::string{"application/json"}, response.header["content-type"]);
    EXPECT_EQ(201, response.status_code);
    EXPECT_EQ(ErrorCode::OK, response.error.code);
}
```

**Comment by cyanhill** [comment]
@COM8 
I also found this problem, it seems to be caused by CURLOPT_POSTFIELDSIZE_LARGE, modify it to CURLOPT_POSTFIELDSIZE to correctly calculate the json length.

**Comment by COM8** [comment]
AH!
Thanks @cyanhill.
I might have found it.

Setting `CURLOPT_POSTFIELDSIZE_LARGE` requires a value of type `curl_off_t`, which usually is 64 bit. If you pass it a simple `size_t` like `std::string::length()` returns it, it might be a mismatch (32 to 64 bit).
```c++
curl_easy_setopt(CURL *handle, CURLOPT_POSTFIELDSIZE_LARGE, curl_off_t size);
```

**Comment by COM8** [comment]
I've pushed a potential fix for this issue.
Please let me know, if this fixes it.

**Comment by bayec** [comment]
@COM8 @cyanhill 
Solved it! Thank you all.
