### ISSUE TITLE
Post request doesn't work well

### ISSUE THREAD

**Issue by hung1024** [whoshuu/cpr#458]
Hello there,
I try to work with Post (with Body) but it seems fail, (similar command using curl work well with my web api)

curl -XPOST  -H "Content-Type: application/json" -d "{'GUID':'1', 'comm':'ElectricFan' , 'json':'29.80' }" http://localhost:8866/api/Agents/send_command  

auto r = cpr::Post (cpr::Url{ "http://localhost:8866/api/Agents/send_command" },
            cpr::Body { R"({'GUID':'1','comm':'test','json':'14'})" },
            cpr::Header{ { "Content-Type", "application/json" } });
        std::cout << "Returned Status:" << r.status_code << std::endl;

I setup a Fiddle proxy to see what is sending and see that content length is SO LONG
Host: localhost:8866
User-Agent: curl/7.73.0-DEV
Accept: */*
Accept-Encoding: deflate, gzip
Content-Type: text/plain
Content-Length: 76533568435650626

Please help!
Thank and regards

**Comment by COM8** [comment]
What version of `cpr` are you using?
This looks to me like an issue that has been fixed in #450 .

**Comment by hung1024** [comment]
I think it is 1.5.1, as shown with vcpkg bellow (thanks for quick response)
D:\AVMAN2\AgentFunctions\CMakeProject3>D:\AVMAN2\vcpkg\vcpkg.exe list
cpr:x64-windows                                    1.5.1            C++ Requests is a simple wrapper around libcurl ...
cpr:x86-windows                                    1.5.1            C++ Requests is a simple wrapper around libcurl ...
curl:x64-windows                                   7.73.0           A library for transferring data with URLs
curl:x86-windows                                   7.73.0           A library for transferring data with URLs
curl[non-http]:x64-windows                                          Enables protocols beyond HTTP/HTTPS/HTTP2
curl[non-http]:x86-windows                                          Enables protocols beyond HTTP/HTTPS/HTTP2
curl[schannel]:x64-windows                                          SSL support (Secure Channel)
curl[schannel]:x86-windows                                          SSL support (Secure Channel)

**Comment by COM8** [comment]
OK. This issue has been fixed in #450 but there is no new version of cpr in vcpkg available until now. As a workaround I suggest basing your implementation on the latest master with cmake and fetch content.
Is this workaround viable for your project?

**Comment by hung1024** [comment]
I am using Visual studio 2019, windows 10, I am new with C++ so I try download source code zip file from https://github.com/whoshuu/cpr, try compile with Cmake-gui, it shows error, so I am get stuck :D
Post works well with Payload, but I dont know how to catch value "key" in my Web API (MVC) (right now I am using [FromBody])
  
 auto oor = cpr::Post(cpr::Url{ "http://localhost:44332/api/products/1" },
            cpr::Payload{ {"key",  R"({"Id":1,"Name":"ElectricFan","Qty":15,"Price":29.80})"} },
            cpr::Header{ { "Content-Type", "text/plain" } });


MVC code:
[HttpPost]
        public IHttpActionResult send_command([FromBody] Command item)
        {
            if (item == null)
            {
                //return BadRequest();
            }

            //do something here
            item.comm = "test";
            return Ok(item);
        }

**Comment by COM8** [comment]
Arg, ok. Then I guess it's time for a 1.5.2 release since this is a critical bug.
I will try to create a new tag today and start creating a PR on vcpkg.

**Comment by hung1024** [comment]
Great, thanks

**Comment by COM8** [comment]
https://github.com/whoshuu/cpr/releases/tag/1.5.2

**Comment by COM8** [comment]
https://github.com/microsoft/vcpkg/pull/14131
