### ISSUE TITLE
Supporting Tor And Socks5

### ISSUE THREAD

**Issue by s1nisteR** [whoshuu/cpr#461]
#define SOCKS5_PROXY "127.0.0.1:9050"

using namespace std;

int main(int argc, char** argv)
{
    cpr::Response r = cpr::Get(cpr::Url("http://httpbin.org/ip"), cpr::Proxies{{"socks5", SOCKS5_PROXY}});
    sleep(15);
    cout << r.raw_header << endl;
    cout << r.text << endl;
    return 0;
}

Used this code after making sure tor is running on localhost:9050 but it still returns my IP address and not the IP address of a Tor exit node meaning the connection isn't getting routef through tor. What could be the problem and how to fix it?

**Comment by COM8** [comment]
What happens if you add a `socks5://` in front  of your IP (=> `socks5://127.0.0.1:9050`)?

**Comment by COM8** [comment]
Reference: https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html

**Comment by s1nisteR** [comment]
Tried 
#define SOCKS5_PROXY "socks5://127.0.0.1:9050" and even
#define SOCKS5_PROXY "socks5h://127.0.0.1:9050"

Same result, no changes. :(

**Comment by COM8** [comment]
OK. Then I do not know how to fix this.
Is there an easy to use sock5 proxy setup or server out there, you know about?
So I can try to reproduce this issue.

**Comment by COM8** [comment]
What version of `cpr` are you using?

**Comment by s1nisteR** [comment]
> What version of `cpr` are you using?

FetchContent_Declare(cpr GIT_REPOSITORY https://github.com/whoshuu/cpr.git GIT_TAG c8d33915dbd88ad6c92b258869b03aba06587ff9)

So c8d33915dbd88ad6c92b258869b03aba06587ff9

**Comment by s1nisteR** [comment]
> OK. Then I do not know how to fix this.
> Is there an easy to use sock5 proxy setup or server out there, you know about?
> So I can try to reproduce this issue.

You could setup tor easily if you got a linux system.
sudo apt-get install tor
sudo service tor start

It runs on 127.0.0.1:9050 or localhostL9050 by default and uses the SOCKS5 proxy.

**Comment by s1nisteR** [comment]
Fixed it doing this:
#define SOCKS5_PROXY "socks5h://localhost:9050"   //Use socks5h here
cpr::Proxies{{"http", SOCKS5_PROXY}} //but in Proxies part had to use http for some reason.
Used The AsyncResponse and now it all works :D
