### ISSUE TITLE
Failed to compile, undefined reference to `cpr::Session::Get()'

### ISSUE THREAD

**Issue by Criper98** [whoshuu/cpr#467]
hi, i'm tryng to compile a simple GET program with cpr library, i have include the cpr.h file but when i try to compile the program i get this errors:
`undefined reference to `cpr::Session::Get()'
undefined reference to `cpr::Session::~Session()'
undefined reference to `cpr::Session::~Session()'
undefined reference to `cpr::Session::SetOption(cpr::Url const&)'`

i try to link the -lcpr but i get another error:

`cannot find -lcpr`

i'm using MinGW and i really doesn't know how to solv them.

**Comment by COM8** [comment]
Which version of CPR are you using currently?
