### ISSUE TITLE
Unknown CMake command "FetchContent_MakeAvailable"

### ISSUE THREAD

**Issue by philippludwig** [whoshuu/cpr#471]
When I try to add cpr to a project, I get:

```
Unknown CMake command "FetchContent_MakeAvailable"
```

My guess is that the version of CMake shipped with debian (3.13.4) is too old, but I am not sure. It would be nice if the documentation could mention what the minimum required version of CMake is.

**Comment by COM8** [comment]
Based on the official CMake documentation [`FetchContent`](https://cmake.org/cmake/help/git-stage/module/FetchContent.html) got added in `3.11`.

CPR requires `3.15`:
https://github.com/whoshuu/cpr/blob/4f0a0bac4feabc74dee4ef1f634ff0bf5dc7efcc/CMakeLists.txt#L1
