### ISSUE TITLE
Concerns on session.cpp implementation

### ISSUE THREAD

**Issue by GiuseppeCesarano** [whoshuu/cpr#476]
Looking at the source code of [session.cpp](https://github.com/whoshuu/cpr/blob/master/cpr/session.cpp) i noticed that move constructors are manually implemented and no particular behavior is involved, so i would suggest to remove the blank destructor, and allow the compiler to automatically generate those for us. Note that if is decided to keep things the way they are now, those constructors should anyway be declared as `noexcept`. There also others small things, like the usage of iterator based for instead of range based one like in all the other code base and a [call to std::move() on an c_str()](https://github.com/whoshuu/cpr/blob/47cc92045247c429037324cb4eee67ede81c35cf/cpr/session.cpp#L186) which is already trivially copyable type since is a `char*`.

**Comment by COM8** [comment]
Yes, you are right.
I will try to fix it.

**Comment by GiuseppeCesarano** [comment]
Issue closed since 96e33bae7a5282ae5a3cdac22c83499e0848d856 resolve all listed problems
