### ISSUE TITLE
cpr error

### ISSUE THREAD

**Issue by tcpid** [whoshuu/cpr#484]
When I tried to compile with Visual Studio 2019, the following error occurred:
\cpr-master\cpr\ timeout.cpp (19,65): error C2039: "to_ string ": not a member of std.
\cpr-master\cpr\ session.cpp (114,10): error c2280: "CPR:: URL & CPR:: URL:: operator = (const CPR:: URL &) noexcept": attempted to reference a deleted function.

For the first error, I added "include < string > in timeout. h, and then recompilation does not report the first error.
now，I don't know how to solve the second problem。

**Comment by xusai** [comment]
In "cprtypes. h", I try to modify the source code and delete noexcept to compile normally.

    StringHolder(const StringHolder& other) noexcept = default;
    StringHolder(StringHolder&& old) noexcept = default;
    StringHolder& operator=(StringHolder&& old) noexcept = default;
    StringHolder& operator=(const StringHolder& other) noexcept = default;

    Url(const Url& other) noexcept = default;
    Url(Url&& old) noexcept = default;
    ~Url() override = default;

    Url& operator=(Url&& old) noexcept = default;
    Url& operator=(const Url& other) noexcept = default;

The above code is modified as follows:
`StringHolder(const StringHolder& other) = default;
    StringHolder(StringHolder&& old) = default;
    virtual ~StringHolder() = default;

    StringHolder& operator=(StringHolder&& old) = default;
    StringHolder& operator=(const StringHolder& other) = default;

 Url(const Url& other) = default;
    Url(Url&& old) = default;
    ~Url() override = default;

    Url& operator=(Url&& old) = default;
    Url& operator=(const Url& other) = default;
`

**Comment by COM8** [comment]
This has been fixed in: https://github.com/whoshuu/cpr/commit/fe29aee4ca4bfc9d17802e7623c2ee574b1d1e9b and https://github.com/whoshuu/cpr/commit/11591630ed9ab0c7263ea0bd16f595f8cb84d631 .
Please try pulling the latest changes.

**Comment by xusai** [comment]
Thank you. I have been able to compile the library。

I tried to run the demo on the document, and the demo print was always empty。
The code is as follows:
`int main(int argc, char** argv) {
    cpr::Response r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"},
                               cpr::Authentication{"user", "pass"},
                               cpr::Parameters{{"anon", "true"}, {"key", "value"}});
    r.status_code;            // 200
    r.header["content-type"]; // application/json; charset=utf-8
    r.text;                   // JSON text string


    std::cout << r.text << std::endl;
}`

**Comment by xusai** [comment]
[
[Uploading lib.zip…]()

](url)

**Comment by tcpid** [comment]
Thank you. I have been able to compile the library。

I tried to run the demo on the document, and the demo print was always empty。
The code is as follows:
`

int main(int argc, char** argv)
{

cpr::Response r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"},
                           cpr::Authentication{"user", "pass"},
                           cpr::Parameters{{"anon", "true"}, {"key", "value"}});
r.status_code;            // 200
r.header["content-type"]; // application/json; charset=utf-8
r.text;                   // JSON text string


std::cout << r.text << std::endl;
}

`
I used openssl1.1.1h when compiling the CPR library. Is it related to the OpenSSL version?
