### ISSUE TITLE
unable to get local issuer certificate

### ISSUE THREAD

**Issue by tcpid** [whoshuu/cpr#485]
When I was testing in Visual Studio 2019, it returned an error when visiting an HTTPS website：
SSL certificate problem: unable to get local issuer certificate

How to solve this problem？I need your help。

**Comment by COM8** [comment]
How did you install CPR?
In case you build it yourself, try using WINTLS instead of OPENSSL.
```
cmake .. -DUSE_WINSSL=ON -DUSE_OPENSSL=OFF
```

https://github.com/whoshuu/cpr/blob/fe29aee4ca4bfc9d17802e7623c2ee574b1d1e9b/.github/workflows/ci.yml#L134-L154

**Comment by tcpid** [comment]
thinks，I've got the results I want。
