### ISSUE TITLE
cmake build on windows is broken (openssl)

### ISSUE THREAD

**Issue by carre68** [whoshuu/cpr#493]
Hi,

for a cross project i have try out the cmake build ( include(FetchContent) ... )  on windows 10, with the result of unresolved external symbol in openssl build

`LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_CONF_modules_free" in Funktion "_x509_name_oneline".	\out\build\x86-Debug\openssl.c.obj	1
LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_ENGINE_cleanup" in Funktion "_x509_name_oneline".	    \out\build\x86-Debug\openssl.c.obj	1	
LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_ERR_free_strings" in Funktion "_x509_name_oneline".	    \out\build\x86-Debug\openssl.c.obj	1	
LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_EVP_cleanup" in Funktion "_x509_name_oneline".	        \out\build\x86-Debug\openssl.c.obj	1	
LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_EVP_MD_CTX_create" in Funktion "_ossl_connect_common".	\out\build\x86-Debug\openssl.c.obj	1	
.
`

I tried 1.5.0 and 1.5.2
With vcpkg for a other C++ project it is working fine.

Update: The build failed only on x86 build - on x64 it is ok

**Comment by COM8** [comment]
Please try using WINSSL instead of OPENSSL.

https://github.com/whoshuu/cpr/issues/485#issuecomment-736311001

**Comment by carre68** [comment]
Hi,
thanks for fast response, i have CMAKE_USE_OPENSSL and USE_OPENSSL disabled and CMAKE_USE_WINSSL and USE_WINSSL enabled :

`Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_SSLv23_client_method" in Funktion "_mg_ssl_if_conn_init".	\out\build\x86-Debug\lib_cmake	\out\build\x86-Debug\mongoose.lib(mongoose.c.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_SSLv23_client_method" in Funktion "_mg_ssl_if_conn_init".	\out\build\x86-Debug\lib_cmake	\out\build\x86-Debug\mongoose.lib(mongoose.c.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_SSLv23_client_method" in Funktion "_mg_ssl_if_conn_init".	\out\build\x86-Debug\lib_cmake	\out\build\x86-Debug\mongoose.lib(mongoose.c.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_SSLv23_client_method" in Funktion "_mg_ssl_if_conn_init".	\out\build\x86-Debug\lib_cmake	\out\build\x86-Debug\mongoose.lib(mongoose.c.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_SSLv23_server_method" in Funktion "_mg_ssl_if_conn_init".	\out\build\x86-Debug\lib_cmake	\out\build\x86-Debug\mongoose.lib(mongoose.c.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_SSLv23_server_method" in Funktion "_mg_ssl_if_conn_init".	\out\build\x86-Debug\lib_cmake	\out\build\x86-Debug\mongoose.lib(mongoose.c.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_SSLv23_server_method" in Funktion "_mg_ssl_if_conn_init".	\out\build\x86-Debug\lib_cmake	\out\build\x86-Debug\mongoose.lib(mongoose.c.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_SSLv23_server_method" in Funktion "_mg_ssl_if_conn_init".	\out\build\x86-Debug\lib_cmake	\out\build\x86-Debug\mongoose.lib(mongoose.c.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_SSL_library_init" in Funktion "_mg_ssl_if_init".	\out\build\x86-Debug\lib_cmake	\out\build\x86-Debug\mongoose.lib(mongoose.c.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_SSL_library_init" in Funktion "_mg_ssl_if_init".	\out\build\x86-Debug\lib_cmake	\out\build\x86-Debug\mongoose.lib(mongoose.c.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_SSL_library_init" in Funktion "_mg_ssl_if_init".	\out\build\x86-Debug\lib_cmake	\out\build\x86-Debug\mongoose.lib(mongoose.c.obj)	1	
Fehler	LNK2019	Verweis auf nicht aufgelöstes externes Symbol "_SSL_library_init" in Funktion "_mg_ssl_if_init".	\out\build\x86-Debug\lib_cmake	\out\build\x86-Debug\mongoose.lib(mongoose.c.obj)	1	
`

**Comment by COM8** [comment]
@KingKili Do you know anything about that?

**Comment by KingKili** [comment]
It seems to be some problem with mongoose which is only required for testing. I would try setting `BUILD_CPR_TESTS` to false.

**Comment by carre68** [comment]
Hi,

with (for Win10, x86)
disable: CMAKE_USE_OPENSSL, USE_OPENSSL, BUILD_CPR_TESTS  and  
enable: CMAKE_USE_WINSSL, USE_WINSSL

it was successfully compiled! Thanks!

PS: Happy new year 2021!
