### ISSUE TITLE
4 unresolved external symbols?

### ISSUE THREAD

**Issue by ytmcgamer** [whoshuu/cpr#498]
Hello, I have a problem using this library it doesn't matter where I use it in which source code I implement this, I'm getting every time 4 unresolved externals anyone knows how I could possibly fix this error?

```cpp
Build started...
1>------ Build started: Project: Test, Configuration: Release x64 ------
1>cl : command line warning D9025: overriding '/sdl' with '/GS-'
1>dllmain.cpp
1>E:\Downloads\Test\main.cpp(103,33): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
1>E:\Downloads\Test\main.cpp(104,29): warning C4244: '=': conversion from 'double' to 'int', possible loss of data
1>   Creating library E:\Downloads\Test\x64\Release\test.lib and object E:\Downloads\Test\x64\Release\test.exp
1>LINK : warning LNK4098: defaultlib 'LIBCMTD' conflicts with use of other libs; use /NODEFAULTLIB:library
1>dllmain.obj : error LNK2001: unresolved external symbol "public: class cpr::Response __cdecl cpr::Session::Get(void)" (?Get@Session@cpr@@QEAA?AVResponse@2@XZ)
1>dllmain.obj : error LNK2001: unresolved external symbol "public: void __cdecl cpr::Session::SetOption(class cpr::Url const &)" (?SetOption@Session@cpr@@QEAAXAEBVUrl@2@@Z)
1>dllmain.obj : error LNK2001: unresolved external symbol "public: __cdecl cpr::Session::~Session(void)" (??1Session@cpr@@QEAA@XZ)
1>dllmain.obj : error LNK2001: unresolved external symbol "public: __cdecl cpr::Session::Session(void)" (??0Session@cpr@@QEAA@XZ)
1>E:\Downloads\Test\x64\Release\test.exe: fatal error LNK1120: 4 unresolved externals
1>Done building project "Test.vcxproj" -- FAILED.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

And btw thats my code im using
```cpp
CHAR* HWID_RAW;
std::string HWID;
std::string Check;
std::string InputText;
std::string keyy;
HW_PROFILE_INFO hwprofileinfo;
if (GetCurrentHwProfile(&hwprofileinfo)) {
	HWID_RAW = hwprofileinfo.szHwProfileGuid;
	HWID = HWID_RAW;
	HWID = Replace(HWID, "{", "");
	HWID = Replace(HWID, "}", "");
	std::string command_temp = "Start http://185.25.207.217/Start.php?HardwareID=" + HWID;
	const char* command = command_temp.c_str();
	system(command);
	system("cls");
	std::cout << "Please type in your Key : ";
	std::cin >> keyy;
	cpr::Response verifyResponse = cpr::Get(cpr::Url{ "http://127.0.0.1/Verify.php?HardwareID=" + HWID + "&Key=" + keyy }); // this is the error line
}
else
{
	system("color 0c && echo Failure && pause && exit");
}
```

**Comment by Emersont1** [comment]
What's in your Linker Settings?

**Comment by COM8** [comment]
To me this one looks related to https://github.com/whoshuu/cpr/issues/478.

**Comment by ytmcgamer** [comment]
> What's in your Linker Settings?

![image](https://user-images.githubusercontent.com/66328734/104312605-21ff1880-54d7-11eb-857f-a84e89d799e1.png)
![image](https://user-images.githubusercontent.com/66328734/104312642-304d3480-54d7-11eb-92a5-744784fbbcf3.png)
![image](https://user-images.githubusercontent.com/66328734/104312668-3511e880-54d7-11eb-9b50-63a5e1a9b1e5.png)

**Comment by Emersont1** [comment]
You need to add `cpr.lib` to the "additional dependencies" section

**Comment by ytmcgamer** [comment]
where do i find cpr.lib?

**Comment by Emersont1** [comment]
I'm not entirely sure, it depends on how you've downloaded the library. The Specifics of using visual studio isn't my strong point, but basically if you're compiling CPR from source (you downloaded a zip or similar of cpp files) you'll want to add a reference to the project you're building, if you downloaded a dll and some header files, you there should be a `cpr.lib` file in the `/lib` folder next to the `include` folder. If you're using VCPKG, visual studio should handle it for you (i think)

**Comment by Kid0h** [comment]
> where do I find cpr.lib? I'm really new to this sorry like in which folder 

Have you managed to successfully build it as a static library?
If so, did you use vcpkg or just the source code..

**Comment by KingKili** [comment]
> > where do I find cpr.lib? I'm really new to this sorry like in which folder
> 
> Have you managed to successfully build it as a static library?
> If so, did you use vcpkg or just the source code..

I just created CI runs for static builds at least the unit tests seem to work with static linkage.
