### ISSUE TITLE
can't add  #include <cpr/cpr.h> to Arduino ID

### ISSUE THREAD

**Issue by MIIB1** [whoshuu/cpr#503]
Hello
i want add #include <cpr/cpr.h> to Arduino IDE but it say cpr/cpr.h valid library i use windows 10
can you help me ?

**Comment by COM8** [comment]
I guess you mean "invalid" library?
As far as this goes, I'd say there is something wrong with your library configuration.
Please share an example project and instructions for how to setup additional libraries in the Arduino IDE.

**Comment by MIIB1** [comment]
this the code i want add to my arduino nano IoT
`#include <iostream>
#include <string>

#include <iostream>
#include <cpr/cpr.h>

using namespace std;


int main()
{  
    // Update these variable with our sensor value
    int age = 20 ;
    int heart_beat = 20 ;
    int oxygen = 20 ;
    int gender = 1 ;
    
    // Convert int vales as string
    string age_str = to_string(age) ;
    string hb_str = to_string(heart_beat) ;
    string oxy_str = to_string(oxygen) ;
    string gen_str = to_string(gender) ;
    
    string comma = "," ;
    string coln = ":";
    
    // Basic URL
    string URL = "http://x.x.x.x:5000/model/";
    // Develop Main URL for API call
    string final_url = URL+"age"+coln+age_str+comma+"hb"+coln+hb_str+comma+"oxy"+coln+oxy_str+comma+"gen"+coln+gen_str ;
    
    // Calling GET Request using CPR Lib
    auto response = cpr::Get(cpr::Url{final_url});
    std::cout << response.text << std::endl;
    
    
    cout << final_url ;
    
    return 0;
}`

i find this 
https://github.com/whoshuu/cpr
i don't undertand it very will
i download the file from and try add it in anduino but it say 
cpr/cpr.h valid library
can you help ?

**Comment by COM8** [comment]
I don't think this is the way you integrate CPR into an Arduino project.
I've never been using the Arduino IDE my self.

**Comment by MIIB1** [comment]
is there a way to make it work ?
i new to arduino can you help?

**Comment by COM8** [comment]
I don't think, this is how it works if you would like to add something to the Arduino IDE.
I suggest you have a look at how to include external libs into the Arduino IDE and come back here in case you have a concrete question :)

**Comment by MIIB1** [comment]
I know how add external libs into arduino ide i try it with this but not working
