### ISSUE TITLE
build with meson

### ISSUE THREAD

**Issue by frsauvage** [whoshuu/cpr#505]
Hi,

How can I build with meson (without conan neither vcpk)?

Best Regards,
Francine

**Comment by KingKili** [comment]
To my knowledge meson does support CMake subprojects. But there is also a wrap file for [cpr](https://wrapdb.mesonbuild.com/cpr).
Unfortunately I did not use meson very much, and never used wraps. But the process seems to be well [documented](https://mesonbuild.com/Adding-new-projects-to-wrapdb.html).

**Comment by frsauvage** [comment]
Thank a lot, I am trying to adapt with cmake (-;
