### ISSUE TITLE
equivalent for python requests' session.headers.update()

### ISSUE THREAD

**Issue by thirdpartyman** [whoshuu/cpr#506]

**Comment by COM8** [comment]
Please elaborate elaborate your question a little bit.
What exactly does this function in python do?
Link to the documentation, ...

**Comment by stevet11** [comment]
https://requests.readthedocs.io/en/master/user/advanced/#session-objects

It allows for custom headers to be defined and persist across requests.

**Comment by COM8** [comment]
Added support for it:
https://github.com/whoshuu/cpr/blob/8cd9535b929c951b472e8e5a2d25046ae20a989d/test/get_tests.cpp#L404-L450
