### ISSUE TITLE
cpr::Authentication should not required && parameters

### ISSUE THREAD

**Issue by atif1996** [whoshuu/cpr#507]
Love the library overall, but when using it in a project, I noticed that I'm getting compiler issues when I sent in const std::string& parameters down into the Authentication function.  

I see its trying to use std::move, so I tried to copy to std::string to see if it would appease the compiler, alas that doesn't work either.  

Current function signature is (note forwarding references): `Authentication(std::string&& username, std::string&& password)`

This constructor only works when your moving in an rvalue, but I have lvalues, so I need an lvalue overload that would look like:

```Authentication(const std::string& username, const std::string& password)```

However, it appears the best practice on this is to use pass by value for the std::string and then perform a move as follows.  This covers the move case and the const ref case.
```
Authentication(std::string username, std::string password)
     : username_(std::move(username)), password_(std::move(password) {}
```

More from Sutter: https://www.youtube.com/watch?t=54m50s&v=xnqTKD8uD64&feature=youtu.be&ab_channel=CppCon

Error from clang:
```oauth.cpp:49:21: error: no matching constructor for initialization of 'cpr::Authentication'
        auto auth = cpr::Authentication(id, secret);
                    ^                   ~~~~~~~~~~
conan/data/cpr/1.5.2/_/_/package/e7f329b4ec418d8b5cee3c589027eded18933645/include/cpr/auth.h:12:5: note: candidate constructor not viable: no known conversion from 'std::string' (aka 'basic_string<char, char_traits<char>, allocator<char> >') to 'std::string &&' (aka 'basic_string<char, char_traits<char>, allocator<char> > &&') for 1st argument
    Authentication(std::string&& username, std::string&& password)
    ```

**Comment by COM8** [comment]
Hi, thanks for reporting this!

Which version of CPR are you using?
In the current version (master) this behaviour has been fixed already.
It's present in all versions <= 1.5.2
https://github.com/whoshuu/cpr/blob/9a8689e16b224cb9b9b4b5f3cfd4e815501552ea/include/cpr/auth.h#L12-L15

**Comment by atif1996** [comment]
I'm on 1.5.2.  

Ok great, so its already fixed on master.  When is the next release going out to conan :)

**Comment by COM8** [comment]
There is no real schedule for it, but here are a few more information: https://github.com/whoshuu/cpr/issues/510#issuecomment-768062576
