### ISSUE TITLE
Travis builds failing due to clang-3.6 being unavailable

### ISSUE THREAD

**Issue by whoshuu** [whoshuu/cpr#51]
Looks like clang-3.6 isn't being found anymore in the dependencies list:

https://travis-ci.org/whoshuu/cpr/jobs/81851148#L129

**Comment by nabijaczleweli** [comment]
It [looks like](https://github.com/travis-ci/travis-ci/issues/3478) it's a known bug

**Comment by whoshuu** [comment]
I've checked out that issue and I think something else is going on. I've tried rebuilding an unrelated project using travis ci and the same error in this issue pops up.

**Comment by whoshuu** [comment]
Looks like the issue resolved itself. There was something up with the llvm source repositories, even some of the curl commands to get the gpg key were timing out. All good now!
