### ISSUE TITLE
Release v1.5.3

### ISSUE THREAD

**Issue by draveness** [whoshuu/cpr#510]
Can we schedule a new feature or hotfix release?

**Comment by COM8** [comment]
For a v1.5.3 release there are to many changes currently staged for the 1.6 release and backporting (cherry picking) fixes for a "bug fix" release would be too much work.
An alternative could be a pre release version or snapshot for 1.6.

I think this should be the way to go here.
Does anybody know if vcpkg and conan allow pre release packages?
(perhaps @KingKili ?)

**Comment by KingKili** [comment]
I don't think conan would accept a cpr pre-release, since they only accept pre-releases in very few cases.

**Comment by COM8** [comment]
Closing this in preparation for the [`1.6`](https://github.com/whoshuu/cpr/milestone/9) release.
