### ISSUE TITLE
Static compilation for Linux and link into a statically compiled application

### ISSUE THREAD

**Issue by galjs** [whoshuu/cpr#515]
I couldn't find any documentation for linux on how to statically compile CPR. The `cmake` script options do not specify any flags related to this option (from what I see, in Windows there is a `mode` flag for exactly this purpose).

The following problem is of course how to link CPR to my static application.

**Comment by COM8** [comment]
Ping @KingKili .

**Comment by KingKili** [comment]
The build system of cpr uses the `BUILD_SHARED_LIBS` variable in cmake. Therefore, I would try to use something like this for your configuration build `cmake .. -DBUILD_SHARED_LIBS=False`. Does this work?

**Comment by galjs** [comment]
@KingKili yes, it solved my problem, thank you very much!
right now adding `-DCMAKE_CXX_FLAGS=-m32` doesn't work but I'm working on it (I'll probably have to figure out first how to compile OpenSSL, zlib and curl for 32 bit)
