### ISSUE TITLE
ReadCallback will reset Header

### ISSUE THREAD

**Issue by tusooa** [whoshuu/cpr#517]
`cpr::Post(..., header, ReadCallback(...));` will discard `header`, if size is not set, according to https://github.com/whoshuu/cpr/blob/master/cpr/session.cpp#L329 .

Using `cpr::Post(..., ReadCallback(...), header);` will keep `header` but "Transfer-Encoding: chunked" is obviously not kept.

**Comment by COM8** [comment]
Hmmm...
This is a interesting one.
I will have a look at it.

**Comment by COM8** [comment]
Thanks for reporting.
