### ISSUE TITLE
High level scope of library question

### ISSUE THREAD

**Issue by bsenftner** [whoshuu/cpr#518]
My boss just pointed this library out to me. We use another C++ library called Restbed (https://github.com/Corvusoft/restbed) to implement an integrated Internet server within our applications. Restbed only supports Basic & Digest Authentication when one is not using HTTPS under Windows. We want to support additional Authentication schemes, and my boss pointed at this library as a means of supporting more Authentication methods. 

However, from what I can tell this library is for **making requests and not receiving requests**. Is that correct? This library is for creating a programmatic user making requests, and not making software that receives and responds to requests. Correct?

**Comment by COM8** [comment]
Exact. CPR is a simple wrapper around [libcurl](https://curl.se/libcurl/).
We are using [mongoose](https://github.com/cesanta/mongoose) as a server for testing our implementation.
You might want to have a look at it.
