### ISSUE TITLE
Linking CPR without vcpkg?

### ISSUE THREAD

**Issue by pctopgs** [whoshuu/cpr#522]
Hello,
I'm trying to link cpr with vcpkg. As simple as it is, it's buggy sometimes. I submit issues with the vcpkg team, but I'd like to link cpr by just configuring my project properties.

**Comment by COM8** [comment]
This might be because Windows linking is completely broken right now.
We need somebody who knows how to handle Windows linking in CMake.

Closing this in favor of #520
