### ISSUE TITLE
Missing implementation of SetOption(const LimitRate& limit_rate)

### ISSUE THREAD

**Issue by galjs** [whoshuu/cpr#526]
In session.h there's the declaration of this function:
`void SetOption(const LimitRate& limit_rate);`

but it's never implemented in session.cpp, which causes a compilation error when trying to set the limit rate of the session.

I tried to open a pull request but failed to do so, so I I decided to just let you know and add the necessary implementation here:
`void SetOption(const LimitRate& limit_rate) { pimpl_->SetLimitRate(limit_rate); }`

**Comment by COM8** [comment]
Nice catch!
