### ISSUE TITLE
Content-Type getting overwritten?

### ISSUE THREAD

**Issue by acceleratxr** [whoshuu/cpr#532]
I'm experiencing a strange problem where for some requests, not all, if I set the content-type header explicitly it seems to be ignored and overwritten with another.

Example:
```
std::unique_ptr<cpr::Session> session = std::make_unique<cpr::Session>();
session->SetUrl({ url });
session->SetBody({ bodyString });
session->SetHeader({ {"Content-Type", "application/json"} });
cpr::Response response = session->Post();
```

This will produce the following HTTP request (as captured by my proxy).

```
POST http://localhost/path/to/my/resource HTTP/1.1
Host: localhost
User-Agent: curl/7.74.0-DEV
Accept: */*
Accept-Encoding: deflate, gzip
Connection: Keep-Alive
Content-Length: 186
Content-Type: application/x-www-form-urlencoded

{"secret":"33630!9eFc#FeA6(5c87*913a&8731*Ee89&26A9!6c93#C555(8751#6582(BaF","uid":"e854dacc-1cc5-4cc8-9755-2c3af8ec951b"}
```

As you can see the Content-Type is being changed from `application/json` to `application/x-www-form-urlencoded` for some reason.

I would try using the simple API instead of the session object but I have to build the request dynamically including the method type, headers and the body type which doesn't work when the rest of the API uses only initializer_lists. Even if I did though this shouldn't be happening. What am I doing wrong?

**Comment by COM8** [comment]
I've created a test case for your problem and I'm not able to reproduce it (https://github.com/whoshuu/cpr/commit/89a7f2008800825e208995a617134c823d6e22e3).
Could you please try to come up with a more specific test case for this?

Are you sure this is what is being send, or is the server replacing your content-type header?

**Comment by acceleratxr** [comment]
> I've created a test case for your problem and I'm not able to reproduce it ([89a7f20](https://github.com/whoshuu/cpr/commit/89a7f2008800825e208995a617134c823d6e22e3)).
> Could you please try to come up with a more specific test case for this?
> 
> Are you sure this is what is being send, or is the server replacing your content-type header?

It looks like i'm using version 1.5.1 as that's what is currently available in vcpkg HEAD.

I'm definitely sure this is what is being sent to the server as I can confirm its what the server receives before processing with or without the proxy. The proxy isn't configured to make any alterations to headers (i'm using Fiddler).

**Comment by acceleratxr** [comment]
I should note that in my specific test case I am executing 3 requests in succession. The first request is a GET, the second is a POST that succeeds. It's the third request (POST) that fails with the content-type changing as noted above.

**Comment by acceleratxr** [comment]
@COM8 I was able to create a simple test case that reproduces the problem. It's available at the following.

https://gist.github.com/acceleratxr/898791e737e33f796c7709b8eeba036b

**Comment by COM8** [comment]
Instead of:
```c++
session.SetHeader({ {"Content-Type", "application/json"} });
session.SetHeader({ {"Authorization", "jwt " + token} });
```

try:
```c++
session.SetHeader({ {"Content-Type", "application/json"}, {"Authorization", "jwt " + token} });
```
Since every time you call `SetHeader()` it overrides all previously set headers.

**Comment by COM8** [comment]
Btw. Nice demo for this issue. This really helps :)

**Comment by acceleratxr** [comment]
> Instead of:
> 
> ```c++
> session.SetHeader({ {"Content-Type", "application/json"} });
> session.SetHeader({ {"Authorization", "jwt " + token} });
> ```
> 
> try:
> 
> ```c++
> session.SetHeader({ {"Content-Type", "application/json"}, {"Authorization", "jwt " + token} });
> ```
> 
> Since every time you call `SetHeader()` it overrides all previously set headers.

That makes sense but poses another problem. My project actually takes in a vector of additional custom headers that need to be applied. I am currently doing this via
```
for (auto& [key, value] : headerParams)
{
      session->SetHeader({ { key, value } });
}
```

If `SetHeader` always overrides, what is the proper way to build a dynamic list of headers?

**Comment by acceleratxr** [comment]
OK I see now that cpr::Header is actually a map. So this makes perfect sense now. I think I have my problem solved. Thank you!

**Comment by COM8** [comment]
I would suggest passing the header as a `lvalue` and then every time before you perform a request you call `SetHeader` to update it to the latest version.
