### ISSUE TITLE
Avoid recursive template instantiation in priv::set_option()

### ISSUE THREAD

**Issue by jsouquie** [whoshuu/cpr#534]
A small suggestion to avoid recursive template instantiation in priv::set_option(): use the initializer_list trick as below.
Of course, if you intend to restrict the library to C++17, a fold expression would be a more straightforward choice.

```cpp
template <typename... Ts>
void set_option(Session& session, Ts&&... ts) {
    std::initializer_list<int> ignore = { (session.SetOption(std::forward<Ts>(ts)), 0)... };
    (void)ignore;
}
```

**Comment by COM8** [comment]
Thanks for the suggestion!
Could you please explain to me a little bit more what happens here, since I do not get how this solves our problem?

**Comment by jsouquie** [comment]
I found the following posts explaining this technique:
https://articles.emptycrate.com/2016/05/14/folds_in_cpp11_ish.html
https://kubasejdak.com/techniques-of-variadic-templates

**Comment by COM8** [comment]
Aha, OK! Thanks.
Would you like to create a PR for this?
