### ISSUE TITLE
Add support for curl pinned public key (ssl pinning)

### ISSUE THREAD

**Issue by b1scoito** [whoshuu/cpr#535]
With the option `CURLOPT_PINNEDPUBLICKEY` set, more information https://curl.se/libcurl/c/CURLOPT_PINNEDPUBLICKEY.html.

**Comment by COM8** [comment]
Would you like to create a PR for this? Perhaps include it in [`ssl_options.h`](https://github.com/whoshuu/cpr/blob/master/include/cpr/ssl_options.h).
