### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Bdoom** [whoshuu/cpr#536]
How can I install this when I don't use vcpkg or the other tool? Can I just include headers and add them to a folder? I want to implement this in unreal engine, which has it's own build tool.

**Comment by COM8** [comment]
Well, you have multiple options here:
* Copy&Paste all cpp and hpp files into the unreal engines build system and fix imports there.
* Compile cpr as library and point unreal to the header and lib path of cpr
* https://quickturnstudio.com/ue4-cmake-project-boost-integration/
