### ISSUE TITLE
android 64 bit https request don't work response status code 0

### ISSUE THREAD

**Issue by EMHussain** [whoshuu/cpr#538]
```
auto sslOpts  = cpr::Ssl(cpr::ssl::CaPath{"cacert.pem"});
session.SetOption(sslOpts);
cpr::Response response = session.Get();

```
**error** : SSL certificate problem: unable to get local issuer certificate

**Comment by COM8** [comment]
This is probably being caused by `auto sslOpts  = cpr::Ssl(cpr::ssl::CaPath{"cacert.pem"});` and your `cacert.pem` not having a valid cert for the page you want to visit.
What happens if you do not set any SSL options?

Also could you please provide a complete example so I can reproduce this issue?

**Comment by EMHussain** [comment]
if i don't set sslOpt then same error and `cacert.pem` is working with libcurl. 
Here is complete exampe
```
    cpr::Session session{};
    session.SetUrl(cpr::Url{url});

    cpr::Cookies cookies;
    if(!duplexDataId.empty())
    {
        cookies = cpr::Cookies{{"duplexdataiad", duplexDataId}};
       session.SetCookies(cookies);
    }
    #ifdef ANDROID
    auto sslOpts  = cpr::Ssl(cpr::ssl::CaPath{"cacert.pem"});
    session.SetOption(sslOpts);
    #endif // ANDROID

    cpr::Response response = session.Get();
    
    std::cout << response.error.message << std::endl;
    ```

**Comment by COM8** [comment]
What version of CPR are you using?

**Comment by EMHussain** [comment]
version 1.6

**Comment by COM8** [comment]
Could you provide me an example project which I can load with android studio?

**Comment by EMHussain** [comment]
Please see this sample project .[https://github.com/EMHussain/cpr-android](url)

**Comment by EMHussain** [comment]
@COM8 could you see the example project?

**Comment by COM8** [comment]
yes, and I'm currently struggeling getting it build for an emulator

**Comment by EMHussain** [comment]
Worked with 
auto sslOpts  = cpr::Ssl(cpr::ssl::CaInfo{"cacert.pem"});
