### ISSUE TITLE
OpenSSL Question

### ISSUE THREAD

**Issue by tallalnparis4ev** [whoshuu/cpr#546]
Hello, I am a very novice user. I have set cpr's (most recent release of cpr is used) CMake options to:
![image](https://user-images.githubusercontent.com/47358379/114540140-18f42380-9c4d-11eb-8620-c1e88b5ece27.png)

With these options, is it normal to get this error:
![image](https://user-images.githubusercontent.com/47358379/114540283-3b863c80-9c4d-11eb-8f54-80780f9bee76.png)

Is it a must to set OPENSSL_ROOT_DIR? Even if all of cpr's options are set to "OFF"?

**Comment by COM8** [comment]
This is definitely not intended. I will have a look at it.
Thanks for reporting.

**Comment by tallalnparis4ev** [comment]
Thank you very much, maybe it is something to do with me? 
I am using macOS Catalina version 10.15.6

**Comment by COM8** [comment]
Why do you have this line `find_package(OpenSSL REQUIRED)` in your CMakeLists.txt?
CPR handles this internally.

**Comment by tallalnparis4ev** [comment]
Idk, I was getting desperate lol. I removed it, cleared the build, and rebuilt. But I am still getting this:
![image](https://user-images.githubusercontent.com/47358379/114868013-5c859380-9ded-11eb-8deb-469d4db250e6.png)

**Comment by COM8** [comment]
If you do not need HTTPS, please try the following:
```CMake
FetchContent_Declare(cpr GIT_REPOSITORY https://github.com/tallalnparis4ev/cpr.git GIT_TAG stable)
set(CPR_ENABLE_SSL OFF CACHE INTERNAL "" FORCE)
FetchContent_MakeAvailable(cpr)
set(CPR "cpr::cpr")
```

**Comment by COM8** [comment]
Else, you have to fix your OpenSSL installation since automatic detection is not working.

**Comment by tallalnparis4ev** [comment]
Very strange, even with this I am getting the same error.
```CMake
cmake_minimum_required(VERSION 3.15.2)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

project(demo)
add_executable(${CMAKE_PROJECT_NAME} fib.cpp)

#Get cppersist 
include(FetchContent)
FetchContent_Declare(cppersist GIT_REPOSITORY https://github.com/tallalnparis4ev/cppersist GIT_TAG master)
FetchContent_MakeAvailable(cppersist)
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} ${cppersist_SOURCE_DIR}/cppersist/cmake)

#Link threading and filesystem libraries
set(THREADS_PREFER_PTHREAD_FLAG ON)
find_package(Threads REQUIRED)
find_package(Filesystem REQUIRED)

include_directories(${cppersist_SOURCE_DIR})

#Get cpr if needed
if(MONGO)
  FetchContent_Declare(cpr GIT_REPOSITORY https://github.com/tallalnparis4ev/cpr.git GIT_TAG stable)
  set(CPR_ENABLE_SSL OFF CACHE INTERNAL "" FORCE)
  FetchContent_MakeAvailable(cpr)
  set(CPR "cpr::cpr")
endif()
target_link_libraries(${CMAKE_PROJECT_NAME} PRIVATE Threads::Threads std::filesystem ${CPR})
```

**Comment by ollien** [comment]
I'm facing this issue as well, even when just building `cpr` directly. 

```
CMake Error at /usr/local/Cellar/cmake/3.20.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.20.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.20.1/share/cmake/Modules/FindOpenSSL.cmake:570 (find_package_handle_standard_args)
  build/_deps/curl-src/CMakeLists.txt:365 (find_package)
```

I am able to make it work if I manually specify `-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl`, but this implies that `openssl` was installed as Homebrew installs it. This could potentially be fixed if CPR linked against LibreSSL, which macOS includes OOTB. I haven't done serious development on macOS in a while though, so I'm not 100%

**Comment by COM8** [comment]
CPR does not link against OpenSSL.
It only tells curl to use it.
As far as I know curl does not support `LibreSSL`.

**Comment by ollien** [comment]
It looks like curl has support for `darwinssl` built in. Misspoke abotu it being LibreSSL)

https://github.com/curl/curl/blob/6fc805d0c1f82363836f1c6199cebdd3c41cbc5b/CMakeLists.txt#L364-L377
https://everything.curl.dev/source/build/tls

I haven't tested it explicitly, but it looks like it exists

**Comment by COM8** [comment]
Aha!
Yes, curl works with DarwinSSL, but CPR currently does not support it.
I was planing to add support for it, but it's rather annoying without access to a Mac, so ...

**Comment by tallalnparis4ev** [comment]
Hey I made a pull request (#549) implementing what you guys suggested, if I interpreted u both correctly?

It works for me, can you guys see if it's ok?
