### ISSUE TITLE
Is there any way to terminate all TCP connections of a session?

### ISSUE THREAD

**Issue by Sr173** [whoshuu/cpr#547]

**Comment by COM8** [comment]
The only way is to dispose all `cpr::Response` and `cpr::Session` objects since this calls the corresponding curl functions:
https://github.com/whoshuu/cpr/blob/51d9059e1396aff151fd812930bef82f0e527478/cpr/curlholder.cpp#L28-L30

**Comment by Sr173** [comment]
Or is there any way I can turn off keep-alive so that it does not reuse the tcp link, because reusing the tcp link when I use a tunnel proxy will cause the proxy to fail, thanks

**Comment by COM8** [comment]
No currently not.
By default it is enabled.
https://github.com/whoshuu/cpr/blob/51d9059e1396aff151fd812930bef82f0e527478/cpr/session.cpp#L133

But this could be an option in the future.
Would you like to create a PR for that?
