### ISSUE TITLE
Cannot open the cpr library in QT Creator

### ISSUE THREAD

**Issue by YoussofAttallah** [whoshuu/cpr#548]
How can I install the cpr library and make it work on QT Creator, I used it with Visual Studio and its working but I cannot find a way to make it work with QT Creator.

**Comment by COM8** [comment]
Might be related to these: https://github.com/whoshuu/cpr/issues?q=QT

**Comment by YoussofAttallah** [comment]
They dont really help, non of them have a way to include the library in qt

**Comment by COM8** [comment]
But isn't this then an issue that should be asked on the QT side (forum) since we do not provide any QT support here.
I don't know how to use their build system sorry.
