### ISSUE TITLE
Update CURL

### ISSUE THREAD

**Issue by jgsogo** [whoshuu/cpr#55]
I have submitted a PR tu bagder/curl (https://github.com/bagder/curl/pull/488) with the same content as the one submitted to your fork, now I'm testing whoshuu/cpr#master with bagder/curl#master and everything seems to work ok (Win7 64bits MSVC2015).

I've just had to choose in CMake between ```CMAKE_USE_OPENSSL``` and ```CMAKE_USE_SCHANNEL``` because under both macros there is the same definition in ```curl/lib/urldata.h``` ([line#273](https://github.com/bagder/curl/blob/9756d1da7637d1913b7ca2b589e4635f32ed3e00/lib/urldata.h#L273) and [line#322](https://github.com/bagder/curl/blob/9756d1da7637d1913b7ca2b589e4635f32ed3e00/lib/urldata.h#L322))

```
ssl_connect_state connecting_state;
```

Both seems to be "ON" by default... I don't know what the difference is among all the ```USE_XXX``` macros in that file, but I can confirm that last revision works with CPR (I'll try to run all the tests, but my computer crash with them :S)

Update this dependency (after PR merge and tag so install in windows works ok)?

**Comment by whoshuu** [comment]
I've already updated my local curl dependency with your change in https://github.com/whoshuu/cpr/commit/f9a3159d0363670a50cba5331c9405b3f3ef824c. I'll close this issue when the upstream curl repo gets updated, and I point my fork to it. Thanks for the information.

**Comment by jgsogo** [comment]
This issue now depends on this pull-request: https://github.com/bagder/curl/pull/498

**Comment by jgsogo** [comment]
The PR have been merged, It is already available in #master branch and will be shipped with v7.46.0

**Comment by whoshuu** [comment]
Hey @jgsogo, really appreciate the work you've done to push this through. When that version of curl gets shipped and I point my submodule to it, I'll go ahead and close this ticket.

**Comment by jgsogo** [comment]
Thanks @whoshuu

**Comment by whoshuu** [comment]
This can be closed after updating the embedded curl to 7.46.0.
