### ISSUE TITLE
CMake: TRY_RUN() invoked in cross-compiling mode

### ISSUE THREAD

**Issue by NancyLi1013** [whoshuu/cpr#582]
Hi guys,

I'm one of vcpkg maintainers. 

When upgrading `cpr `to the latest version 1.6.2 in vcpkg, it failed with the following errors on `uwp`:

```
-- Performing Test THREAD_SANITIZER_AVAILABLE
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   THREAD_SANITIZER_AVAILABLE_EXITCODE (advanced)
   THREAD_SANITIZER_AVAILABLE_EXITCODE__TRYRUN_OUTPUT (advanced)
For details see D:/buildtrees/cpr/arm-uwp-dbg/TryRunResults.cmake
-- Performing Test THREAD_SANITIZER_AVAILABLE - Failed
-- Performing Test ADDRESS_SANITIZER_AVAILABLE
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   ADDRESS_SANITIZER_AVAILABLE_EXITCODE (advanced)
   ADDRESS_SANITIZER_AVAILABLE_EXITCODE__TRYRUN_OUTPUT (advanced)
For details see D:/buildtrees/cpr/arm-uwp-dbg/TryRunResults.cmake
-- Performing Test ADDRESS_SANITIZER_AVAILABLE - Failed
-- Performing Test LEAK_SANITIZER_AVAILABLE
-- Performing Test LEAK_SANITIZER_AVAILABLE - Failed
-- Performing Test UNDEFINED_BEHAVIOUR_SANITIZER_AVAILABLE
-- Performing Test UNDEFINED_BEHAVIOUR_SANITIZER_AVAILABLE - Failed
-- Performing Test ALL_SANITIZERS_AVAILABLE
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   ALL_SANITIZERS_AVAILABLE_EXITCODE (advanced)
   ALL_SANITIZERS_AVAILABLE_EXITCODE__TRYRUN_OUTPUT (advanced)
For details see D:/buildtrees/cpr/arm-uwp-dbg/TryRunResults.cmake
-- Performing Test ALL_SANITIZERS_AVAILABLE - Failed
```
Can you help me look into this problem? @COM8 

Thanks in advance!

Related PR from vcpkg: https://github.com/microsoft/vcpkg/pull/18386

**Comment by COM8** [comment]
I'd say this is caused by cpr trying to compile a simple program with sanitizers enabled.
https://github.com/whoshuu/cpr/blob/f4622efcb59d84071ae11404ae61bd821c1c344b/cmake/sanitizer.cmake#L11

It looks like in case you want to perform cross-compilation for UWP, this fails.
As a quick and dirty workaround I suggest patching out this line, when building:
https://github.com/whoshuu/cpr/blob/f4622efcb59d84071ae11404ae61bd821c1c344b/CMakeLists.txt#L49

... since the vcpkg packages probably will not need any sanitizers enabled.

For the next release, we should probably find a way to disable those checks for cross-compilation.
@KingKili do you know a way to fix this?

**Comment by NancyLi1013** [comment]
Thanks for your quick response and suggestion. @COM8 

So we can make a patch to comment `include(cmake/sanitizer.cmake) `out in `cpr `1.6.2 now and remove the patch when this is fixed in next release.

**Comment by NancyLi1013** [comment]
`include(cmake/sanitizer.cmake)` is still required on other targets. I add the patch only for `uwp`. Please take this case in consideration for the new fix in next release.

```
CMake Error at CMakeLists.txt:110 (message):
  Invalid build type: Debug
```

**Comment by NancyLi1013** [comment]
Thanks for your fixing @COM8.

**Comment by mhtvsSFrpHdE** [comment]
`THREAD_SANITIZER_AVAILABLE - Failed`, `clang_rt.asan_dbg_dynamic-x86_64.dll` was not found

For people trying to build `1.9.9` and Visual Studio 2019 `16.11.56`, CMake GUI `3.31.7`

Open cmd.exe, run
- `"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64`
- cd to where CMake GUI installed like `C:\CMake\bin`
- `cmake-gui.exe`
- Build as usual
