### ISSUE TITLE
Support set "X-Forwarded-For"?

### ISSUE THREAD

**Issue by jojo0796** [whoshuu/cpr#586]
Is cpr support set "X-Forwarded-For" value in header

**Comment by COM8** [comment]
So you would like to set "X-Forwarded-For" in the header of a request?
In case, yes. How about:
```c++
cpr::Response r = cpr::Get(cpr::Url{"http://www.httpbin.org/headers"},
                  cpr::Header{{"X-Forwarded-For", "YOUR_VALUE"}});
std::cout << r.text << std::endl;
```
https://whoshuu.github.io/cpr/advanced-usage.html#request-headers

**Comment by jojo0796** [comment]
It's OK. Thanks
