### ISSUE TITLE
Upload file with Post

### ISSUE THREAD

**Issue by jojo0796** [whoshuu/cpr#589]
I use cpr::Multipart to upload file. How to limit send data buffer size (chunk size)??

**Comment by COM8** [comment]
How do you construct a `cpr::Multipart` instance?
Since `cpr::Multipart` takes an `std::initializer_list<Part>` which allows you to define the size of your individual parts.

**Comment by jojo0796** [comment]
cpr::Response r = cpr::Post(cpr::Url{ "http://www.httpbin.org/post" },
		cpr::Multipart{ {"Filenam", "test.txt"},
					   {"Filedata", cpr::File{"c:\\test\\test.txt"}, "application/octet-stream"} });

I want to set max chunk buffer size send to server and how to set offset size?

**Comment by jojo0796** [comment]
POST /post HTTP/1.1
Host: www.httpbin.org
User-Agent: curl/7.77.0
Accept: */*
Accept-Encoding: identity
Content-Length: 313
Content-Type: multipart/form-data; boundary=------------------------b2a6bc2a84e00f6d

--------------------------b2a6bc2a84e00f6d
Content-Disposition: form-data; name="Filenam"

test.txt
--------------------------b2a6bc2a84e00f6d
Content-Disposition: form-data; name="Filedata"; filename="test.txt"
Content-Type: application/octet-stream

hello
--------------------------b2a6bc2a84e00f6d--


I use cpr::ProgressCallback([](size_t downloadTotal, size_t downloadNow, size_t uploadTotal, size_t uploadNow) to control upload size, but uploadTotal/uploadNow include all transferred data size not only file size, how can i got file transferred size progress only??
