### ISSUE TITLE
GET requests on github API and raw links return bad host (status code: 0)

### ISSUE THREAD

**Issue by IngCr3at1on** [whoshuu/cpr#59]
This includes the example in the readme documentation.

**Comment by whoshuu** [comment]
Just tried the example in the readme documentation again, and it works just fine. Can you give me a minimal snippet of the request that's bugging out for you?

**Comment by nabijaczleweli** [comment]
@IngCr3at1on OS, `curl` version?

**Comment by IngCr3at1on** [comment]
@whoshuu will have to get that later. @nabijaczleweli this occurs in Arch Linux with curl 7.45

**Comment by vitorhnn** [comment]
I'm having the same issue, but I found out that it happens only if you don't use your system's libcurl and it's just https requests, http works fine. I'm also on Arch Linux with curl 7.45 and OpenSSL 1.0.2.d

**Comment by IngCr3at1on** [comment]
@vitorhnn aye I've noticed it only seems to happen on https also, I forgot to note that in the initial issue. I have the same version of OpenSSL also.

As for a snippet of the request it's literally the same one as the example that I was playing with.

@vitorhnn can you elaborate on what you mean by "don't use your system's libcurl"; more specifically was there something you were able to do to make it work?

**Comment by whoshuu** [comment]
@vitorhnn, I think the issue you're seeing is related to #31, which has yet to be implemented when building the included curl library. It makes sense that your system curl works just fine, since it's correctly using OpenSSL from your system as well. When #31 is implemented, let's circle back on this issue and see if it's resolved.

**Comment by whoshuu** [comment]
@IngCr3at1on, there's an option to either use your system's libcurl or the included one. The option is `USE_SYSTEM_CURL` (found [here](https://github.com/whoshuu/cpr/blob/5f1b59004d31e1158541ba96ddcad5b44194c1fa/CMakeLists.txt#L58-L59)) and by default it's `OFF`. You can turn it on by setting an environment variable (ie, `export USE_SYSTEM_CURL=ON`), or setting a CMake definition `cmake -DUSE_SYSTEM_CURL=ON .. && make`.

Additionally, the option _should_ be exposed in the CMake gui if that's what you're using to configure your project.

**Comment by vitorhnn** [comment]
@IngCr3at1on, set USE_SYSTEM_CURL to ON on your CMakeLists.txt, like [here](https://github.com/whoshuu/cpr-example/blob/master/opt/CMakeLists.txt)

**Comment by IngCr3at1on** [comment]
Alright @whoshuu and @vitorhnn I'll try that out. Assuming it works I'll close this being that #31 already exists. Thanks.

**Comment by nabijaczleweli** [comment]
@IngCr3at1on And?

**Comment by COM8** [comment]
Closing this, since it does not seem to be relevant any more.
