### ISSUE TITLE
Callback function use size_t?

### ISSUE THREAD

**Issue by jojo0796** [whoshuu/cpr#593]
cpr callback function (ex. ProgressCallback), use size_t, if the project build with x86, size_t define as "unsigned int", but the file size need to define with "__int64"

libcurl callback define used as below, is "define CURL_TYPEOF_CURL_OFF_T     __int64"
```c++
#elif defined(_MSC_VER)
#  if (_MSC_VER >= 900) && (_INTEGRAL_MAX_BITS >= 64)
#    define CURL_TYPEOF_CURL_OFF_T     __int64
#    define CURL_FORMAT_CURL_OFF_T     "I64d"
#    define CURL_FORMAT_CURL_OFF_TU    "I64u"
#    define CURL_SUFFIX_CURL_OFF_T     i64
#    define CURL_SUFFIX_CURL_OFF_TU    ui64
#  else
#    define CURL_TYPEOF_CURL_OFF_T     long
#    define CURL_FORMAT_CURL_OFF_T     "ld"
#    define CURL_FORMAT_CURL_OFF_TU    "lu"
#    define CURL_SUFFIX_CURL_OFF_T     L
#    define CURL_SUFFIX_CURL_OFF_TU    UL
#  endif
```

**Comment by COM8** [comment]
That's a bug then I guess :)
thanks for reporting.
I will have a look at it.

Tip: https://guides.github.com/pdfs/markdown-cheatsheet-online.pdf
