### ISSUE TITLE
Getting error CRYPTO_STATIC_MUTEX_lock_write when using aws-sdk-cpp-v2 with http lib cpr (using curl + openssl)

### ISSUE THREAD

**Issue by mayurpatelgec** [whoshuu/cpr#594]
Hi All,

> I dont know if its the right place to post the que here but its due to a lib conflict thats why m posting it here / or can help someone in future and to find some help from community. 

I want to integrate one cpr with my aws-sdk based pub-sub mqtt example

**How I did it (example code)**
- I used our basic-pub-sub mqtt example (https://github.com/aws/aws-iot-device-sdk-cpp-v2/tree/main/samples/mqtt/basic_pub_sub) to start.
- added this small code to test it.
 ```
#include <cpr/cpr.h>
****
****
int test_http {
    cpr::Response r = cpr::Get(cpr::Url{"https://api.github.com/repos/whoshuu/cpr/contributors"},
                      cpr::Authentication{"user", "pass"},
                      cpr::Parameters{{"anon", "true"}, {"key", "value"}});
    r.status_code;                  // 200
    r.header["content-type"];       // application/json; charset=utf-8
    r.text;                         // JSON text string
}
```
- compiled it and linked the lib as described on their website README and it all went smoothly.

**Problem**
- when i run the code without any AWS-SDK code just only CPR lib demo then the code runs fine and work as expected.
- When I run this our above described code (with aws pub-sub example), then it throws a `CRYPTO_STATIC_MUTEX_lock_write` and then it crashes.
- screenshot of gdb trace:
![image](https://user-images.githubusercontent.com/26649420/126276557-bc5231f6-6efd-4c54-b65f-ee71757bdade.png)

**Hints(why this can happen)**
I am not an expert in libcrypto but still m putting my assumptions here
- can be due to multi threaded/mutex problems with curl (because curl does not support it and some threads can be already in use by AWS-SDK)
- conflicts between aws-lc (libcrypto) and libcrypto from cpr lib

**If anyone has hints about solving this problem then please let me know.
Thank you in advance and wish you all a great working day.**

**Comment by COM8** [comment]
I think this one has been solved https://github.com/aws/aws-iot-device-sdk-cpp-v2/issues/301#issuecomment-884493921?
As you suggested I also think this is a clash between different versions of OpenSSL / libcrypto.
Therefore I don't think this is a cpr related issue.
