### ISSUE TITLE
SEC_E_UNTRUSTED_ROOT - socks5 Proxy

### ISSUE THREAD

**Issue by GoekhanDev** [whoshuu/cpr#603]
Hello,

Im trying to do a request with socks proxies but im getting a untrusted cerificate error.

Im getting the error:
> SEC_E_UNTRUSTED_ROOT (0x80090325) - The certificate chain was issued by a non-trusted CA.

Reproduceable example:

```
cpr::Session session;
session.SetProxies({ {"http", "socks5://<ip>:<port>"}, {"https", "socks5://<ip>:<port>"} });
session.SetUrl("https://api.myip.com/");
{
     //cpr::VerifySsl(false); this doesn't work.
     cpr::Response response = session.Get();
}
```

Kind Regards.

**Comment by COM8** [comment]
What version of CPR are you using?

**Comment by GoekhanDev** [comment]
Im using the version `cpr[core]:x86-windows -> 1.6.2`.

**Comment by A91K3C1l** [comment]
How to porting to nim

**Comment by GoekhanDev** [comment]
Having a namspace error even when including <cpr/ssl_options.h>
> name followed by '::' must be a class or namespace name

Installed cpr with vcpkg

**Comment by COM8** [comment]
> Having a namspace error even when including <cpr/ssl_options.h>
> 
> > name followed by '::' must be a class or namespace name
> 
> Installed cpr with vcpkg

Ah, right!
You have to prepend the namespace `cpr` in front of `ssl`.
I've updated my comment.

**Comment by COM8** [comment]
> How to porting to nim

What is "nim"?

**Comment by GoekhanDev** [comment]
> 
> 
> > How to porting to nim
> 
> What is "nim"?

He mostly likely means nim-lang.



> 
> 
> > Having a namspace error even when including <cpr/ssl_options.h>
> > > name followed by '::' must be a class or namespace name
> > 
> > 
> > Installed cpr with vcpkg
> 
> Ah, right!
> You have to prepend the namespace `cpr` in front of `ssl`.
> I've updated my comment.

Thank you works now!
