### ISSUE TITLE
Allow setting network interface (CURLOPT_INTERFACE in curl)

### ISSUE THREAD

**Issue by shmuelnatan** [whoshuu/cpr#606]
I saw that on October 2019 a commit was made to add support for CURLOPT_INTERFACE (here's the link to the issue that was solved https://github.com/whoshuu/cpr/pull/326 ).

But in latest version (v1.6.2) I don't see support for this issue.
Is there a reason that this code was removed? If so, can new code be added to support the CURLOPT_INTERFACE option?
Thanks.

**Comment by COM8** [comment]
As far, as I can see, this PR never made it in.
It got closed by its author: https://github.com/whoshuu/cpr/pull/331

BUT, there currently exists a more or less undocumented way you can access curl directly:
https://github.com/whoshuu/cpr/blob/63bfcc6292bba06f9806994ee5474baadff48254/test/session_tests.cpp#L877-L899
Just make sure you link against curl for this :)
