### ISSUE TITLE
PUT body is lost on 301 redirect

### ISSUE THREAD

**Issue by Chemrat** [whoshuu/cpr#608]
I'm trying to push data into consul via `PUT`. However, if target URL isn't 100% correct, e.g. has dot folder or multiple slashes in a row, consul responds with a `301 Moved Permanently`. When cpr follows the redirect, it resends the request with empty body (no content-length even), which results in clobbering the data. This doesn't seem like a correct behaviour.

Minimum example (needs a server that repsonds with 301 though):
```c++
cpr::Put(cpr::Url{"http://REDACTED:8500/v1/kv//test"}, cpr::Body{"This body is lost"});
```

HTTP dialogue from wireshark:
```
PUT /v1/kv//test HTTP/1.1
Host: REDACTED:8500
User-Agent: curl/7.69.1
Accept: */*
Accept-Encoding: deflate, gzip
Content-Length: 17
Content-Type: application/x-www-form-urlencoded

This body is lostHTTP/1.1 301 Moved Permanently
Location: /v1/kv/test
Date: Tue, 10 Aug 2021 09:27:15 GMT
Content-Length: 0

PUT /v1/kv/test HTTP/1.1
Host: REDACTED:8500
User-Agent: curl/7.69.1
Accept: */*
Accept-Encoding: deflate, gzip

HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Type: application/json
Vary: Accept-Encoding
Date: Tue, 10 Aug 2021 09:27:15 GMT
Content-Length: 28

true
```

This doesn't seem to be the case with command-line curl using `-T -L`, although it seems command-line curl handles it a bit differently in that case. I did not investigate if this is a case with libcurl.

**Comment by COM8** [comment]
Looks like a bug to me. I will have a look at it.
Thanks for reporting!

**Comment by COM8** [comment]
https://everything.curl.dev/http/redirects
