### ISSUE TITLE
Post array

### ISSUE THREAD

**Issue by gravitywolfLaCanneAPeche** [whoshuu/cpr#609]
Hello, is it possible to use array in the payload ?

**Comment by COM8** [comment]
What is your use case?
What would you like to archive?

**Comment by gravitywolfLaCanneAPeche** [comment]
For fun, I try to make a lib for create discord bots, and, I need to use an array in a post request. Example of the payload I need : 
```json
{
  "content": "Hello, World!",
  "tts": false,
  "embeds": [{
    "title": "Hello, Embed!",
    "description": "This is an embedded message."
  }]
}
```

**Comment by COM8** [comment]
OK. To me this looks like you should be looking into just posting JSON with https://github.com/nlohmann/json.

Example:
```c++
nlohmann::json j = nlohmann::json{{"bareJid", "blabla"}, {"password", "secret"}};
std::string jString = j;
cpr::Response r = cpr::Post(cpr::Url{"http://www.httpbin.org/post"}, cpr::Body{jString});
```

There you then can build more complex structures like arrays.

But I'm sure you already knew this, since based on your GitHub profile, you are superior to me...
