### ISSUE TITLE
Userland erorr

### ISSUE THREAD

**Issue by A91K3C1l** [whoshuu/cpr#611]
I installed cmake following the instructions of this web https://askubuntu.com/questions/829310/how-to-upgrade-cmake-in-ubuntu

And I installed cpr following the answers on this web
![Screenshot_2021-08-14-20-17-44-00](https://user-images.githubusercontent.com/59974186/129447697-2c891892-0107-41f1-add0-7e23d432c72f.png)

https://stackoverflow.com/questions/58362204/how-to-use-the-cpr-library-in-c

CMake Error at /opt/cmake-3.21.1-linux-aarch64/share/cmake-3.21/Modules/FetchContent.cmake:1017 (message):
  Build step for curl failed: 2
Call Stack (most recent call first):
  /opt/cmake-3.21.1-linux-aarch64/share/cmake-3.21/Modules/FetchContent.cmake:1146:EVAL:2 (__FetchContent_directPopulate)
  /opt/cmake-3.21.1-linux-aarch64/share/cmake-3.21/Modules/FetchContent.cmake:1146 (cmake_language)
  /opt/cmake-3.21.1-linux-aarch64/share/cmake-3.21/Modules/FetchContent.cmake:1189 (FetchContent_Populate)
  CMakeLists.txt:205 (FetchContent_MakeAvailable)

**Comment by COM8** [comment]
To me looks like the download of curl fails.
Could you provide the `build/CMakeError.log` and `build/CMakeOutput.log`?

**Comment by COM8** [comment]
Closing, since no response.
