### ISSUE TITLE
Can't work on Windows.

### ISSUE THREAD

**Issue by ChungZH** [whoshuu/cpr#623]
------
Here is my [repo](https://github.com/ChungZH/tsl), my [CMakeLists.txt](https://github.com/ChungZH/tsl/blob/main/CMakeLists.txt) and [.cpp](https://github.com/ChungZH/tsl/blob/main/src/main.cpp).
The source:
```cpp
#include <cpr/cpr.h>
int main(int argc, char** argv)
{
    cxxopts::Options options("tsl", "Translate in terminal.");
    options.add_options()("h,help", "Print usage");
    auto result = options.parse(argc, argv);
    const std::vector<std::string> words(result.unmatched());
    cout << "HelloWorld" << endl;
    for (const auto word : words) {
        cpr::Response r = cpr::Get(cpr::Url { "http://fanyi.youdao.com/openapi.do?keyfrom=node-fanyi&key=110811608&type=data&doctype=json&version=1.1&q="+word });
        cout << r.text << endl;
    }
    return 0;
}
```
------
The problem: When I use `cpr::Get()`, the program quit without doing anything. I tried `cout << "HelloWorld" << endl` in **front** of `Get()` but it didn't work.

------

```powershell
❯ mkdir buildTest
❯ cd buildTest
❯ cmake .. -DCMAKE_USE_OPENSSL=OFF -DBUILD_CPR_TESTS=OFF
❯ cmake --build .
```
After that:
```powershell
❯ .\Debug\tsl.exe
❯ .\Debug\tsl.exe -h
❯ .\Debug\tsl.exe STH
```
![image](https://user-images.githubusercontent.com/42088872/131104593-3e1a66ac-239f-4d07-9c45-472a587279df.png)

NOTHINGGGGGG！

**Comment by COM8** [comment]
This is caused by windows not being able to find the required dlls your code depends on.
Add the following to the top level `CMakeLists.txt` and it should do the trick.

````CMake
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR})
```

**Comment by ChungZH** [comment]
Thank you.

**Comment by ChungZH** [comment]
It still does not work on my machine.

commit: https://github.com/ChungZH/tsl/commit/2eab9b92f3de88dd4045073b5836e69e61c665c7

**Comment by COM8** [comment]
[cpr-win-test.zip](https://github.com/whoshuu/cpr/files/7107014/cpr-win-test.zip)
Does this one work for you?

**Comment by ChungZH** [comment]
yes, it does.

**Comment by COM8** [comment]
Then please try to extend my test case step by step, until it stops working for you since both work for me.
