### ISSUE TITLE
Response/Return value filter?!

### ISSUE THREAD

**Issue by dontknowanything23** [whoshuu/cpr#626]
Hello, got a Post API Call. My output is like: {"id":9071045551,"key":"5fnyoc9lus6vtr6","created_at": ......}
Now i want to filter out the value of key to use it in further code. For example: "Your key is: 5fnyoc9lus6vtr6."
Can i realize it with cpr or do i need to use cpp itself?

```
std::string test() 
{
cpr::Response r = cpr::Post(cpr::Url{ "API URL HERE" },
		cpr::Body{ {"api_key", "KEY HERE"} },
		cpr::Header{ "Content-Type", "application/json"}, {"Accept", "application/json"} );
	
	std::string output = r.text;
	
	return output;
}
```

**Comment by COM8** [comment]
You are receiving JSON here. CPR is not Abe to parse it. For this you need some kind of JSON library.
For example you could use: [nlohmann/json](https://github.com/nlohmann/json)

Then do something like this:
```c++
#include <nlohmann/json.hpp>
// Your code…
nlohmann::json j = r.text.
std::cout << j[„key“] << std::endl;
```

**Comment by dontknowanything23** [comment]
Appreciated. 

//Closed
//Solved
