### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by SquitchYT** [whoshuu/cpr#628]
Hello, while trying to use the example code, but i have an error when building with cmake:
```
error: « dummy » .... [-Werror=maybe-uninitialized]
 1301 |   StackLowerThanAddress(&dummy, &result);
      |   ~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~
``` the return code is 2
Have you any idea ?

**Comment by SquitchYT** [comment]
Up: I have found this issues : https://github.com/whoshuu/cpr/issues/607, if this solution work for me, I closed this issues

**Comment by SquitchYT** [comment]
I have found the solution. See https://github.com/whoshuu/cpr/issues/194 if interested. I close the issues (Thanks for the amazing libs)

**Comment by COM8** [comment]
When using GCC 11.11 on fedora with cpr 1.6.2 I can reproduce this issue.
It looks like something in google test is broken.
As a way around try the following:
```bash
cmake .. -DCPR_BUILD_TESTS=OFF
```

**Comment by COM8** [comment]
https://github.com/google/googletest/issues/3219
