### ISSUE TITLE
Error LINK

### ISSUE THREAD

**Issue by SquitchYT** [whoshuu/cpr#630]
Hello, I have an error when removed the uild folder 
```
error while loading shared libraries: libcpr.so.1: cannot open shared object file: No such file or directory
``` I use cmake. I can workaround by adding `-DBUILD_SHARED_LIBS=False` to cmake command but I want to find a cleaner way fir this problem.

**Comment by COM8** [comment]
So, you are trying to build cpr as a static lib, right?
And then when you link against it and remove the `build` directory, it's missing the shared cpr lib?

**Comment by SquitchYT** [comment]
Yes is exactly that. For linking as SHARED cpr, actually I use the exemple CMakeLists.txt

**Comment by COM8** [comment]
Ping @KingKili

**Comment by KingKili** [comment]
You used `-DBUILD_SHARED_LIBS=False` which is the correct way of building CPR as a static library. 
If I read this issue correctly you want to get rid of this option.
 To do so I would recommend setting the variable at the beginning of your `CMakelists.txt`.
E.G. `set(BUILD_SHARED_LIBS False FORCE) `or `option(BUILD_SHARED_LIBS "" False)`. Note that I think that you can remove the `FORCE` parameter in the set.

**Comment by SquitchYT** [comment]
Okay thanks for your response. I new with CMake and so I don't know the option() func. Bye
