### ISSUE TITLE
proxy_tests fail when not using USE_SYSTEM_CURL is off

### ISSUE THREAD

**Issue by bobjansen** [whoshuu/cpr#71]
I'm on Ubuntu 15.10 and compile using `gcc version 5.2.1 20151010 (Ubuntu 5.2.1-22ubuntu2)` 
 with all relevant packages updated and proxy_tests fails the https related tests:

```
 [ RUN      ] ProxyTests.MultipleProxyHttpsTest
 /home/brj/Code/cpr/test/proxy_tests.cpp:40: Failure
```

which I believe is currently the only test that uses a https URL. Using SYSTEM_CURL by changing the `CMakeLists.txt` solves the problem (for me). Is this a common issue? Is being unable to use SYSTEM_CURL a common issue?

**Comment by bobjansen** [comment]
Duplicate of #59?

**Comment by COM8** [comment]
Should be fixed. Feel free to open a new issue in case this is still a problem.
