### ISSUE TITLE
Build system integration examples

### ISSUE THREAD

**Issue by sholsapp** [whoshuu/cpr#76]
Hi there, great project!

I'm trying to add cpr to one of my projects and cannot get the configuration correct. I'm admittedly new to CMake and was wondering if it would be useful to others if we added more build system integration examples besides just the `add_project(cpr)` bit in the documentation. Right now I'm struggling to figure out how to integrate cpr such that i) it doesn't use system curl nor internally packaged curl (instead I want it to use one that I've built myself in the project) and ii) it doesn't build the test dependencies. I think adding a bit more content to this section would be super useful.

Thanks! If there are things I can contribute here I would be happy to. :beers:

**Comment by whoshuu** [comment]
Hey @sholsapp, this is an awesome suggestion. I think documentation is pretty light on the integration side, and would definitely appreciate any help I can get here.

By the way, have you taken a look at the [example project](https://github.com/whoshuu/cpr-example). I recommend forking that and trying to build it as a first step. I understand the options aren't explicit in the example, and I can do a bit more explaining them.

As for cpr picking the right curl library, cpr simply uses `find_package(CURL)` if `USE_SYSTEM_CURL` is set to `ON`. You can find documentation for how this command works [here](https://github.com/Kitware/CMake/blob/master/Modules/FindCURL.cmake).

**Comment by COM8** [comment]
Should be fixed since we now provide more information in the README.md.
