### ISSUE TITLE
README.md typo

### ISSUE THREAD

**Issue by danielcardeenas** [whoshuu/cpr#80]
In the README example:
`r.headers["content-type"];      // application/json; charset=utf-8`

should be `r.header`

**Comment by sam-bristow** [comment]
The python requests api uses the plural version (`r.headers`) in their API. Is it worth changing cpr to be consistent with that project? Or is this going to annoy all the existing users of cpr?

**Comment by danielcardeenas** [comment]
Just saying there is no member 'headers' in the library. But 'header' do exists.

**Comment by sam-bristow** [comment]
Yes, I got part-way through a pull request to fix that when I checked how python-requests does it.

There are two options to resolve the issue:
* Update the Readme to use the member `header`.
* Update the member to be called `headers` which matches the Readme and python-requests.

Either would work, it's just a question of which option the maintainers prefer. :-)

**Comment by sam-bristow** [comment]
As this library has already had a 1.0 release and is using semver I suggest that (unless there are other API changes planned) the first option is the easiest.
