### ISSUE TITLE
Getting several errors

### ISSUE THREAD

**Issue by ghost** [whoshuu/cpr#87]
`In file included from ./cpr/cpr/api.h:8:
./cpr/cpr/auth.h:14:43: error: expected member name or ';' after declaration
      specifiers
            : username_{CPR_FWD(username)}, password_{CPR_FWD(password)},
                                          ^
./cpr/cpr/auth.h:14:24: error: expected '('
            : username_{CPR_FWD(username)}, password_{CPR_FWD(password)},
                       ^
./cpr/cpr/auth.h:14:42: error: expected ';' after expression
            : username_{CPR_FWD(username)}, password_{CPR_FWD(password)},
                                         ^
                                         ;
In file included from crack.cpp:1:
In file included from ./cpr/cpr.h:4:
In file included from ./cpr/cpr/api.h:9:
./cpr/cpr/cprtypes.h:10:70: error: expected ';' at end of declaration list
    bool operator()(const std::string& a, const std::string& b) const noexcept;
                                                                     ^
                                                                     ;
In file included from crack.cpp:1:
In file included from ./cpr/cpr.h:4:
In file included from ./cpr/cpr/api.h:11:
./cpr/cpr/digest.h:13:68: error: expected member name or ';' after declaration
      specifiers
            : Authentication{CPR_FWD(username), CPR_FWD(password)} {}
                                                                   ^
./cpr/cpr/digest.h:13:29: error: expected '('
            : Authentication{CPR_FWD(username), CPR_FWD(password)} {}
                            ^
./cpr/cpr/digest.h:13:66: error: expected ';' after expression
            : Authentication{CPR_FWD(username), CPR_FWD(password)} {}
                                                                 ^
                                                                 ;
In file included from crack.cpp:1:
In file included from ./cpr/cpr.h:4:
In file included from ./cpr/cpr/api.h:12:
./cpr/cpr/multipart.h:14:72: error: expected member name or ';' after
      declaration specifiers
    explicit File(StringType&& filepath) : filepath{CPR_FWD(filepath)} {}
                                                                       ^
./cpr/cpr/multipart.h:14:52: error: expected '('
    explicit File(StringType&& filepath) : filepath{CPR_FWD(filepath)} {}
                                                   ^
./cpr/cpr/multipart.h:14:70: error: expected ';' after expression
    explicit File(StringType&& filepath) : filepath{CPR_FWD(filepath)} {}
                                                                     ^
                                                                     ;
./cpr/cpr/multipart.h:20:25: error: expected member name or ';' after
      declaration specifiers
            : name{name}, value{value}, content_type{content_type}, is_f...
                        ^
./cpr/cpr/multipart.h:19:95: error: expected expression
  ...name, const std::string& value, const std::string& content_type = {})
                                                                       ^
./cpr/cpr/multipart.h:20:19: error: expected '('
            : name{name}, value{value}, content_type{content_type}, is_f...
                  ^
./cpr/cpr/multipart.h:20:24: error: expected ';' after expression
            : name{name}, value{value}, content_type{content_type}, is_f...
                       ^
                       ;
./cpr/cpr/multipart.h:35:26: error: no type named 'initializer_list' in
      namespace 'std'
    Multipart(const std::initializer_list<Part>& parts);
                    ~~~~~^
./cpr/cpr/multipart.h:35:42: error: expected ')'
    Multipart(const std::initializer_list<Part>& parts);
                                         ^
./cpr/cpr/multipart.h:35:14: note: to match this '('
    Multipart(const std::initializer_list<Part>& parts);
             ^
In file included from crack.cpp:1:
In file included from ./cpr/cpr.h:4:
In file included from ./cpr/cpr/api.h:13:
./cpr/cpr/payload.h:16:34: error: expected member name or ';' after declaration
      specifiers
            : key{CPR_FWD(p_key)}, value{CPR_FWD(p_value)} {}
                                 ^
./cpr/cpr/payload.h:16:18: error: expected '('
            : key{CPR_FWD(p_key)}, value{CPR_FWD(p_value)} {}`

**Comment by whoshuu** [comment]
@Lloydaaa, what compiler are you using btw?

**Comment by Lloydaaa** [comment]
I'm using g++ with the C++11 flag, on Mac OSX.

**Comment by whoshuu** [comment]
It looks like your headers are located in `cpr/cpr/`, when the library has them in `include/cpr/`. Do you think that might be the issue?

**Comment by danielbarbarito** [comment]
I had this problem too. I fixed it by putting `set (CMAKE_CXX_STANDARD 11)` in my CMakeLists.txt
