### ISSUE TITLE
Move SSL verification from compile time to runtime option

### ISSUE THREAD

**Issue by jlisee** [whoshuu/cpr#95]
Just like the curl commandline program or library I would like to be able set some kind of flag or option to disable SSL certificate checks.  During development you don't always have those setup and it doesn't make sense to disable 100% of the time by rebuilding the library:

The lines of code are in `cpr/session.cpp`

``` cpp
#ifdef INSECURE_CURL
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYPEER, 0L);
        curl_easy_setopt(curl, CURLOPT_SSL_VERIFYHOST, 0L);
#endif
```

**Comment by whoshuu** [comment]
This is totally reasonable. I could imagine some object like `UseSsl(bool)` that by default is set to true on the session. Does that sound right to you?

**Comment by jlisee** [comment]
That sounds pretty, slick so the interface would be: `cpr::Get(cpr::Url{url}, crp::VerifySsl{false})`.  I went with `VerifySsl` because SSL would still be used, it just would not check if the connection was trusted.

**Comment by whoshuu** [comment]
That's a fair point about the name being `VerifySsl`!

**Comment by TheChuckster** [comment]
Is there a PR for this?

**Comment by whoshuu** [comment]
Fixed in https://github.com/whoshuu/cpr/commit/67d0b59e2eb3887afb4af3d34444f2ee32968c07.
