### ISSUE TITLE
What instruction should I add at compile and link time?

### ISSUE THREAD

**Issue by Lw-Cui** [whoshuu/cpr#96]
I wrote `Makefile` directly without using `cmake`. So compiler and linker cannot find `cpr` header and lib.
So please what instruction I should add at compile and link time, thanks!

**Comment by nabijaczleweli** [comment]
You're out in no man's land if you don't use CMake, so just fiddle with it 'till it works

**Comment by Lw-Cui** [comment]
Thanks.. Maybe it's the time for me to learn `CMake`:)
